// Auto-generated by codegen/aot-compile.ts — do not edit
// Contains both Bun-optimized (push) and V8-optimized (prealloc) variants

type CompiledRunner = (source: any[], fns: any[], a1s: any[]) => any

// Runtime detection — Bun uses JSC, Node/Deno use V8
const _isV8 = typeof (globalThis as any).Bun === "undefined"

// map
const map = _isV8
  ? function(src,f0) {var r=new Array(src.length);for(var i=0;i<src.length;i++){;var v=src[i];v=f0(v);r[i]=v;};return r}
  : function(src,f0) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];v=f0(v);r.push(v);};return r}

const run_map: CompiledRunner = (src, fns) => map(src,fns[0])

// filter
const filter = function(src,f0) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;r.push(v);};return r}

const run_filter: CompiledRunner = (src, fns) => filter(src,fns[0])

// take
const take = function(src,f0) {var c0=0;var r=[];for(var i=0;i<src.length&&c0<f0;i++){;var v=src[i];c0++;r.push(v);};return r}

const run_take: CompiledRunner = (src, fns) => take(src,fns[0])

// drop
const drop = function(src,f0) {var d0=0;var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(d0<f0){d0++;continue};r.push(v);};return r}

const run_drop: CompiledRunner = (src, fns) => drop(src,fns[0])

// reject
const reject = function(src,f0) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(f0(v))continue;r.push(v);};return r}

const run_reject: CompiledRunner = (src, fns) => reject(src,fns[0])

// takeWhile
const takeWhile = function(src,f0) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))break;r.push(v);};return r}

const run_takeWhile: CompiledRunner = (src, fns) => takeWhile(src,fns[0])

// dropWhile
const dropWhile = function(src,f0) {var dw0=true;var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(dw0){if(f0(v))continue;dw0=false};r.push(v);};return r}

const run_dropWhile: CompiledRunner = (src, fns) => dropWhile(src,fns[0])

// flatMap
const flatMap = function(src,f0) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];var items0=f0(v);for(var j0=0;j0<items0.length;j0++){;v=items0[j0];r.push(v);};};return r}

const run_flatMap: CompiledRunner = (src, fns) => flatMap(src,fns[0])

// filter → map
const filter_map = function(src,f0,f1) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;v=f1(v);r.push(v);};return r}

const run_filter_map: CompiledRunner = (src, fns) => filter_map(src,fns[0],fns[1])

// map → filter
const map_filter = function(src,f0,f1) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];v=f0(v);if(!f1(v))continue;r.push(v);};return r}

const run_map_filter: CompiledRunner = (src, fns) => map_filter(src,fns[0],fns[1])

// filter → take
const filter_take = function(src,f0,f1) {var c1=0;var r=[];for(var i=0;i<src.length&&c1<f1;i++){;var v=src[i];if(!f0(v))continue;c1++;r.push(v);};return r}

const run_filter_take: CompiledRunner = (src, fns) => filter_take(src,fns[0],fns[1])

// map → take
const map_take = function(src,f0,f1) {var c1=0;var r=[];for(var i=0;i<src.length&&c1<f1;i++){;var v=src[i];v=f0(v);c1++;r.push(v);};return r}

const run_map_take: CompiledRunner = (src, fns) => map_take(src,fns[0],fns[1])

// drop → map
const drop_map = function(src,f0,f1) {var d0=0;var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(d0<f0){d0++;continue};v=f1(v);r.push(v);};return r}

const run_drop_map: CompiledRunner = (src, fns) => drop_map(src,fns[0],fns[1])

// drop → filter
const drop_filter = function(src,f0,f1) {var d0=0;var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(d0<f0){d0++;continue};if(!f1(v))continue;r.push(v);};return r}

const run_drop_filter: CompiledRunner = (src, fns) => drop_filter(src,fns[0],fns[1])

// filter → reject
const filter_reject = function(src,f0,f1) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;if(f1(v))continue;r.push(v);};return r}

const run_filter_reject: CompiledRunner = (src, fns) => filter_reject(src,fns[0],fns[1])

// reject → map
const reject_map = function(src,f0,f1) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(f0(v))continue;v=f1(v);r.push(v);};return r}

const run_reject_map: CompiledRunner = (src, fns) => reject_map(src,fns[0],fns[1])

// flatMap → take
const flatMap_take = function(src,f0,f1) {var c1=0;var r=[];for(var i=0;i<src.length&&c1<f1;i++){;var v=src[i];var items0=f0(v);for(var j0=0;j0<items0.length;j0++){;v=items0[j0];c1++;r.push(v);};};return r}

const run_flatMap_take: CompiledRunner = (src, fns) => flatMap_take(src,fns[0],fns[1])

// flatMap → filter
const flatMap_filter = function(src,f0,f1) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];var items0=f0(v);for(var j0=0;j0<items0.length;j0++){;v=items0[j0];if(!f1(v))continue;r.push(v);};};return r}

const run_flatMap_filter: CompiledRunner = (src, fns) => flatMap_filter(src,fns[0],fns[1])

// flatMap → map
const flatMap_map = function(src,f0,f1) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];var items0=f0(v);for(var j0=0;j0<items0.length;j0++){;v=items0[j0];v=f1(v);r.push(v);};};return r}

const run_flatMap_map: CompiledRunner = (src, fns) => flatMap_map(src,fns[0],fns[1])

// map → flatMap
const map_flatMap = function(src,f0,f1) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];v=f0(v);var items1=f1(v);for(var j1=0;j1<items1.length;j1++){;v=items1[j1];r.push(v);};};return r}

const run_map_flatMap: CompiledRunner = (src, fns) => map_flatMap(src,fns[0],fns[1])

// filter → flatMap
const filter_flatMap = function(src,f0,f1) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;var items1=f1(v);for(var j1=0;j1<items1.length;j1++){;v=items1[j1];r.push(v);};};return r}

const run_filter_flatMap: CompiledRunner = (src, fns) => filter_flatMap(src,fns[0],fns[1])

// filter → map → take
const filter_map_take = function(src,f0,f1,f2) {var c2=0;var r=[];for(var i=0;i<src.length&&c2<f2;i++){;var v=src[i];if(!f0(v))continue;v=f1(v);c2++;r.push(v);};return r}

const run_filter_map_take: CompiledRunner = (src, fns) => filter_map_take(src,fns[0],fns[1],fns[2])

// map → filter → take
const map_filter_take = function(src,f0,f1,f2) {var c2=0;var r=[];for(var i=0;i<src.length&&c2<f2;i++){;var v=src[i];v=f0(v);if(!f1(v))continue;c2++;r.push(v);};return r}

const run_map_filter_take: CompiledRunner = (src, fns) => map_filter_take(src,fns[0],fns[1],fns[2])

// drop → filter → map
const drop_filter_map = function(src,f0,f1,f2) {var d0=0;var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(d0<f0){d0++;continue};if(!f1(v))continue;v=f2(v);r.push(v);};return r}

const run_drop_filter_map: CompiledRunner = (src, fns) => drop_filter_map(src,fns[0],fns[1],fns[2])

// filter → map → reject
const filter_map_reject = function(src,f0,f1,f2) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;v=f1(v);if(f2(v))continue;r.push(v);};return r}

const run_filter_map_reject: CompiledRunner = (src, fns) => filter_map_reject(src,fns[0],fns[1],fns[2])

// filter → reject → take
const filter_reject_take = function(src,f0,f1,f2) {var c2=0;var r=[];for(var i=0;i<src.length&&c2<f2;i++){;var v=src[i];if(!f0(v))continue;if(f1(v))continue;c2++;r.push(v);};return r}

const run_filter_reject_take: CompiledRunner = (src, fns) => filter_reject_take(src,fns[0],fns[1],fns[2])

// drop → map → take
const drop_map_take = function(src,f0,f1,f2) {var d0=0;var c2=0;var r=[];for(var i=0;i<src.length&&c2<f2;i++){;var v=src[i];if(d0<f0){d0++;continue};v=f1(v);c2++;r.push(v);};return r}

const run_drop_map_take: CompiledRunner = (src, fns) => drop_map_take(src,fns[0],fns[1],fns[2])

// drop → filter → take
const drop_filter_take = function(src,f0,f1,f2) {var d0=0;var c2=0;var r=[];for(var i=0;i<src.length&&c2<f2;i++){;var v=src[i];if(d0<f0){d0++;continue};if(!f1(v))continue;c2++;r.push(v);};return r}

const run_drop_filter_take: CompiledRunner = (src, fns) => drop_filter_take(src,fns[0],fns[1],fns[2])

// filter → flatMap → take
const filter_flatMap_take = function(src,f0,f1,f2) {var c2=0;var r=[];for(var i=0;i<src.length&&c2<f2;i++){;var v=src[i];if(!f0(v))continue;var items1=f1(v);for(var j1=0;j1<items1.length;j1++){;v=items1[j1];c2++;r.push(v);};};return r}

const run_filter_flatMap_take: CompiledRunner = (src, fns) => filter_flatMap_take(src,fns[0],fns[1],fns[2])

// drop → filter → map → take
const drop_filter_map_take = function(src,f0,f1,f2,f3) {var d0=0;var c3=0;var r=[];for(var i=0;i<src.length&&c3<f3;i++){;var v=src[i];if(d0<f0){d0++;continue};if(!f1(v))continue;v=f2(v);c3++;r.push(v);};return r}

const run_drop_filter_map_take: CompiledRunner = (src, fns) => drop_filter_map_take(src,fns[0],fns[1],fns[2],fns[3])

// filter → map → flatMap → filter
const filter_map_flatMap_filter = function(src,f0,f1,f2,f3) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;v=f1(v);var items2=f2(v);for(var j2=0;j2<items2.length;j2++){;v=items2[j2];if(!f3(v))continue;r.push(v);};};return r}

const run_filter_map_flatMap_filter: CompiledRunner = (src, fns) => filter_map_flatMap_filter(src,fns[0],fns[1],fns[2],fns[3])

// filter → map → flatMap → filter → take
const filter_map_flatMap_filter_take = function(src,f0,f1,f2,f3,f4) {var c4=0;var r=[];for(var i=0;i<src.length&&c4<f4;i++){;var v=src[i];if(!f0(v))continue;v=f1(v);var items2=f2(v);for(var j2=0;j2<items2.length;j2++){;v=items2[j2];if(!f3(v))continue;c4++;r.push(v);};};return r}

const run_filter_map_flatMap_filter_take: CompiledRunner = (src, fns) => filter_map_flatMap_filter_take(src,fns[0],fns[1],fns[2],fns[3],fns[4])

// reduce
const reduce = function(src,f0,init) {var acc=init;for(var i=0;i<src.length;i++){;var v=src[i];acc=f0(acc,v);};return acc}

const run_reduce: CompiledRunner = (src, fns, a1s) => {
  const args = [src]
  for (let i = 0; i < 1; i++) args.push(fns[i])
  args.push(a1s[0])
  return reduce.apply(null, args)
}

// filter → reduce
const filter_reduce = function(src,f0,f1,init) {var acc=init;for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;acc=f1(acc,v);};return acc}

const run_filter_reduce: CompiledRunner = (src, fns, a1s) => {
  const args = [src]
  for (let i = 0; i < 2; i++) args.push(fns[i])
  args.push(a1s[1])
  return filter_reduce.apply(null, args)
}

// map → reduce
const map_reduce = function(src,f0,f1,init) {var acc=init;for(var i=0;i<src.length;i++){;var v=src[i];v=f0(v);acc=f1(acc,v);};return acc}

const run_map_reduce: CompiledRunner = (src, fns, a1s) => {
  const args = [src]
  for (let i = 0; i < 2; i++) args.push(fns[i])
  args.push(a1s[1])
  return map_reduce.apply(null, args)
}

// filter → map → reduce
const filter_map_reduce = function(src,f0,f1,f2,init) {var acc=init;for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;v=f1(v);acc=f2(acc,v);};return acc}

const run_filter_map_reduce: CompiledRunner = (src, fns, a1s) => {
  const args = [src]
  for (let i = 0; i < 3; i++) args.push(fns[i])
  args.push(a1s[2])
  return filter_map_reduce.apply(null, args)
}

// forEach
const forEach = function(src,f0) {for(var i=0;i<src.length;i++){;var v=src[i];f0(v);}}

const run_forEach: CompiledRunner = (src, fns) => forEach(src,fns[0])

// map → forEach
const map_forEach = function(src,f0,f1) {for(var i=0;i<src.length;i++){;var v=src[i];v=f0(v);f1(v);}}

const run_map_forEach: CompiledRunner = (src, fns) => map_forEach(src,fns[0],fns[1])

// filter → forEach
const filter_forEach = function(src,f0,f1) {for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;f1(v);}}

const run_filter_forEach: CompiledRunner = (src, fns) => filter_forEach(src,fns[0],fns[1])

// every
const every = function(src,f0) {var ev=true;for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v)){ev=false;break};};return ev}

const run_every: CompiledRunner = (src, fns) => every(src,fns[0])

// filter → every
const filter_every = function(src,f0,f1) {var ev=true;for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;if(!f1(v)){ev=false;break};};return ev}

const run_filter_every: CompiledRunner = (src, fns) => filter_every(src,fns[0],fns[1])

// map → every
const map_every = function(src,f0,f1) {var ev=true;for(var i=0;i<src.length;i++){;var v=src[i];v=f0(v);if(!f1(v)){ev=false;break};};return ev}

const run_map_every: CompiledRunner = (src, fns) => map_every(src,fns[0],fns[1])

// some
const some = function(src,f0) {var sm=false;for(var i=0;i<src.length;i++){;var v=src[i];if(f0(v)){sm=true;break};};return sm}

const run_some: CompiledRunner = (src, fns) => some(src,fns[0])

// filter → some
const filter_some = function(src,f0,f1) {var sm=false;for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;if(f1(v)){sm=true;break};};return sm}

const run_filter_some: CompiledRunner = (src, fns) => filter_some(src,fns[0],fns[1])

// map → some
const map_some = function(src,f0,f1) {var sm=false;for(var i=0;i<src.length;i++){;var v=src[i];v=f0(v);if(f1(v)){sm=true;break};};return sm}

const run_map_some: CompiledRunner = (src, fns) => map_some(src,fns[0],fns[1])

// find
const find = function(src,f0) {for(var i=0;i<src.length;i++){;var v=src[i];if(f0(v))return v;};return undefined}

const run_find: CompiledRunner = (src, fns) => find(src,fns[0])

// filter → find
const filter_find = function(src,f0,f1) {for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;if(f1(v))return v;};return undefined}

const run_filter_find: CompiledRunner = (src, fns) => filter_find(src,fns[0],fns[1])

// map → find
const map_find = function(src,f0,f1) {for(var i=0;i<src.length;i++){;var v=src[i];v=f0(v);if(f1(v))return v;};return undefined}

const run_map_find: CompiledRunner = (src, fns) => map_find(src,fns[0],fns[1])

// findIndex
const findIndex = function(src,f0) {var fi=0;for(var i=0;i<src.length;i++){;var v=src[i];if(f0(v))return fi;fi++;};return undefined}

const run_findIndex: CompiledRunner = (src, fns) => findIndex(src,fns[0])

// filter → findIndex
const filter_findIndex = function(src,f0,f1) {var fi=0;for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;if(f1(v))return fi;fi++;};return undefined}

const run_filter_findIndex: CompiledRunner = (src, fns) => filter_findIndex(src,fns[0],fns[1])

// map → findIndex
const map_findIndex = function(src,f0,f1) {var fi=0;for(var i=0;i<src.length;i++){;var v=src[i];v=f0(v);if(f1(v))return fi;fi++;};return undefined}

const run_map_findIndex: CompiledRunner = (src, fns) => map_findIndex(src,fns[0],fns[1])

// none
const none = function(src,f0) {var nn=false;for(var i=0;i<src.length;i++){;var v=src[i];if(f0(v)){nn=true;break};};return !nn}

const run_none: CompiledRunner = (src, fns) => none(src,fns[0])

// filter → none
const filter_none = function(src,f0,f1) {var nn=false;for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;if(f1(v)){nn=true;break};};return !nn}

const run_filter_none: CompiledRunner = (src, fns) => filter_none(src,fns[0],fns[1])

// count
const count = function(src,f0) {var cnt=0;for(var i=0;i<src.length;i++){;var v=src[i];if(f0(v))cnt++;};return cnt}

const run_count: CompiledRunner = (src, fns) => count(src,fns[0])

// filter → count
const filter_count = function(src,f0,f1) {var cnt=0;for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;if(f1(v))cnt++;};return cnt}

const run_filter_count: CompiledRunner = (src, fns) => filter_count(src,fns[0],fns[1])

// filter → head
const filter_head = function(src,f0,f1) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;r.push(v);};return r[0]}

const run_filter_head: CompiledRunner = (src, fns) => filter_head(src,fns[0],fns[1])

// filter → last
const filter_last = function(src,f0,f1) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;r.push(v);};return r[r.length-1]}

const run_filter_last: CompiledRunner = (src, fns) => filter_last(src,fns[0],fns[1])

// filter → length
const filter_length = function(src,f0,f1) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;r.push(v);};return r.length}

const run_filter_length: CompiledRunner = (src, fns) => filter_length(src,fns[0],fns[1])

// filter → isEmpty
const filter_isEmpty = function(src,f0,f1) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;r.push(v);};return r.length===0}

const run_filter_isEmpty: CompiledRunner = (src, fns) => filter_isEmpty(src,fns[0],fns[1])

// map → head
const map_head = _isV8
  ? function(src,f0,f1) {var r=new Array(src.length);for(var i=0;i<src.length;i++){;var v=src[i];v=f0(v);r[i]=v;};return r[0]}
  : function(src,f0,f1) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];v=f0(v);r.push(v);};return r[0]}

const run_map_head: CompiledRunner = (src, fns) => map_head(src,fns[0],fns[1])

// map → last
const map_last = _isV8
  ? function(src,f0,f1) {var r=new Array(src.length);for(var i=0;i<src.length;i++){;var v=src[i];v=f0(v);r[i]=v;};return r[r.length-1]}
  : function(src,f0,f1) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];v=f0(v);r.push(v);};return r[r.length-1]}

const run_map_last: CompiledRunner = (src, fns) => map_last(src,fns[0],fns[1])

// map → length
const map_length = _isV8
  ? function(src,f0,f1) {var r=new Array(src.length);for(var i=0;i<src.length;i++){;var v=src[i];v=f0(v);r[i]=v;};return r.length}
  : function(src,f0,f1) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];v=f0(v);r.push(v);};return r.length}

const run_map_length: CompiledRunner = (src, fns) => map_length(src,fns[0],fns[1])

// filter → map → head
const filter_map_head = function(src,f0,f1,f2) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;v=f1(v);r.push(v);};return r[0]}

const run_filter_map_head: CompiledRunner = (src, fns) => filter_map_head(src,fns[0],fns[1],fns[2])

// filter → map → last
const filter_map_last = function(src,f0,f1,f2) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;v=f1(v);r.push(v);};return r[r.length-1]}

const run_filter_map_last: CompiledRunner = (src, fns) => filter_map_last(src,fns[0],fns[1],fns[2])

// filter → map → length
const filter_map_length = function(src,f0,f1,f2) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;v=f1(v);r.push(v);};return r.length}

const run_filter_map_length: CompiledRunner = (src, fns) => filter_map_length(src,fns[0],fns[1],fns[2])

// filter → map → sum
const filter_map_sum = function(src,f0,f1,f2) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;v=f1(v);r.push(v);};var s=0;for(var si=0;si<r.length;si++)s+=r[si];return s}

const run_filter_map_sum: CompiledRunner = (src, fns) => filter_map_sum(src,fns[0],fns[1],fns[2])

// filter → map → min
const filter_map_min = function(src,f0,f1,f2) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;v=f1(v);r.push(v);};var mn=r[0];for(var mi=1;mi<r.length;mi++)if(r[mi]<mn)mn=r[mi];return mn}

const run_filter_map_min: CompiledRunner = (src, fns) => filter_map_min(src,fns[0],fns[1],fns[2])

// filter → map → max
const filter_map_max = function(src,f0,f1,f2) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;v=f1(v);r.push(v);};var mx=r[0];for(var mi=1;mi<r.length;mi++)if(r[mi]>mx)mx=r[mi];return mx}

const run_filter_map_max: CompiledRunner = (src, fns) => filter_map_max(src,fns[0],fns[1],fns[2])

// filter → sum
const filter_sum = function(src,f0,f1) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;r.push(v);};var s=0;for(var si=0;si<r.length;si++)s+=r[si];return s}

const run_filter_sum: CompiledRunner = (src, fns) => filter_sum(src,fns[0],fns[1])

// filter → min
const filter_min = function(src,f0,f1) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;r.push(v);};var mn=r[0];for(var mi=1;mi<r.length;mi++)if(r[mi]<mn)mn=r[mi];return mn}

const run_filter_min: CompiledRunner = (src, fns) => filter_min(src,fns[0],fns[1])

// filter → max
const filter_max = function(src,f0,f1) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;r.push(v);};var mx=r[0];for(var mi=1;mi<r.length;mi++)if(r[mi]>mx)mx=r[mi];return mx}

const run_filter_max: CompiledRunner = (src, fns) => filter_max(src,fns[0],fns[1])

// map → sum
const map_sum = _isV8
  ? function(src,f0,f1) {var r=new Array(src.length);for(var i=0;i<src.length;i++){;var v=src[i];v=f0(v);r[i]=v;};var s=0;for(var si=0;si<r.length;si++)s+=r[si];return s}
  : function(src,f0,f1) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];v=f0(v);r.push(v);};var s=0;for(var si=0;si<r.length;si++)s+=r[si];return s}

const run_map_sum: CompiledRunner = (src, fns) => map_sum(src,fns[0],fns[1])

// map → min
const map_min = _isV8
  ? function(src,f0,f1) {var r=new Array(src.length);for(var i=0;i<src.length;i++){;var v=src[i];v=f0(v);r[i]=v;};var mn=r[0];for(var mi=1;mi<r.length;mi++)if(r[mi]<mn)mn=r[mi];return mn}
  : function(src,f0,f1) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];v=f0(v);r.push(v);};var mn=r[0];for(var mi=1;mi<r.length;mi++)if(r[mi]<mn)mn=r[mi];return mn}

const run_map_min: CompiledRunner = (src, fns) => map_min(src,fns[0],fns[1])

// map → max
const map_max = _isV8
  ? function(src,f0,f1) {var r=new Array(src.length);for(var i=0;i<src.length;i++){;var v=src[i];v=f0(v);r[i]=v;};var mx=r[0];for(var mi=1;mi<r.length;mi++)if(r[mi]>mx)mx=r[mi];return mx}
  : function(src,f0,f1) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];v=f0(v);r.push(v);};var mx=r[0];for(var mi=1;mi<r.length;mi++)if(r[mi]>mx)mx=r[mi];return mx}

const run_map_max: CompiledRunner = (src, fns) => map_max(src,fns[0],fns[1])

// filter → reverse
const filter_reverse = function(src,f0,f1) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;r.push(v);};return r.reverse()}

const run_filter_reverse: CompiledRunner = (src, fns) => filter_reverse(src,fns[0],fns[1])

// map → reverse
const map_reverse = _isV8
  ? function(src,f0,f1) {var r=new Array(src.length);for(var i=0;i<src.length;i++){;var v=src[i];v=f0(v);r[i]=v;};return r.reverse()}
  : function(src,f0,f1) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];v=f0(v);r.push(v);};return r.reverse()}

const run_map_reverse: CompiledRunner = (src, fns) => map_reverse(src,fns[0],fns[1])

// filter → uniq
const filter_uniq = function(src,f0,f1) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;r.push(v);};return Array.from(new Set(r))}

const run_filter_uniq: CompiledRunner = (src, fns) => filter_uniq(src,fns[0],fns[1])

// map → uniq
const map_uniq = _isV8
  ? function(src,f0,f1) {var r=new Array(src.length);for(var i=0;i<src.length;i++){;var v=src[i];v=f0(v);r[i]=v;};return Array.from(new Set(r))}
  : function(src,f0,f1) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];v=f0(v);r.push(v);};return Array.from(new Set(r))}

const run_map_uniq: CompiledRunner = (src, fns) => map_uniq(src,fns[0],fns[1])

// filter → map → sortAsc
const filter_map_sortAsc = function(src,f0,f1,f2) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;v=f1(v);r.push(v);};return r}

const run_filter_map_sortAsc: CompiledRunner = (src, fns) => filter_map_sortAsc(src,fns[0],fns[1],fns[2])

// filter → map → sortDesc
const filter_map_sortDesc = function(src,f0,f1,f2) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;v=f1(v);r.push(v);};return r}

const run_filter_map_sortDesc: CompiledRunner = (src, fns) => filter_map_sortDesc(src,fns[0],fns[1],fns[2])

// filter → tail
const filter_tail = function(src,f0,f1) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;r.push(v);};return r.slice(1)}

const run_filter_tail: CompiledRunner = (src, fns) => filter_tail(src,fns[0],fns[1])

// filter → init
const filter_init = function(src,f0,f1) {var r=[];for(var i=0;i<src.length;i++){;var v=src[i];if(!f0(v))continue;r.push(v);};return r.slice(0,-1)}

const run_filter_init: CompiledRunner = (src, fns) => filter_init(src,fns[0],fns[1])

export const aotCache = new Map<number, CompiledRunner>([
  [2, run_map],
  [4, run_filter],
  [6, run_take],
  [8, run_drop],
  [32, run_reject],
  [10, run_takeWhile],
  [12, run_dropWhile],
  [14, run_flatMap],
  [1026, run_filter_map],
  [516, run_map_filter],
  [1030, run_filter_take],
  [518, run_map_take],
  [2050, run_drop_map],
  [2052, run_drop_filter],
  [1056, run_filter_reject],
  [8194, run_reject_map],
  [3590, run_flatMap_take],
  [3588, run_flatMap_filter],
  [3586, run_flatMap_map],
  [526, run_map_flatMap],
  [1038, run_filter_flatMap],
  [262662, run_filter_map_take],
  [132102, run_map_filter_take],
  [525314, run_drop_filter_map],
  [262688, run_filter_map_reject],
  [270342, run_filter_reject_take],
  [524806, run_drop_map_take],
  [525318, run_drop_filter_take],
  [265734, run_filter_flatMap_take],
  [134480390, run_drop_filter_map_take],
  [67243524, run_filter_map_flatMap_filter],
  [17214342150, run_filter_map_flatMap_filter_take],
  [16, run_reduce],
  [1040, run_filter_reduce],
  [528, run_map_reduce],
  [262672, run_filter_map_reduce],
  [18, run_forEach],
  [530, run_map_forEach],
  [1042, run_filter_forEach],
  [20, run_every],
  [1044, run_filter_every],
  [532, run_map_every],
  [22, run_some],
  [1046, run_filter_some],
  [534, run_map_some],
  [24, run_find],
  [1048, run_filter_find],
  [536, run_map_find],
  [26, run_findIndex],
  [1050, run_filter_findIndex],
  [538, run_map_findIndex],
  [34, run_none],
  [1058, run_filter_none],
  [36, run_count],
  [1060, run_filter_count],
  [1084, run_filter_head],
  [1086, run_filter_last],
  [1088, run_filter_length],
  [1090, run_filter_isEmpty],
  [572, run_map_head],
  [574, run_map_last],
  [576, run_map_length],
  [262716, run_filter_map_head],
  [262718, run_filter_map_last],
  [262720, run_filter_map_length],
  [262738, run_filter_map_sum],
  [262740, run_filter_map_min],
  [262742, run_filter_map_max],
  [1106, run_filter_sum],
  [1108, run_filter_min],
  [1110, run_filter_max],
  [594, run_map_sum],
  [596, run_map_min],
  [598, run_map_max],
  [1096, run_filter_reverse],
  [584, run_map_reverse],
  [1100, run_filter_uniq],
  [588, run_map_uniq],
  [262836, run_filter_map_sortAsc],
  [262838, run_filter_map_sortDesc],
  [1092, run_filter_tail],
  [1094, run_filter_init],
])

// --- Named chain exports (zero fusion overhead) ---

export { filter_map as filterMap }
export { map_filter as mapFilter }
export { filter_take as filterTake }
export { map_take as mapTake }
export { filter_map_take as filterMapTake }
export { map_filter_take as mapFilterTake }
export { drop_filter_map as dropFilterMap }
export { drop_filter_map_take as dropFilterMapTake }
export { filter_reduce as filterReduce }
export { map_reduce as mapReduce }
export { filter_map_reduce as filterMapReduce }
export { filter_find as filterFind }
export { map_find as mapFind }
export { filter_every as filterEvery }
export { filter_some as filterSome }
export { map_every as mapEvery }
export { map_some as mapSome }
export { filter_head as filterHead }
export { filter_last as filterLast }
export { filter_length as filterCount }
export { filter_sum as filterSum }
export { map_sum as mapSum }
export { filter_map_sum as filterMapSum }
export { filter_min as filterMin }
export { filter_max as filterMax }
export { map_min as mapMin }
export { map_max as mapMax }
export { filter_map_head as filterMapHead }
export { filter_map_last as filterMapLast }
