// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_SortArray from "@rescript/runtime/lib/es6/Belt_SortArray.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let head = (function(arr) { return arr.length === 0 ? undefined : arr[0] });

let truncate = (function(a, n) { a.length = n });

let last = (function(arr) { return arr.length === 0 ? undefined : arr[arr.length - 1] });

function tail(arr) {
  if (arr.length <= 1) {
    return [];
  } else {
    return arr.slice(1);
  }
}

function init(arr) {
  let len = arr.length;
  if (len <= 1) {
    return [];
  } else {
    return arr.slice(0, len - 1 | 0);
  }
}

function isEmpty(arr) {
  return arr.length === 0;
}

function length(arr) {
  return arr.length;
}

function take(arr, n) {
  let len = arr.length;
  if (n <= 0) {
    return [];
  } else {
    return arr.slice(0, n > len ? len : n);
  }
}

function drop(arr, n) {
  let len = arr.length;
  if (n <= 0) {
    return arr.slice();
  } else if (n >= len) {
    return [];
  } else {
    return arr.slice(n);
  }
}

let takeWhile = (function(arr, pred) {
    var out = [];
    for (var i = 0, len = arr.length; i < len; i++) {
      if (!pred(arr[i])) break;
      out.push(arr[i]);
    }
    return out;
  });

let dropWhile = (function(arr, pred) {
    for (var i = 0, len = arr.length; i < len; i++) {
      if (!pred(arr[i])) return arr.slice(i);
    }
    return [];
  });

let chunk = (function(arr, n) {
    var len = arr.length;
    if (n <= 0 || len === 0) return [];
    var numChunks = ((len + n - 1) / n) | 0;
    var out = new Array(numChunks);
    for (var i = 0; i < numChunks; i++) {
      out[i] = arr.slice(i * n, i * n + n);
    }
    return out;
  });

function slidingWindow(arr, n) {
  let len = arr.length;
  if (n <= 0 || n > len) {
    return [];
  }
  let numWindows = (len - n | 0) + 1 | 0;
  let out = new Array(numWindows);
  for (let wi = 0; wi < numWindows; ++wi) {
    let win = new Array(n);
    for (let j = 0; j < n; ++j) {
      win[j] = arr[wi + j | 0];
    }
    out[wi] = win;
  }
  return out;
}

let map = (function(arr, f) {
    var len = arr.length, out = new Array(len);
    for (var i = 0; i < len; i++) out[i] = f(arr[i]);
    return out;
  });

let mapWithIndex = (function(arr, f) {
    var len = arr.length, out = new Array(len);
    for (var i = 0; i < len; i++) out[i] = f(arr[i], i);
    return out;
  });

function filter(arr, pred) {
  let result = [];
  for (let i = 0, i_finish = arr.length; i < i_finish; ++i) {
    let x = arr[i];
    if (pred(x)) {
      result.push(x);
    }
  }
  return result;
}

function filterWithIndex(arr, pred) {
  let result = [];
  for (let i = 0, i_finish = arr.length; i < i_finish; ++i) {
    let x = arr[i];
    if (pred(x, i)) {
      result.push(x);
    }
  }
  return result;
}

function forEach(arr, f) {
  let len = arr.length;
  for (let i = 0; i < len; ++i) {
    f(arr[i]);
  }
}

function forEachWithIndex(arr, f) {
  let len = arr.length;
  for (let i = 0; i < len; ++i) {
    f(arr[i], i);
  }
}

let reduce = (function(arr, f, init) {
    for (var i = 0, acc = init; i < arr.length; i++) acc = f(acc, arr[i]);
    return acc;
  });

let reduceRight = (function(arr, f, init) {
    for (var i = arr.length - 1, acc = init; i >= 0; i--) acc = f(acc, arr[i]);
    return acc;
  });

let flatMap = (function(arr, f) {
    var out = [];
    for (var i = 0; i < arr.length; i++) {
      var inner = f(arr[i]);
      for (var j = 0; j < inner.length; j++) out.push(inner[j]);
    }
    return out;
  });

let flatten = (function(arr) {
    var out = [];
    for (var i = 0; i < arr.length; i++) {
      var inner = arr[i];
      for (var j = 0; j < inner.length; j++) out.push(inner[j]);
    }
    return out;
  });

let find = (function(arr, pred) {
    for (var i = 0; i < arr.length; i++) { if (pred(arr[i])) return arr[i]; }
    return undefined;
  });

let findIndex = (function(arr, pred) {
    for (var i = 0; i < arr.length; i++) { if (pred(arr[i])) return i; }
    return undefined;
  });

let every = (function(arr, pred) {
    for (var i = 0; i < arr.length; i++) { if (!pred(arr[i])) return false; }
    return true;
  });

let some = (function(arr, pred) {
    for (var i = 0; i < arr.length; i++) { if (pred(arr[i])) return true; }
    return false;
  });

let includes = (function(arr, val) { return arr.indexOf(val) !== -1; });

let reverse = (function(arr) {
    var len = arr.length, out = new Array(len);
    for (var i = 0; i < len; i++) out[i] = arr[len - 1 - i];
    return out;
  });

function sort(arr) {
  return Belt_SortArray.stableSortBy(arr, (a, b) => {
    if (a < b) {
      return -1;
    } else if (a > b) {
      return 1;
    } else {
      return 0;
    }
  });
}

let sortBy = Belt_SortArray.stableSortBy;

let takeSortedBy = (function(arr, k, cmp) {
    var n = arr.length;
    if (k <= 0) return [];
    if (k >= n) return arr.slice().sort(cmp);
    // Copy to avoid mutating input
    var work = arr.slice();
    // Quickselect: partition work so that work[0..k-1] contains the k smallest
    var lo = 0, hi = n - 1;
    while (lo < hi) {
      var pivot = work[lo + ((hi - lo) >> 1)];
      var i = lo, j = hi;
      while (i <= j) {
        while (cmp(work[i], pivot) < 0) i++;
        while (cmp(work[j], pivot) > 0) j--;
        if (i <= j) { var tmp = work[i]; work[i] = work[j]; work[j] = tmp; i++; j--; }
      }
      if (j < k - 1) lo = i;
      else if (i > k - 1) hi = j;
      else break;
    }
    // Extract first k and sort them
    var result = work.slice(0, k);
    result.sort(cmp);
    return result;
  });

let uniq = (function(arr) { return Array.from(new Set(arr)) });

let uniqBy = (function(arr, f) {
    var seen = new Set(), out = [];
    for (var i = 0, len = arr.length; i < len; i++) {
      var x = arr[i], key = f(x);
      if (!seen.has(key)) { seen.add(key); out.push(x); }
    }
    return out;
  });

function intersperse(arr, sep) {
  let len = arr.length;
  if (len <= 1) {
    return arr.slice(0);
  }
  let outLen = (len << 1) - 1 | 0;
  let out = new Array(outLen);
  for (let i = 0; i < len; ++i) {
    out[(i << 1)] = arr[i];
    if (i < (len - 1 | 0)) {
      out[(i << 1) + 1 | 0] = sep;
    }
  }
  return out;
}

let zip = (function(a, b) {
    var len = a.length < b.length ? a.length : b.length;
    var out = new Array(len), i = 0;
    while (i < len) { out[i] = [a[i], b[i]]; i++; }
    return out;
  });

function zipWith(a, b, f) {
  let lenA = a.length;
  let lenB = b.length;
  let len = lenA < lenB ? lenA : lenB;
  let out = new Array(len);
  for (let i = 0; i < len; ++i) {
    out[i] = f(a[i], b[i]);
  }
  return out;
}

let groupBy = (function(arr, f) {
    var out = {};
    for (var i = 0, len = arr.length; i < len; i++) {
      var x = arr[i], key = f(x);
      var existing = out[key];
      if (existing !== undefined) existing.push(x);
      else out[key] = [x];
    }
    return out;
  });

function partition(arr, pred) {
  let len = arr.length;
  let pass = new Array(len);
  let fail = new Array(len);
  let pi = 0;
  let fi = 0;
  for (let i = 0; i < len; ++i) {
    let x = arr[i];
    if (pred(x)) {
      pass[pi] = x;
      pi = pi + 1 | 0;
    } else {
      fail[fi] = x;
      fi = fi + 1 | 0;
    }
  }
  truncate(pass, pi);
  truncate(fail, fi);
  return [
    pass,
    fail
  ];
}

function adjust(arr, index, f) {
  let len = arr.length;
  if (index < 0 || index >= len) {
    return arr.slice(0);
  }
  let out = arr.slice(0);
  out[index] = f(arr[index]);
  return out;
}

let update = (function(arr, index, value) {
    var len = arr.length;
    if (index < 0 || index >= len) return arr.slice();
    var out = arr.slice();
    out[index] = value;
    return out;
  });

function insert(arr, index, value) {
  let len = arr.length;
  let idx = index < 0 ? 0 : (
      index > len ? len : index
    );
  let out = new Array(len + 1 | 0);
  for (let i = 0; i < idx; ++i) {
    out[i] = arr[i];
  }
  out[idx] = value;
  for (let i$1 = idx; i$1 < len; ++i$1) {
    out[i$1 + 1 | 0] = arr[i$1];
  }
  return out;
}

function remove(arr, index, count) {
  let len = arr.length;
  if (index < 0 || index >= len || count <= 0) {
    return arr.slice(0);
  }
  let actual = (index + count | 0) > len ? len - index | 0 : count;
  let newLen = len - actual | 0;
  let out = new Array(newLen);
  for (let i = 0; i < index; ++i) {
    out[i] = arr[i];
  }
  for (let i$1 = index + actual | 0; i$1 < len; ++i$1) {
    out[i$1 - actual | 0] = arr[i$1];
  }
  return out;
}

let aperture = slidingWindow;

function range(start, end_) {
  if (end_ <= start) {
    return [];
  }
  let len = end_ - start | 0;
  let out = new Array(len);
  for (let i = 0; i < len; ++i) {
    out[i] = start + i | 0;
  }
  return out;
}

function repeat(value, n) {
  if (n <= 0) {
    return [];
  }
  let out = new Array(n);
  for (let i = 0; i < n; ++i) {
    out[i] = value;
  }
  return out;
}

function times(f, n) {
  if (n <= 0) {
    return [];
  }
  let out = new Array(n);
  for (let i = 0; i < n; ++i) {
    out[i] = f(i);
  }
  return out;
}

function unfold(f, seed) {
  let result = [];
  let s = seed;
  let continue_ = true;
  while (continue_) {
    let match = f(s);
    if (match !== undefined) {
      result.push(match[0]);
      s = match[1];
    } else {
      continue_ = false;
    }
  };
  return result;
}

function scan(arr, f, init) {
  let len = arr.length;
  let out = new Array(len + 1 | 0);
  let acc = init;
  out[0] = init;
  for (let i = 0; i < len; ++i) {
    acc = f(acc, arr[i]);
    out[i + 1 | 0] = acc;
  }
  return out;
}

function xprod(a, b) {
  let lenA = a.length;
  let lenB = b.length;
  let total = lenA * lenB | 0;
  if (total === 0) {
    return [];
  }
  let out = new Array(total);
  for (let i = 0; i < lenA; ++i) {
    for (let j = 0; j < lenB; ++j) {
      out[(i * lenB | 0) + j | 0] = [
        a[i],
        b[j]
      ];
    }
  }
  return out;
}

function transpose(arr) {
  let rows = arr.length;
  if (rows === 0) {
    return [];
  }
  let cols = arr[0].length;
  for (let i = 1; i < rows; ++i) {
    let rowLen = arr[i].length;
    if (rowLen < cols) {
      cols = rowLen;
    }
  }
  if (cols === 0) {
    return [];
  }
  let out = new Array(cols);
  for (let c = 0; c < cols; ++c) {
    let col = new Array(rows);
    for (let r = 0; r < rows; ++r) {
      col[r] = arr[r][c];
    }
    out[c] = col;
  }
  return out;
}

let intersection = (function(a, b) {
    var setB = new Set(b);
    return a.filter(function(x) { return setB.delete(x); });
  });

let union = (function(a, b) {
    var la = a.length, lb = b.length, out, i, j, x, found;
    if (la + lb < 256) {
      out = a.slice();
      for (i = 0; i < lb; i++) {
        x = b[i]; found = false;
        for (j = 0; j < out.length; j++) { if (out[j] === x) { found = true; break; } }
        if (!found) out.push(x);
      }
      return out;
    }
    var seen = new Set(); out = [];
    for (i = 0; i < la; i++) { x = a[i]; if (!seen.has(x)) { seen.add(x); out.push(x); } }
    for (i = 0; i < lb; i++) { x = b[i]; if (!seen.has(x)) { seen.add(x); out.push(x); } }
    return out;
  });

function unionBy(a, b, f) {
  let seen = new Set();
  let result = [];
  for (let i = 0, i_finish = a.length; i < i_finish; ++i) {
    let x = a[i];
    let k = f(x);
    if (!seen.has(k)) {
      seen.add(k);
      result.push(x);
    }
  }
  for (let i$1 = 0, i_finish$1 = b.length; i$1 < i_finish$1; ++i$1) {
    let x$1 = b[i$1];
    let k$1 = f(x$1);
    if (!seen.has(k$1)) {
      seen.add(k$1);
      result.push(x$1);
    }
  }
  return result;
}

function intersectionBy(a, b, f) {
  let setB = new Set();
  for (let i = 0, i_finish = b.length; i < i_finish; ++i) {
    setB.add(f(b[i]));
  }
  let seen = new Set();
  let result = [];
  for (let i$1 = 0, i_finish$1 = a.length; i$1 < i_finish$1; ++i$1) {
    let x = a[i$1];
    let k = f(x);
    if (setB.has(k) && !seen.has(k)) {
      seen.add(k);
      result.push(x);
    }
  }
  return result;
}

let difference = (function(a, b) {
    var lenA = a.length, lenB = b.length, out = [];
    if (lenB < 64) {
      outer: for (var i = 0; i < lenA; i++) {
        var x = a[i];
        for (var j = 0; j < lenB; j++) { if (b[j] === x) continue outer; }
        out.push(x);
      }
    } else {
      var setB = new Set(b);
      for (var i = 0; i < lenA; i++) {
        var x = a[i];
        if (!setB.has(x)) { setB.add(x); out.push(x); }
      }
    }
    return out;
  });

function differenceBy(a, b, f) {
  let setB = new Set();
  for (let i = 0, i_finish = b.length; i < i_finish; ++i) {
    setB.add(f(b[i]));
  }
  let seen = new Set();
  let result = [];
  for (let i$1 = 0, i_finish$1 = a.length; i$1 < i_finish$1; ++i$1) {
    let x = a[i$1];
    let k = f(x);
    if (!setB.has(k) && !seen.has(k)) {
      seen.add(k);
      result.push(x);
    }
  }
  return result;
}

let symmetricDifference = (function(a, b) {
    var la = a.length, lb = b.length, out, i, j, x;
    if (la + lb < 256) {
      var d1 = [], d2 = [];
      outer1: for (i = 0; i < la; i++) { x = a[i]; j = lb; while (j--) { if (b[j] === x) continue outer1; } d1.push(x); }
      outer2: for (i = 0; i < lb; i++) { x = b[i]; j = la; while (j--) { if (a[j] === x) continue outer2; } d2.push(x); }
      var all = d1.length + d2.length; out = new Array(all);
      for (i = 0; i < d1.length; i++) out[i] = d1[i];
      for (i = 0; i < d2.length; i++) out[d1.length + i] = d2[i];
      if (all < 2) return out;
      var r = [out[0]];
      outer3: for (i = 1; i < all; i++) { x = out[i]; j = r.length; while (j--) { if (r[j] === x) continue outer3; } r.push(x); }
      return r;
    }
    var setA = new Set(a), setB = new Set(b); out = [];
    for (i = 0; i < la; i++) { x = a[i]; if (!setB.has(x) && setA.has(x)) { setA.delete(x); out.push(x); } }
    for (i = 0; i < lb; i++) { x = b[i]; if (!setA.has(x) && setB.has(x)) { setB.delete(x); out.push(x); } }
    return out;
  });

function symmetricDifferenceBy(a, b, f) {
  let setA = new Set();
  let setB = new Set();
  for (let i = 0, i_finish = a.length; i < i_finish; ++i) {
    setA.add(f(a[i]));
  }
  for (let i$1 = 0, i_finish$1 = b.length; i$1 < i_finish$1; ++i$1) {
    setB.add(f(b[i$1]));
  }
  let seen = new Set();
  let result = [];
  for (let i$2 = 0, i_finish$2 = a.length; i$2 < i_finish$2; ++i$2) {
    let x = a[i$2];
    let k = f(x);
    if (!setB.has(k) && !seen.has(k)) {
      seen.add(k);
      result.push(x);
    }
  }
  for (let i$3 = 0, i_finish$3 = b.length; i$3 < i_finish$3; ++i$3) {
    let x$1 = b[i$3];
    let k$1 = f(x$1);
    if (!setA.has(k$1) && !seen.has(k$1)) {
      seen.add(k$1);
      result.push(x$1);
    }
  }
  return result;
}

function append(arr, value) {
  let len = arr.length;
  let out = new Array(len + 1 | 0);
  for (let i = 0; i < len; ++i) {
    out[i] = arr[i];
  }
  out[len] = value;
  return out;
}

function prepend(arr, value) {
  let len = arr.length;
  let out = new Array(len + 1 | 0);
  out[0] = value;
  for (let i = 0; i < len; ++i) {
    out[i + 1 | 0] = arr[i];
  }
  return out;
}

let concat = (function(a, b) { return a.concat(b) });

let nth = (function(arr, n) {
    var i = n < 0 ? arr.length + n : n;
    return i < 0 || i >= arr.length ? undefined : arr[i];
  });

let indexOf = (function(arr, val) {
    var i = arr.indexOf(val);
    return i === -1 ? undefined : i;
  });

let lastIndexOf = (function(arr, val) {
    var i = arr.lastIndexOf(val);
    return i === -1 ? undefined : i;
  });

let findLast = (function(arr, pred) {
    for (var i = arr.length - 1; i >= 0; i--) { if (pred(arr[i])) return arr[i]; }
    return undefined;
  });

let findLastIndex = (function(arr, pred) {
    for (var i = arr.length - 1; i >= 0; i--) { if (pred(arr[i])) return i; }
    return undefined;
  });

let reject = (function(arr, pred) {
    var out = [];
    for (var i = 0; i < arr.length; i++) { if (!pred(arr[i])) out.push(arr[i]); }
    return out;
  });

let none = (function(arr, pred) {
    for (var i = 0; i < arr.length; i++) { if (pred(arr[i])) return false; }
    return true;
  });

function count(arr, pred) {
  let len = arr.length;
  let c = 0;
  for (let i = 0; i < len; ++i) {
    if (pred(arr[i])) {
      c = c + 1 | 0;
    }
  }
  return c;
}

function slice(arr, start, end_) {
  let len = arr.length;
  let s = start < 0 ? (
      (len + start | 0) > 0 ? len + start | 0 : 0
    ) : (
      start < len ? start : len
    );
  let e = end_ < 0 ? (
      (len + end_ | 0) > 0 ? len + end_ | 0 : 0
    ) : (
      end_ < len ? end_ : len
    );
  if (s >= e) {
    return [];
  }
  let count = e - s | 0;
  let out = new Array(count);
  for (let i = 0; i < count; ++i) {
    out[i] = arr[s + i | 0];
  }
  return out;
}

let join = (function(arr, sep) { return arr.join(sep); });

function pair(a, b) {
  return [
    a,
    b
  ];
}

let pluckRaw = (function(arr, key) {
    const len = arr.length;
    const out = new Array(len);
    for (let i = 0; i < len; i++) {
      out[i] = arr[i][key];
    }
    return out;
  });

function pluck(arr, key) {
  return pluckRaw(arr, key);
}

function without(arr, values) {
  let exclude = new Set(values);
  let result = [];
  for (let i = 0, i_finish = arr.length; i < i_finish; ++i) {
    let x = arr[i];
    if (!exclude.has(x)) {
      result.push(x);
    }
  }
  return result;
}

function withoutBy(arr, values, f) {
  let exclude = new Set();
  for (let i = 0, i_finish = values.length; i < i_finish; ++i) {
    exclude.add(f(values[i]));
  }
  let result = [];
  for (let i$1 = 0, i_finish$1 = arr.length; i$1 < i_finish$1; ++i$1) {
    let x = arr[i$1];
    if (!exclude.has(f(x))) {
      result.push(x);
    }
  }
  return result;
}

function dropLast(arr, n) {
  let len = arr.length;
  if (n <= 0) {
    return arr.slice(0);
  }
  if (n >= len) {
    return [];
  }
  let count = len - n | 0;
  let out = new Array(count);
  for (let i = 0; i < count; ++i) {
    out[i] = arr[i];
  }
  return out;
}

function dropLastWhile(arr, pred) {
  let len = arr.length;
  let i = len - 1 | 0;
  while (i >= 0 && pred(arr[i])) {
    i = i - 1 | 0;
  };
  let count = i + 1 | 0;
  if (count === len) {
    return arr.slice(0);
  }
  if (count <= 0) {
    return [];
  }
  let out = new Array(count);
  for (let j = 0; j < count; ++j) {
    out[j] = arr[j];
  }
  return out;
}

function dropRepeats(arr) {
  let len = arr.length;
  if (len === 0) {
    return [];
  }
  let result = [arr[0]];
  for (let i = 1; i < len; ++i) {
    let x = arr[i];
    if (Primitive_object.notequal(x, arr[i - 1 | 0])) {
      result.push(x);
    }
  }
  return result;
}

function dropRepeatsBy(arr, f) {
  let len = arr.length;
  if (len === 0) {
    return [];
  }
  let first = arr[0];
  let result = [first];
  let lastKey = f(first);
  for (let i = 1; i < len; ++i) {
    let x = arr[i];
    let key = f(x);
    if (Primitive_object.notequal(key, lastKey)) {
      result.push(x);
      lastKey = key;
    }
  }
  return result;
}

function dropRepeatsWith(arr, eq) {
  let len = arr.length;
  if (len === 0) {
    return [];
  }
  let result = [arr[0]];
  for (let i = 1; i < len; ++i) {
    let x = arr[i];
    if (!eq(arr[i - 1 | 0], x)) {
      result.push(x);
    }
  }
  return result;
}

function takeLast(arr, n) {
  let len = arr.length;
  if (n <= 0) {
    return [];
  }
  if (n >= len) {
    return arr.slice(0);
  }
  let start = len - n | 0;
  let out = new Array(n);
  for (let i = 0; i < n; ++i) {
    out[i] = arr[start + i | 0];
  }
  return out;
}

function takeLastWhile(arr, pred) {
  let len = arr.length;
  let i = len - 1 | 0;
  while (i >= 0 && pred(arr[i])) {
    i = i - 1 | 0;
  };
  let start = i + 1 | 0;
  let count = len - start | 0;
  if (count <= 0) {
    return [];
  }
  if (count === len) {
    return arr.slice(0);
  }
  let out = new Array(count);
  for (let j = 0; j < count; ++j) {
    out[j] = arr[start + j | 0];
  }
  return out;
}

let splitAt = (function(arr, index) {
    var i = index < 0 ? 0 : index > arr.length ? arr.length : index;
    return [arr.slice(0, i), arr.slice(i)];
  });

function splitWhen(arr, pred) {
  let len = arr.length;
  let i = 0;
  let found = false;
  while (i < len && !found) {
    if (pred(arr[i])) {
      found = true;
    } else {
      i = i + 1 | 0;
    }
  };
  return splitAt(arr, i);
}

function splitWhenever(arr, pred) {
  let len = arr.length;
  if (len === 0) {
    return [];
  }
  let result = [];
  let current = [];
  for (let i = 0; i < len; ++i) {
    let x = arr[i];
    if (pred(x)) {
      result.push(current.slice());
      current.splice(0, current.length);
    } else {
      current.push(x);
    }
  }
  result.push(current.slice());
  return result;
}

function swap(arr, i, j) {
  let len = arr.length;
  if (i < 0 || i >= len || j < 0 || j >= len) {
    return arr.slice(0);
  }
  let out = arr.slice(0);
  out[i] = arr[j];
  out[j] = arr[i];
  return out;
}

function insertAll(arr, index, values) {
  let len = arr.length;
  let vLen = values.length;
  let idx = index < 0 ? 0 : (
      index > len ? len : index
    );
  let out = new Array(len + vLen | 0);
  for (let i = 0; i < idx; ++i) {
    out[i] = arr[i];
  }
  for (let i$1 = 0; i$1 < vLen; ++i$1) {
    out[idx + i$1 | 0] = values[i$1];
  }
  for (let i$2 = idx; i$2 < len; ++i$2) {
    out[i$2 + vLen | 0] = arr[i$2];
  }
  return out;
}

function arrayStartsWith(arr, prefix) {
  let lenA = arr.length;
  let lenP = prefix.length;
  if (lenP > lenA) {
    return false;
  }
  let i = 0;
  let ok = true;
  while (i < lenP && ok) {
    if (Primitive_object.notequal(arr[i], prefix[i])) {
      ok = false;
    }
    i = i + 1 | 0;
  };
  return ok;
}

function arrayEndsWith(arr, suffix) {
  let lenA = arr.length;
  let lenS = suffix.length;
  if (lenS > lenA) {
    return false;
  }
  let offset = lenA - lenS | 0;
  let i = 0;
  let ok = true;
  while (i < lenS && ok) {
    if (Primitive_object.notequal(arr[offset + i | 0], suffix[i])) {
      ok = false;
    }
    i = i + 1 | 0;
  };
  return ok;
}

function uniqWith(arr, eq) {
  let result = [];
  for (let i = 0, i_finish = arr.length; i < i_finish; ++i) {
    let x = arr[i];
    let dup = false;
    let j = 0;
    while (j < result.length && !dup) {
      if (eq(result[j], x)) {
        dup = true;
      }
      j = j + 1 | 0;
    };
    if (!dup) {
      result.push(x);
    }
  }
  return result;
}

function unionWith(a, b, eq) {
  let result = [];
  let addIfNew = x => {
    let dup = false;
    let j = 0;
    while (j < result.length && !dup) {
      if (eq(result[j], x)) {
        dup = true;
      }
      j = j + 1 | 0;
    };
    if (!dup) {
      result.push(x);
      return;
    }
  };
  for (let i = 0, i_finish = a.length; i < i_finish; ++i) {
    addIfNew(a[i]);
  }
  for (let i$1 = 0, i_finish$1 = b.length; i$1 < i_finish$1; ++i$1) {
    addIfNew(b[i$1]);
  }
  return result;
}

function differenceWith(a, b, eq) {
  let result = [];
  for (let i = 0, i_finish = a.length; i < i_finish; ++i) {
    let x = a[i];
    let found = false;
    let j = 0;
    while (j < b.length && !found) {
      if (eq(x, b[j])) {
        found = true;
      }
      j = j + 1 | 0;
    };
    if (!found) {
      result.push(x);
    }
  }
  return result;
}

function symmetricDifferenceWith(a, b, eq) {
  let result = [];
  for (let i = 0, i_finish = a.length; i < i_finish; ++i) {
    let x = a[i];
    let found = false;
    let j = 0;
    while (j < b.length && !found) {
      if (eq(x, b[j])) {
        found = true;
      }
      j = j + 1 | 0;
    };
    if (!found) {
      result.push(x);
    }
  }
  for (let i$1 = 0, i_finish$1 = b.length; i$1 < i_finish$1; ++i$1) {
    let x$1 = b[i$1];
    let found$1 = false;
    let j$1 = 0;
    while (j$1 < a.length && !found$1) {
      if (eq(x$1, a[j$1])) {
        found$1 = true;
      }
      j$1 = j$1 + 1 | 0;
    };
    if (!found$1) {
      result.push(x$1);
    }
  }
  return result;
}

function indexBy(arr, f) {
  let len = arr.length;
  let dict = {};
  for (let i = 0; i < len; ++i) {
    let x = arr[i];
    dict[f(x)] = x;
  }
  return dict;
}

function collectBy(arr, f) {
  let len = arr.length;
  let dict = {};
  let keys = [];
  for (let i = 0; i < len; ++i) {
    let x = arr[i];
    let key = f(x);
    let group = dict[key];
    if (group !== undefined) {
      group.push(x);
    } else {
      dict[key] = [x];
      keys.push(key);
    }
  }
  let kLen = keys.length;
  let out = new Array(kLen);
  for (let i$1 = 0; i$1 < kLen; ++i$1) {
    let group$1 = dict[keys[i$1]];
    if (group$1 !== undefined) {
      out[i$1] = group$1;
    } else {
      out[i$1] = [];
    }
  }
  return out;
}

function groupWith(arr, eq) {
  let len = arr.length;
  if (len === 0) {
    return [];
  }
  let result = [];
  let current = [arr[0]];
  for (let i = 1; i < len; ++i) {
    let x = arr[i];
    if (eq(arr[i - 1 | 0], x)) {
      current.push(x);
    } else {
      result.push(current.slice());
      current.splice(0, current.length, x);
    }
  }
  result.push(current.slice());
  return result;
}

function mapAccum(arr, f, init) {
  let len = arr.length;
  let out = new Array(len);
  let acc = init;
  for (let i = 0; i < len; ++i) {
    let match = f(acc, arr[i]);
    acc = match[0];
    out[i] = match[1];
  }
  return [
    acc,
    out
  ];
}

function mapAccumRight(arr, f, init) {
  let len = arr.length;
  let out = new Array(len);
  let acc = init;
  for (let i = 0; i < len; ++i) {
    let j = (len - 1 | 0) - i | 0;
    let match = f(acc, arr[j]);
    acc = match[0];
    out[j] = match[1];
  }
  return [
    acc,
    out
  ];
}

function reduceBy(arr, keyFn, reducer, init) {
  let len = arr.length;
  let dict = {};
  for (let i = 0; i < len; ++i) {
    let x = arr[i];
    let key = keyFn(x);
    let v = dict[key];
    let acc = v !== undefined ? Primitive_option.valFromOption(v) : init;
    dict[key] = reducer(acc, x);
  }
  return dict;
}

function reduceWhile(arr, pred, f, init) {
  let len = arr.length;
  let acc = init;
  let i = 0;
  let continue_ = true;
  while (i < len && continue_) {
    let x = arr[i];
    if (pred(acc, x)) {
      acc = f(acc, x);
      i = i + 1 | 0;
    } else {
      continue_ = false;
    }
  };
  return acc;
}

let mergeAllRaw = (function(arr) {
    return Object.assign({}, ...arr);
  });

function mergeAll(arr) {
  return mergeAllRaw(arr);
}

function zipObj(keys, values) {
  let lenK = keys.length;
  let lenV = values.length;
  let len = lenK < lenV ? lenK : lenV;
  let dict = {};
  for (let i = 0; i < len; ++i) {
    dict[keys[i]] = values[i];
  }
  return dict;
}

function unnest(arr) {
  return flatten(arr);
}

function mapToObj(arr, f) {
  let len = arr.length;
  let dict = {};
  for (let i = 0; i < len; ++i) {
    let match = f(arr[i]);
    dict[match[0]] = match[1];
  }
  return dict;
}

function only(arr) {
  if (arr.length === 1) {
    return Primitive_option.some(arr[0]);
  }
}

function hasAtLeast(arr, n) {
  return arr.length >= n;
}

let sampleRaw = (function(arr, n) {
    var len = arr.length;
    var size = n > len ? len : n;
    var copy = arr.slice();
    for (var i = len - 1; i > len - 1 - size && i > 0; i--) {
      var j = Math.floor(Math.random() * (i + 1));
      var tmp = copy[i]; copy[i] = copy[j]; copy[j] = tmp;
    }
    return copy.slice(len - size);
  });

function sample(arr, n) {
  return sampleRaw(arr, n);
}

let shuffleRaw = (function(arr) {
    var copy = arr.slice();
    for (var i = copy.length - 1; i > 0; i--) {
      var j = Math.floor(Math.random() * (i + 1));
      var tmp = copy[i]; copy[i] = copy[j]; copy[j] = tmp;
    }
    return copy;
  });

function shuffle(arr) {
  return shuffleRaw(arr);
}

function splice(arr, start, deleteCount, items) {
  let len = arr.length;
  let s = start < 0 ? (
      (len + start | 0) > 0 ? len + start | 0 : 0
    ) : (
      start < len ? start : len
    );
  let dc = deleteCount < 0 ? 0 : (
      (s + deleteCount | 0) > len ? len - s | 0 : deleteCount
    );
  let itemsLen = items.length;
  let newLen = (len - dc | 0) + itemsLen | 0;
  let out = new Array(newLen);
  for (let i = 0; i < s; ++i) {
    out[i] = arr[i];
  }
  for (let i$1 = 0; i$1 < itemsLen; ++i$1) {
    out[s + i$1 | 0] = items[i$1];
  }
  for (let i$2 = s + dc | 0; i$2 < len; ++i$2) {
    out[(s + itemsLen | 0) + ((i$2 - s | 0) - dc | 0) | 0] = arr[i$2];
  }
  return out;
}

function sortedIndex(arr, value) {
  let lo = 0;
  let hi = arr.length;
  while (lo < hi) {
    let mid = (lo + hi | 0) / 2 | 0;
    if (arr[mid] < value) {
      lo = mid + 1 | 0;
    } else {
      hi = mid;
    }
  };
  return lo;
}

function sortedIndexBy(arr, value, f) {
  let target = f(value);
  let lo = 0;
  let hi = arr.length;
  while (lo < hi) {
    let mid = (lo + hi | 0) / 2 | 0;
    if (f(arr[mid]) < target) {
      lo = mid + 1 | 0;
    } else {
      hi = mid;
    }
  };
  return lo;
}

function sortedIndexWith(arr, pred) {
  let lo = 0;
  let hi = arr.length;
  while (lo < hi) {
    let mid = (lo + hi | 0) / 2 | 0;
    if (pred(arr[mid])) {
      hi = mid;
    } else {
      lo = mid + 1 | 0;
    }
  };
  return lo;
}

function sortedLastIndex(arr, value) {
  let lo = 0;
  let hi = arr.length;
  while (lo < hi) {
    let mid = (lo + hi | 0) / 2 | 0;
    if (arr[mid] <= value) {
      lo = mid + 1 | 0;
    } else {
      hi = mid;
    }
  };
  return lo;
}

function sortedLastIndexBy(arr, value, f) {
  let target = f(value);
  let lo = 0;
  let hi = arr.length;
  while (lo < hi) {
    let mid = (lo + hi | 0) / 2 | 0;
    if (f(arr[mid]) <= target) {
      lo = mid + 1 | 0;
    } else {
      hi = mid;
    }
  };
  return lo;
}

function meanBy(arr, f) {
  let len = arr.length;
  if (len === 0) {
    return 0.0;
  }
  let acc = 0.0;
  for (let i = 0; i < len; ++i) {
    acc = acc + f(arr[i]);
  }
  return acc / len;
}

function sumBy(arr, f) {
  let len = arr.length;
  let acc = 0.0;
  for (let i = 0; i < len; ++i) {
    acc = acc + f(arr[i]);
  }
  return acc;
}

let groupByPropRaw = (function(arr, prop) {
    var dict = {};
    for (var i = 0; i < arr.length; i++) {
      var key = String(arr[i][prop]);
      if (!dict[key]) dict[key] = [];
      dict[key].push(arr[i]);
    }
    return dict;
  });

function groupByProp(arr, prop) {
  return groupByPropRaw(arr, prop);
}

export {
  head,
  truncate,
  last,
  tail,
  init,
  isEmpty,
  length,
  take,
  drop,
  takeWhile,
  dropWhile,
  chunk,
  slidingWindow,
  map,
  mapWithIndex,
  filter,
  filterWithIndex,
  forEach,
  forEachWithIndex,
  reduce,
  reduceRight,
  flatMap,
  flatten,
  find,
  findIndex,
  every,
  some,
  includes,
  reverse,
  sort,
  sortBy,
  takeSortedBy,
  uniq,
  uniqBy,
  intersperse,
  zip,
  zipWith,
  groupBy,
  partition,
  adjust,
  update,
  insert,
  remove,
  aperture,
  range,
  repeat,
  times,
  unfold,
  scan,
  xprod,
  transpose,
  intersection,
  union,
  unionBy,
  intersectionBy,
  difference,
  differenceBy,
  symmetricDifference,
  symmetricDifferenceBy,
  append,
  prepend,
  concat,
  nth,
  indexOf,
  lastIndexOf,
  findLast,
  findLastIndex,
  reject,
  none,
  count,
  slice,
  join,
  pair,
  pluckRaw,
  pluck,
  without,
  withoutBy,
  dropLast,
  dropLastWhile,
  dropRepeats,
  dropRepeatsBy,
  dropRepeatsWith,
  takeLast,
  takeLastWhile,
  splitAt,
  splitWhen,
  splitWhenever,
  swap,
  insertAll,
  arrayStartsWith,
  arrayEndsWith,
  uniqWith,
  unionWith,
  differenceWith,
  symmetricDifferenceWith,
  indexBy,
  collectBy,
  groupWith,
  mapAccum,
  mapAccumRight,
  reduceBy,
  reduceWhile,
  mergeAllRaw,
  mergeAll,
  zipObj,
  unnest,
  mapToObj,
  only,
  hasAtLeast,
  sampleRaw,
  sample,
  shuffleRaw,
  shuffle,
  splice,
  sortedIndex,
  sortedIndexBy,
  sortedIndexWith,
  sortedLastIndex,
  sortedLastIndexBy,
  meanBy,
  sumBy,
  groupByPropRaw,
  groupByProp,
}
/* No side effect */
