// @ts-nocheck
// Auto-generated by codegen/dual-inline.ts — do not edit
// Source of truth: codegen/defs/
import * as RS from './Array.gen'

// Internal helpers (auto-extracted from ReScript compiled output)
function truncate(a, n) {
  a.length = n
}

function pluckRaw(arr, key) {
  const len = arr.length;
    const out = new Array(len);
    for (let i = 0; i < len; i++) {
      out[i] = arr[i][key];
    }
    return out;
}

function sampleRaw(arr, n) {
  var len = arr.length;
    var size = n > len ? len : n;
    var copy = arr.slice();
    for (var i = len - 1; i > len - 1 - size && i > 0; i--) {
      var j = Math.floor(Math.random() * (i + 1));
      var tmp = copy[i]; copy[i] = copy[j]; copy[j] = tmp;
    }
    return copy.slice(len - size);
}

function groupByPropRaw(arr, prop) {
  var dict = {};
    for (var i = 0; i < arr.length; i++) {
      var key = String(arr[i][prop]);
      if (!dict[key]) dict[key] = [];
      dict[key].push(arr[i]);
    }
    return dict;
}

type Dict<A> = Record<string, A>
import { sum as nSum, min as nMin, max as nMax } from './number'

// Arity 1 — tagged for fusion engine (accessor ops get inlined in pipe)
export const head: <A>(arr: A[]) => A | undefined = /* @__PURE__ */ (() => {
  const _f: any = function head(a: any) { return a[0] }
  _f._op = 30
  return _f
})()

export const last: <A>(arr: A[]) => A | undefined = /* @__PURE__ */ (() => {
  const _f: any = function last(a: any) { return a[a.length - 1] }
  _f._op = 31
  return _f
})()

export const tail: <A>(arr: A[]) => A[] = /* @__PURE__ */ (() => {
  const _f: any = function tail(arr: any) { if (arr.length <= 1) {
    return [];
  } else {
    return arr.slice(1);
  } }
  _f._op = 34
  return _f
})()

export const init: <A>(arr: A[]) => A[] = /* @__PURE__ */ (() => {
  const _f: any = function init(arr: any) { let len = arr.length;
  if (len <= 1) {
    return [];
  } else {
    return arr.slice(0, len - 1 | 0);
  } }
  _f._op = 35
  return _f
})()

export const isEmpty: <A>(arr: A[]) => boolean = /* @__PURE__ */ (() => {
  const _f: any = function isEmpty(arr: any) { return arr.length === 0; }
  _f._op = 33
  return _f
})()

export const length: <A>(arr: A[]) => number = /* @__PURE__ */ (() => {
  const _f: any = function length(arr: any) { return arr.length; }
  _f._op = 32
  return _f
})()

export const reverse: <A>(arr: A[]) => A[] = /* @__PURE__ */ (() => {
  const _f: any = function reverse(arr: any) { var len = arr.length, out = new Array(len);
    for (var i = 0; i < len; i++) out[i] = arr[len - 1 - i];
    return out; }
  _f._op = 36
  return _f
})()

export const flatten: <A>(arr: A[][]) => A[] = /* @__PURE__ */ (() => {
  const _f: any = function flatten(arr: any) { var out = [];
    for (var i = 0; i < arr.length; i++) {
      var inner = arr[i];
      for (var j = 0; j < inner.length; j++) out.push(inner[j]);
    }
    return out; }
  _f._op = 40
  return _f
})()

export const first: <A>(arr: A[]) => A | undefined = /* @__PURE__ */ (() => {
  const _f: any = function first(a: any) { return a[0] }
  _f._op = 30
  return _f
})()


// Standalone generators (no dual)
export const range: (start: number, end: number) => number[] = RS.range
export const sort: (arr: number[]) => number[] = /* @__PURE__ */ (() => {
  const _f: any = RS.sort
  _f._op = 21
  return _f
})()

export const transpose: <A>(arr: A[][]) => A[][] = RS.transpose

export const repeat: {
  <A>(value: A, n: number): A[]
  <A>(n: number): (value: A) => A[]
} = function repeat() {
  if (arguments.length >= 2) {
    const value = arguments[0], n = arguments[1]
    return RS.repeat(value, n)
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const value = data, n = _a0
    return RS.repeat(value, n)
  }
  return _dl
} as any


export const times: {
  <A>(f: (i: number) => A, n: number): A[]
  (n: number): <A>(f: (i: number) => A) => A[]
} = function times() {
  if (arguments.length >= 2) {
    const f = arguments[0], n = arguments[1]
    return RS.times(f, n)
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const f = data, n = _a0
    return RS.times(f, n)
  }
  return _dl
} as any


export const unfold: {
  <A, B>(f: (seed: B) => [A, B] | undefined, seed: B): A[]
  <A, B>(seed: B): (f: (seed: B) => [A, B] | undefined) => A[]
} = function unfold() {
  if (arguments.length >= 2) {
    const f = arguments[0], seed = arguments[1]
    return RS.unfold(f, seed)
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const f = data, seed = _a0
    return RS.unfold(f, seed)
  }
  return _dl
} as any


export const xprod: {
  <A, B>(a: A[], b: B[]): [A, B][]
  <B>(b: B[]): <A>(a: A[]) => [A, B][]
} = function xprod() {
  if (arguments.length >= 2) {
    const a = arguments[0], b = arguments[1]
    let lenA = a.length;
  let lenB = b.length;
  let total = lenA * lenB | 0;
  if (total === 0) {
    return [];
  }
  let out = new Array(total);
  for (let i = 0; i < lenA; ++i) {
    for (let j = 0; j < lenB; ++j) {
      out[(i * lenB | 0) + j | 0] = [
        a[i],
        b[j]
      ];
    }
  }
  return out;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const a = data, b = _a0
    let lenA = a.length;
  let lenB = b.length;
  let total = lenA * lenB | 0;
  if (total === 0) {
    return [];
  }
  let out = new Array(total);
  for (let i = 0; i < lenA; ++i) {
    for (let j = 0; j < lenB; ++j) {
      out[(i * lenB | 0) + j | 0] = [
        a[i],
        b[j]
      ];
    }
  }
  return out;
  }
  return _dl
} as any


// Arity 2
export const map: {
  <A, B>(arr: A[], f: (a: A) => B): B[]
  <A, B>(f: (a: A) => B): (arr: A[]) => B[]
} = function map() {
  if (arguments.length >= 2) {
    const arr = arguments[0], f = arguments[1]
    const len = arr.length, out = new Array(len)
  for (let i = 0; i < len; i++) out[i] = f(arr[i])
  return out
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, f = _a0
    const len = arr.length, out = new Array(len)
  for (let i = 0; i < len; i++) out[i] = f(arr[i])
  return out
  }
    _dl._op = 1
    _dl._fn = _a0
  return _dl
} as any


export const mapWithIndex: {
  <A, B>(arr: A[], f: (a: A, i: number) => B): B[]
  <A, B>(f: (a: A, i: number) => B): (arr: A[]) => B[]
} = function mapWithIndex() {
  if (arguments.length >= 2) {
    const arr = arguments[0], f = arguments[1]
    const len = arr.length, out = new Array(len)
  for (let i = 0; i < len; i++) out[i] = f(arr[i], i)
  return out
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, f = _a0
    const len = arr.length, out = new Array(len)
  for (let i = 0; i < len; i++) out[i] = f(arr[i], i)
  return out
  }
  return _dl
} as any


export const filter: {
  <A>(arr: A[], pred: (a: A) => boolean): A[]
  <A>(pred: (a: A) => boolean): (arr: A[]) => A[]
} = function filter() {
  if (arguments.length >= 2) {
    const arr = arguments[0], pred = arguments[1]
    const out: any[] = []
  for (let i = 0, len = arr.length; i < len; i++) {
    const v = arr[i]
    if (pred(v)) out.push(v)
  }
  return out
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, pred = _a0
    const out: any[] = []
  for (let i = 0, len = arr.length; i < len; i++) {
    const v = arr[i]
    if (pred(v)) out.push(v)
  }
  return out
  }
    _dl._op = 2
    _dl._fn = _a0
  return _dl
} as any


export const filterWithIndex: {
  <A>(arr: A[], pred: (a: A, i: number) => boolean): A[]
  <A>(pred: (a: A, i: number) => boolean): (arr: A[]) => A[]
} = function filterWithIndex() {
  if (arguments.length >= 2) {
    const arr = arguments[0], pred = arguments[1]
    const out: any[] = []
  for (let i = 0, len = arr.length; i < len; i++) {
    const v = arr[i]
    if (pred(v, i)) out.push(v)
  }
  return out
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, pred = _a0
    const out: any[] = []
  for (let i = 0, len = arr.length; i < len; i++) {
    const v = arr[i]
    if (pred(v, i)) out.push(v)
  }
  return out
  }
  return _dl
} as any


export const flatMap: {
  <A, B>(arr: A[], f: (a: A) => B[]): B[]
  <A, B>(f: (a: A) => B[]): (arr: A[]) => B[]
} = function flatMap() {
  if (arguments.length >= 2) {
    const arr = arguments[0], f = arguments[1]
    const out: any[] = []
  for (let i = 0, len = arr.length; i < len; i++) {
    const r = f(arr[i])
    for (let j = 0, rlen = r.length; j < rlen; j++) out.push(r[j])
  }
  return out
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, f = _a0
    const out: any[] = []
  for (let i = 0, len = arr.length; i < len; i++) {
    const r = f(arr[i])
    for (let j = 0, rlen = r.length; j < rlen; j++) out.push(r[j])
  }
  return out
  }
    _dl._op = 7
    _dl._fn = _a0
  return _dl
} as any


export const find: {
  <A>(arr: A[], pred: (a: A) => boolean): A | undefined
  <A>(pred: (a: A) => boolean): (arr: A[]) => A | undefined
} = function find() {
  if (arguments.length >= 2) {
    const arr = arguments[0], pred = arguments[1]
    for (let i = 0, len = arr.length; i < len; i++) {
    const v = arr[i]
    if (pred(v)) return v
  }
  return undefined
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, pred = _a0
    for (let i = 0, len = arr.length; i < len; i++) {
    const v = arr[i]
    if (pred(v)) return v
  }
  return undefined
  }
    _dl._op = 12
    _dl._fn = _a0
  return _dl
} as any


export const findIndex: {
  <A>(arr: A[], pred: (a: A) => boolean): number | undefined
  <A>(pred: (a: A) => boolean): (arr: A[]) => number | undefined
} = function findIndex() {
  if (arguments.length >= 2) {
    const arr = arguments[0], pred = arguments[1]
    for (let i = 0, len = arr.length; i < len; i++) {
    if (pred(arr[i])) return i
  }
  return undefined
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, pred = _a0
    for (let i = 0, len = arr.length; i < len; i++) {
    if (pred(arr[i])) return i
  }
  return undefined
  }
    _dl._op = 13
    _dl._fn = _a0
  return _dl
} as any


export const every: {
  <A>(arr: A[], pred: (a: A) => boolean): boolean
  <A>(pred: (a: A) => boolean): (arr: A[]) => boolean
} = function every() {
  if (arguments.length >= 2) {
    const arr = arguments[0], pred = arguments[1]
    for (let i = 0, len = arr.length; i < len; i++) {
    if (!pred(arr[i])) return false
  }
  return true
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, pred = _a0
    for (let i = 0, len = arr.length; i < len; i++) {
    if (!pred(arr[i])) return false
  }
  return true
  }
    _dl._op = 10
    _dl._fn = _a0
  return _dl
} as any


export const some: {
  <A>(arr: A[], pred: (a: A) => boolean): boolean
  <A>(pred: (a: A) => boolean): (arr: A[]) => boolean
} = function some() {
  if (arguments.length >= 2) {
    const arr = arguments[0], pred = arguments[1]
    for (let i = 0, len = arr.length; i < len; i++) {
    if (pred(arr[i])) return true
  }
  return false
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, pred = _a0
    for (let i = 0, len = arr.length; i < len; i++) {
    if (pred(arr[i])) return true
  }
  return false
  }
    _dl._op = 11
    _dl._fn = _a0
  return _dl
} as any


export const includes: {
  <A>(arr: A[], value: A): boolean
  <A>(value: A): (arr: A[]) => boolean
} = function includes() {
  if (arguments.length >= 2) {
    const arr = arguments[0], value = arguments[1]
    return arr.includes(value)
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, value = _a0
    return arr.includes(value)
  }
  return _dl
} as any


export const sortBy: {
  <A>(arr: A[], cmp: (a: A, b: A) => number): A[]
  <A>(cmp: (a: A, b: A) => number): (arr: A[]) => A[]
} = function sortBy() {
  if (arguments.length >= 2) return RS.sortBy(arguments[0], arguments[1])
  const _a0 = arguments[0]
  const _dl: any = (data: any) => RS.sortBy(data, _a0)
    _dl._op = 20
    _dl._fn = _a0
  return _dl
} as any


export const takeSortedBy: {
  <A>(arr: A[], k: number, cmp: (a: A, b: A) => number): A[]
  <A>(k: number, cmp: (a: A, b: A) => number): (arr: A[]) => A[]
} = function takeSortedBy() {
  if (arguments.length >= 3) {
    const arr = arguments[0], k = arguments[1], cmp = arguments[2]
    var n = arr.length;
    if (k <= 0) return [];
    if (k >= n) return arr.slice().sort(cmp);
    // Copy to avoid mutating input
    var work = arr.slice();
    // Quickselect: partition work so that work[0..k-1] contains the k smallest
    var lo = 0, hi = n - 1;
    while (lo < hi) {
      var pivot = work[lo + ((hi - lo) >> 1)];
      var i = lo, j = hi;
      while (i <= j) {
        while (cmp(work[i], pivot) < 0) i++;
        while (cmp(work[j], pivot) > 0) j--;
        if (i <= j) { var tmp = work[i]; work[i] = work[j]; work[j] = tmp; i++; j--; }
      }
      if (j < k - 1) lo = i;
      else if (i > k - 1) hi = j;
      else break;
    }
    // Extract first k and sort them
    var result = work.slice(0, k);
    result.sort(cmp);
    return result;
  }
  const _a0 = arguments[0]; const _a1 = arguments[1]
  const _dl: any = function(data: any) {
    const arr = data, k = _a0, cmp = _a1
    var n = arr.length;
    if (k <= 0) return [];
    if (k >= n) return arr.slice().sort(cmp);
    // Copy to avoid mutating input
    var work = arr.slice();
    // Quickselect: partition work so that work[0..k-1] contains the k smallest
    var lo = 0, hi = n - 1;
    while (lo < hi) {
      var pivot = work[lo + ((hi - lo) >> 1)];
      var i = lo, j = hi;
      while (i <= j) {
        while (cmp(work[i], pivot) < 0) i++;
        while (cmp(work[j], pivot) > 0) j--;
        if (i <= j) { var tmp = work[i]; work[i] = work[j]; work[j] = tmp; i++; j--; }
      }
      if (j < k - 1) lo = i;
      else if (i > k - 1) hi = j;
      else break;
    }
    // Extract first k and sort them
    var result = work.slice(0, k);
    result.sort(cmp);
    return result;
  }
  return _dl
} as any


export const uniq: <A>(arr: A[]) => A[] = /* @__PURE__ */ (() => {
  const _f: any = function uniq(arr: any) { return Array.from(new Set(arr)) }
  _f._op = 38
  return _f
})()


export const uniqBy: {
  <A, B>(arr: A[], f: (a: A) => B): A[]
  <A, B>(f: (a: A) => B): (arr: A[]) => A[]
} = function uniqBy() {
  if (arguments.length >= 2) {
    const arr = arguments[0], f = arguments[1]
    var seen = new Set(), out = [];
    for (var i = 0, len = arr.length; i < len; i++) {
      var x = arr[i], key = f(x);
      if (!seen.has(key)) { seen.add(key); out.push(x); }
    }
    return out;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, f = _a0
    var seen = new Set(), out = [];
    for (var i = 0, len = arr.length; i < len; i++) {
      var x = arr[i], key = f(x);
      if (!seen.has(key)) { seen.add(key); out.push(x); }
    }
    return out;
  }
  return _dl
} as any


export const take: {
  <A>(arr: A[], n: number): A[]
  (n: number): <A>(arr: A[]) => A[]
} = function take() {
  if (arguments.length >= 2) {
    const arr = arguments[0], n = arguments[1]
    let len = arr.length;
  if (n <= 0) {
    return [];
  } else {
    return arr.slice(0, n > len ? len : n);
  }
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, n = _a0
    let len = arr.length;
  if (n <= 0) {
    return [];
  } else {
    return arr.slice(0, n > len ? len : n);
  }
  }
    _dl._op = 3
    _dl._fn = _a0
  return _dl
} as any


export const drop: {
  <A>(arr: A[], n: number): A[]
  (n: number): <A>(arr: A[]) => A[]
} = function drop() {
  if (arguments.length >= 2) {
    const arr = arguments[0], n = arguments[1]
    let len = arr.length;
  if (n <= 0) {
    return arr.slice();
  } else if (n >= len) {
    return [];
  } else {
    return arr.slice(n);
  }
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, n = _a0
    let len = arr.length;
  if (n <= 0) {
    return arr.slice();
  } else if (n >= len) {
    return [];
  } else {
    return arr.slice(n);
  }
  }
    _dl._op = 4
    _dl._fn = _a0
  return _dl
} as any


export const takeWhile: {
  <A>(arr: A[], pred: (a: A) => boolean): A[]
  <A>(pred: (a: A) => boolean): (arr: A[]) => A[]
} = function takeWhile() {
  if (arguments.length >= 2) {
    const arr = arguments[0], pred = arguments[1]
    var out = [];
    for (var i = 0, len = arr.length; i < len; i++) {
      if (!pred(arr[i])) break;
      out.push(arr[i]);
    }
    return out;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, pred = _a0
    var out = [];
    for (var i = 0, len = arr.length; i < len; i++) {
      if (!pred(arr[i])) break;
      out.push(arr[i]);
    }
    return out;
  }
    _dl._op = 5
    _dl._fn = _a0
  return _dl
} as any


export const dropWhile: {
  <A>(arr: A[], pred: (a: A) => boolean): A[]
  <A>(pred: (a: A) => boolean): (arr: A[]) => A[]
} = function dropWhile() {
  if (arguments.length >= 2) {
    const arr = arguments[0], pred = arguments[1]
    for (var i = 0, len = arr.length; i < len; i++) {
      if (!pred(arr[i])) return arr.slice(i);
    }
    return [];
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, pred = _a0
    for (var i = 0, len = arr.length; i < len; i++) {
      if (!pred(arr[i])) return arr.slice(i);
    }
    return [];
  }
    _dl._op = 6
    _dl._fn = _a0
  return _dl
} as any


export const chunk: {
  <A>(arr: A[], n: number): A[][]
  (n: number): <A>(arr: A[]) => A[][]
} = function chunk() {
  if (arguments.length >= 2) {
    const arr = arguments[0], n = arguments[1]
    var len = arr.length;
    if (n <= 0 || len === 0) return [];
    var numChunks = ((len + n - 1) / n) | 0;
    var out = new Array(numChunks);
    for (var i = 0; i < numChunks; i++) {
      out[i] = arr.slice(i * n, i * n + n);
    }
    return out;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, n = _a0
    var len = arr.length;
    if (n <= 0 || len === 0) return [];
    var numChunks = ((len + n - 1) / n) | 0;
    var out = new Array(numChunks);
    for (var i = 0; i < numChunks; i++) {
      out[i] = arr.slice(i * n, i * n + n);
    }
    return out;
  }
  return _dl
} as any


export const slidingWindow: {
  <A>(arr: A[], n: number): A[][]
  (n: number): <A>(arr: A[]) => A[][]
} = function slidingWindow() {
  if (arguments.length >= 2) {
    const arr = arguments[0], n = arguments[1]
    let len = arr.length;
  if (n <= 0 || n > len) {
    return [];
  }
  let numWindows = (len - n | 0) + 1 | 0;
  let out = new Array(numWindows);
  for (let wi = 0; wi < numWindows; ++wi) {
    let win = new Array(n);
    for (let j = 0; j < n; ++j) {
      win[j] = arr[wi + j | 0];
    }
    out[wi] = win;
  }
  return out;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, n = _a0
    let len = arr.length;
  if (n <= 0 || n > len) {
    return [];
  }
  let numWindows = (len - n | 0) + 1 | 0;
  let out = new Array(numWindows);
  for (let wi = 0; wi < numWindows; ++wi) {
    let win = new Array(n);
    for (let j = 0; j < n; ++j) {
      win[j] = arr[wi + j | 0];
    }
    out[wi] = win;
  }
  return out;
  }
  return _dl
} as any


export const intersperse: {
  <A>(arr: A[], sep: A): A[]
  <A>(sep: A): (arr: A[]) => A[]
} = function intersperse() {
  if (arguments.length >= 2) {
    const arr = arguments[0], sep = arguments[1]
    let len = arr.length;
  if (len <= 1) {
    return arr.slice(0);
  }
  let outLen = (len << 1) - 1 | 0;
  let out = new Array(outLen);
  for (let i = 0; i < len; ++i) {
    out[(i << 1)] = arr[i];
    if (i < (len - 1 | 0)) {
      out[(i << 1) + 1 | 0] = sep;
    }
  }
  return out;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, sep = _a0
    let len = arr.length;
  if (len <= 1) {
    return arr.slice(0);
  }
  let outLen = (len << 1) - 1 | 0;
  let out = new Array(outLen);
  for (let i = 0; i < len; ++i) {
    out[(i << 1)] = arr[i];
    if (i < (len - 1 | 0)) {
      out[(i << 1) + 1 | 0] = sep;
    }
  }
  return out;
  }
  return _dl
} as any


export const forEach: {
  <A>(arr: A[], f: (a: A) => void): void
  <A>(f: (a: A) => void): (arr: A[]) => void
} = function forEach() {
  if (arguments.length >= 2) {
    const arr = arguments[0], f = arguments[1]
    for (let i = 0, len = arr.length; i < len; i++) f(arr[i])
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, f = _a0
    for (let i = 0, len = arr.length; i < len; i++) f(arr[i])
  }
    _dl._op = 9
    _dl._fn = _a0
  return _dl
} as any


export const forEachWithIndex: {
  <A>(arr: A[], f: (a: A, i: number) => void): void
  <A>(f: (a: A, i: number) => void): (arr: A[]) => void
} = function forEachWithIndex() {
  if (arguments.length >= 2) {
    const arr = arguments[0], f = arguments[1]
    for (let i = 0, len = arr.length; i < len; i++) f(arr[i], i)
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, f = _a0
    for (let i = 0, len = arr.length; i < len; i++) f(arr[i], i)
  }
  return _dl
} as any


export const groupBy: {
  <A>(arr: A[], f: (a: A) => string): Dict<A[]>
  <A>(f: (a: A) => string): (arr: A[]) => Dict<A[]>
} = function groupBy() {
  if (arguments.length >= 2) {
    const arr = arguments[0], f = arguments[1]
    var out = {};
    for (var i = 0, len = arr.length; i < len; i++) {
      var x = arr[i], key = f(x);
      var existing = out[key];
      if (existing !== undefined) existing.push(x);
      else out[key] = [x];
    }
    return out;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, f = _a0
    var out = {};
    for (var i = 0, len = arr.length; i < len; i++) {
      var x = arr[i], key = f(x);
      var existing = out[key];
      if (existing !== undefined) existing.push(x);
      else out[key] = [x];
    }
    return out;
  }
  return _dl
} as any


export const partition: {
  <A>(arr: A[], pred: (a: A) => boolean): [A[], A[]]
  <A>(pred: (a: A) => boolean): (arr: A[]) => [A[], A[]]
} = function partition() {
  if (arguments.length >= 2) {
    const arr = arguments[0], pred = arguments[1]
    let len = arr.length;
  let pass = new Array(len);
  let fail = new Array(len);
  let pi = 0;
  let fi = 0;
  for (let i = 0; i < len; ++i) {
    let x = arr[i];
    if (pred(x)) {
      pass[pi] = x;
      pi = pi + 1 | 0;
    } else {
      fail[fi] = x;
      fi = fi + 1 | 0;
    }
  }
  truncate(pass, pi);
  truncate(fail, fi);
  return [
    pass,
    fail
  ];
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, pred = _a0
    let len = arr.length;
  let pass = new Array(len);
  let fail = new Array(len);
  let pi = 0;
  let fi = 0;
  for (let i = 0; i < len; ++i) {
    let x = arr[i];
    if (pred(x)) {
      pass[pi] = x;
      pi = pi + 1 | 0;
    } else {
      fail[fi] = x;
      fi = fi + 1 | 0;
    }
  }
  truncate(pass, pi);
  truncate(fail, fi);
  return [
    pass,
    fail
  ];
  }
  return _dl
} as any


export const aperture: {
  <A>(arr: A[], n: number): A[][]
  (n: number): <A>(arr: A[]) => A[][]
} = function aperture() {
  if (arguments.length >= 2) {
    const arr = arguments[0], n = arguments[1]
    let len = arr.length;
  if (n <= 0 || n > len) {
    return [];
  }
  let numWindows = (len - n | 0) + 1 | 0;
  let out = new Array(numWindows);
  for (let wi = 0; wi < numWindows; ++wi) {
    let win = new Array(n);
    for (let j = 0; j < n; ++j) {
      win[j] = arr[wi + j | 0];
    }
    out[wi] = win;
  }
  return out;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, n = _a0
    let len = arr.length;
  if (n <= 0 || n > len) {
    return [];
  }
  let numWindows = (len - n | 0) + 1 | 0;
  let out = new Array(numWindows);
  for (let wi = 0; wi < numWindows; ++wi) {
    let win = new Array(n);
    for (let j = 0; j < n; ++j) {
      win[j] = arr[wi + j | 0];
    }
    out[wi] = win;
  }
  return out;
  }
  return _dl
} as any


export const intersection: {
  <A>(a: A[], b: A[]): A[]
  <A>(b: A[]): (a: A[]) => A[]
} = function intersection() {
  if (arguments.length >= 2) {
    const a = arguments[0], b = arguments[1]
    var setB = new Set(b);
    return a.filter(function(x) { return setB.delete(x); });
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const a = data, b = _a0
    var setB = new Set(b);
    return a.filter(function(x) { return setB.delete(x); });
  }
  return _dl
} as any


export const union: {
  <A>(a: A[], b: A[]): A[]
  <A>(b: A[]): (a: A[]) => A[]
} = function union() {
  if (arguments.length >= 2) {
    const a = arguments[0], b = arguments[1]
    var la = a.length, lb = b.length, out, i, j, x, found;
    if (la + lb < 256) {
      out = a.slice();
      for (i = 0; i < lb; i++) {
        x = b[i]; found = false;
        for (j = 0; j < out.length; j++) { if (out[j] === x) { found = true; break; } }
        if (!found) out.push(x);
      }
      return out;
    }
    var seen = new Set(); out = [];
    for (i = 0; i < la; i++) { x = a[i]; if (!seen.has(x)) { seen.add(x); out.push(x); } }
    for (i = 0; i < lb; i++) { x = b[i]; if (!seen.has(x)) { seen.add(x); out.push(x); } }
    return out;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const a = data, b = _a0
    var la = a.length, lb = b.length, out, i, j, x, found;
    if (la + lb < 256) {
      out = a.slice();
      for (i = 0; i < lb; i++) {
        x = b[i]; found = false;
        for (j = 0; j < out.length; j++) { if (out[j] === x) { found = true; break; } }
        if (!found) out.push(x);
      }
      return out;
    }
    var seen = new Set(); out = [];
    for (i = 0; i < la; i++) { x = a[i]; if (!seen.has(x)) { seen.add(x); out.push(x); } }
    for (i = 0; i < lb; i++) { x = b[i]; if (!seen.has(x)) { seen.add(x); out.push(x); } }
    return out;
  }
  return _dl
} as any


export const difference: {
  <A>(a: A[], b: A[]): A[]
  <A>(b: A[]): (a: A[]) => A[]
} = function difference() {
  if (arguments.length >= 2) {
    const a = arguments[0], b = arguments[1]
    var lenA = a.length, lenB = b.length, out = [];
    if (lenB < 64) {
      outer: for (var i = 0; i < lenA; i++) {
        var x = a[i];
        for (var j = 0; j < lenB; j++) { if (b[j] === x) continue outer; }
        out.push(x);
      }
    } else {
      var setB = new Set(b);
      for (var i = 0; i < lenA; i++) {
        var x = a[i];
        if (!setB.has(x)) { setB.add(x); out.push(x); }
      }
    }
    return out;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const a = data, b = _a0
    var lenA = a.length, lenB = b.length, out = [];
    if (lenB < 64) {
      outer: for (var i = 0; i < lenA; i++) {
        var x = a[i];
        for (var j = 0; j < lenB; j++) { if (b[j] === x) continue outer; }
        out.push(x);
      }
    } else {
      var setB = new Set(b);
      for (var i = 0; i < lenA; i++) {
        var x = a[i];
        if (!setB.has(x)) { setB.add(x); out.push(x); }
      }
    }
    return out;
  }
  return _dl
} as any


export const symmetricDifference: {
  <A>(a: A[], b: A[]): A[]
  <A>(b: A[]): (a: A[]) => A[]
} = function symmetricDifference() {
  if (arguments.length >= 2) {
    const a = arguments[0], b = arguments[1]
    var la = a.length, lb = b.length, out, i, j, x;
    if (la + lb < 256) {
      var d1 = [], d2 = [];
      outer1: for (i = 0; i < la; i++) { x = a[i]; j = lb; while (j--) { if (b[j] === x) continue outer1; } d1.push(x); }
      outer2: for (i = 0; i < lb; i++) { x = b[i]; j = la; while (j--) { if (a[j] === x) continue outer2; } d2.push(x); }
      var all = d1.length + d2.length; out = new Array(all);
      for (i = 0; i < d1.length; i++) out[i] = d1[i];
      for (i = 0; i < d2.length; i++) out[d1.length + i] = d2[i];
      if (all < 2) return out;
      var r = [out[0]];
      outer3: for (i = 1; i < all; i++) { x = out[i]; j = r.length; while (j--) { if (r[j] === x) continue outer3; } r.push(x); }
      return r;
    }
    var setA = new Set(a), setB = new Set(b); out = [];
    for (i = 0; i < la; i++) { x = a[i]; if (!setB.has(x) && setA.has(x)) { setA.delete(x); out.push(x); } }
    for (i = 0; i < lb; i++) { x = b[i]; if (!setA.has(x) && setB.has(x)) { setB.delete(x); out.push(x); } }
    return out;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const a = data, b = _a0
    var la = a.length, lb = b.length, out, i, j, x;
    if (la + lb < 256) {
      var d1 = [], d2 = [];
      outer1: for (i = 0; i < la; i++) { x = a[i]; j = lb; while (j--) { if (b[j] === x) continue outer1; } d1.push(x); }
      outer2: for (i = 0; i < lb; i++) { x = b[i]; j = la; while (j--) { if (a[j] === x) continue outer2; } d2.push(x); }
      var all = d1.length + d2.length; out = new Array(all);
      for (i = 0; i < d1.length; i++) out[i] = d1[i];
      for (i = 0; i < d2.length; i++) out[d1.length + i] = d2[i];
      if (all < 2) return out;
      var r = [out[0]];
      outer3: for (i = 1; i < all; i++) { x = out[i]; j = r.length; while (j--) { if (r[j] === x) continue outer3; } r.push(x); }
      return r;
    }
    var setA = new Set(a), setB = new Set(b); out = [];
    for (i = 0; i < la; i++) { x = a[i]; if (!setB.has(x) && setA.has(x)) { setA.delete(x); out.push(x); } }
    for (i = 0; i < lb; i++) { x = b[i]; if (!setA.has(x) && setB.has(x)) { setB.delete(x); out.push(x); } }
    return out;
  }
  return _dl
} as any


// Arity 3
export const reduce: {
  <A, B>(arr: A[], f: (acc: B, a: A) => B, init: B): B
  <A, B>(f: (acc: B, a: A) => B, init: B): (arr: A[]) => B
} = function reduce() {
  if (arguments.length >= 3) {
    const arr = arguments[0], f = arguments[1], init = arguments[2]
    let acc = init
  for (let i = 0, len = arr.length; i < len; i++) acc = f(acc, arr[i])
  return acc
  }
  const _a0 = arguments[0]; const _a1 = arguments[1]
  const _dl: any = function(data: any) {
    const arr = data, f = _a0, init = _a1
    let acc = init
  for (let i = 0, len = arr.length; i < len; i++) acc = f(acc, arr[i])
  return acc
  }
    _dl._op = 8
    _dl._fn = _a0
    _dl._a1 = _a1
  return _dl
} as any


export const reduceRight: {
  <A, B>(arr: A[], f: (acc: B, a: A) => B, init: B): B
  <A, B>(f: (acc: B, a: A) => B, init: B): (arr: A[]) => B
} = function reduceRight() {
  if (arguments.length >= 3) {
    const arr = arguments[0], f = arguments[1], init = arguments[2]
    let acc = init
  for (let i = arr.length - 1; i >= 0; i--) acc = f(acc, arr[i])
  return acc
  }
  const _a0 = arguments[0]; const _a1 = arguments[1]
  const _dl: any = function(data: any) {
    const arr = data, f = _a0, init = _a1
    let acc = init
  for (let i = arr.length - 1; i >= 0; i--) acc = f(acc, arr[i])
  return acc
  }
  return _dl
} as any


export const zip: {
  <A, B>(a: A[], b: B[]): [A, B][]
  <B>(b: B[]): <A>(a: A[]) => [A, B][]
} = function zip() {
  if (arguments.length >= 2) {
    const a = arguments[0], b = arguments[1]
    var len = a.length < b.length ? a.length : b.length;
    var out = new Array(len), i = 0;
    while (i < len) { out[i] = [a[i], b[i]]; i++; }
    return out;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const a = data, b = _a0
    var len = a.length < b.length ? a.length : b.length;
    var out = new Array(len), i = 0;
    while (i < len) { out[i] = [a[i], b[i]]; i++; }
    return out;
  }
  return _dl
} as any


export const zipWith: {
  <A, B, C>(a: A[], b: B[], f: (a: A, b: B) => C): C[]
  <A, B, C>(b: B[], f: (a: A, b: B) => C): (a: A[]) => C[]
} = function zipWith() {
  if (arguments.length >= 3) {
    const a = arguments[0], b = arguments[1], f = arguments[2]
    let lenA = a.length;
  let lenB = b.length;
  let len = lenA < lenB ? lenA : lenB;
  let out = new Array(len);
  for (let i = 0; i < len; ++i) {
    out[i] = f(a[i], b[i]);
  }
  return out;
  }
  const _a0 = arguments[0]; const _a1 = arguments[1]
  const _dl: any = function(data: any) {
    const a = data, b = _a0, f = _a1
    let lenA = a.length;
  let lenB = b.length;
  let len = lenA < lenB ? lenA : lenB;
  let out = new Array(len);
  for (let i = 0; i < len; ++i) {
    out[i] = f(a[i], b[i]);
  }
  return out;
  }
  return _dl
} as any


export const adjust: {
  <A>(arr: A[], index: number, f: (a: A) => A): A[]
  <A>(index: number, f: (a: A) => A): (arr: A[]) => A[]
} = function adjust() {
  if (arguments.length >= 3) {
    const arr = arguments[0], index = arguments[1], f = arguments[2]
    let len = arr.length;
  if (index < 0 || index >= len) {
    return arr.slice(0);
  }
  let out = arr.slice(0);
  out[index] = f(arr[index]);
  return out;
  }
  const _a0 = arguments[0]; const _a1 = arguments[1]
  const _dl: any = function(data: any) {
    const arr = data, index = _a0, f = _a1
    let len = arr.length;
  if (index < 0 || index >= len) {
    return arr.slice(0);
  }
  let out = arr.slice(0);
  out[index] = f(arr[index]);
  return out;
  }
  return _dl
} as any


export const update: {
  <A>(arr: A[], index: number, value: A): A[]
  <A>(index: number, value: A): (arr: A[]) => A[]
} = function update() {
  if (arguments.length >= 3) {
    const arr = arguments[0], index = arguments[1], value = arguments[2]
    var len = arr.length;
    if (index < 0 || index >= len) return arr.slice();
    var out = arr.slice();
    out[index] = value;
    return out;
  }
  const _a0 = arguments[0]; const _a1 = arguments[1]
  const _dl: any = function(data: any) {
    const arr = data, index = _a0, value = _a1
    var len = arr.length;
    if (index < 0 || index >= len) return arr.slice();
    var out = arr.slice();
    out[index] = value;
    return out;
  }
  return _dl
} as any


export const insert: {
  <A>(arr: A[], index: number, value: A): A[]
  <A>(index: number, value: A): (arr: A[]) => A[]
} = function insert() {
  if (arguments.length >= 3) {
    const arr = arguments[0], index = arguments[1], value = arguments[2]
    let len = arr.length;
  let idx = index < 0 ? 0 : (
      index > len ? len : index
    );
  let out = new Array(len + 1 | 0);
  for (let i = 0; i < idx; ++i) {
    out[i] = arr[i];
  }
  out[idx] = value;
  for (let i$1 = idx; i$1 < len; ++i$1) {
    out[i$1 + 1 | 0] = arr[i$1];
  }
  return out;
  }
  const _a0 = arguments[0]; const _a1 = arguments[1]
  const _dl: any = function(data: any) {
    const arr = data, index = _a0, value = _a1
    let len = arr.length;
  let idx = index < 0 ? 0 : (
      index > len ? len : index
    );
  let out = new Array(len + 1 | 0);
  for (let i = 0; i < idx; ++i) {
    out[i] = arr[i];
  }
  out[idx] = value;
  for (let i$1 = idx; i$1 < len; ++i$1) {
    out[i$1 + 1 | 0] = arr[i$1];
  }
  return out;
  }
  return _dl
} as any


export const remove: {
  <A>(arr: A[], index: number, count: number): A[]
  (index: number, count: number): <A>(arr: A[]) => A[]
} = function remove() {
  if (arguments.length >= 3) {
    const arr = arguments[0], index = arguments[1], count = arguments[2]
    let len = arr.length;
  if (index < 0 || index >= len || count <= 0) {
    return arr.slice(0);
  }
  let actual = (index + count | 0) > len ? len - index | 0 : count;
  let newLen = len - actual | 0;
  let out = new Array(newLen);
  for (let i = 0; i < index; ++i) {
    out[i] = arr[i];
  }
  for (let i$1 = index + actual | 0; i$1 < len; ++i$1) {
    out[i$1 - actual | 0] = arr[i$1];
  }
  return out;
  }
  const _a0 = arguments[0]; const _a1 = arguments[1]
  const _dl: any = function(data: any) {
    const arr = data, index = _a0, count = _a1
    let len = arr.length;
  if (index < 0 || index >= len || count <= 0) {
    return arr.slice(0);
  }
  let actual = (index + count | 0) > len ? len - index | 0 : count;
  let newLen = len - actual | 0;
  let out = new Array(newLen);
  for (let i = 0; i < index; ++i) {
    out[i] = arr[i];
  }
  for (let i$1 = index + actual | 0; i$1 < len; ++i$1) {
    out[i$1 - actual | 0] = arr[i$1];
  }
  return out;
  }
  return _dl
} as any


export const scan: {
  <A, B>(arr: A[], f: (acc: B, a: A) => B, init: B): B[]
  <A, B>(f: (acc: B, a: A) => B, init: B): (arr: A[]) => B[]
} = function scan() {
  if (arguments.length >= 3) {
    const arr = arguments[0], f = arguments[1], init = arguments[2]
    let len = arr.length;
  let out = new Array(len + 1 | 0);
  let acc = init;
  out[0] = init;
  for (let i = 0; i < len; ++i) {
    acc = f(acc, arr[i]);
    out[i + 1 | 0] = acc;
  }
  return out;
  }
  const _a0 = arguments[0]; const _a1 = arguments[1]
  const _dl: any = function(data: any) {
    const arr = data, f = _a0, init = _a1
    let len = arr.length;
  let out = new Array(len + 1 | 0);
  let acc = init;
  out[0] = init;
  for (let i = 0; i < len; ++i) {
    acc = f(acc, arr[i]);
    out[i + 1 | 0] = acc;
  }
  return out;
  }
  return _dl
} as any


// Array numeric terminals (JIT-inlined in pipe)
export const sum: (arr: number[]) => number = /* @__PURE__ */ (() => {
  const _f: any = nSum
  _f._op = 41
  return _f
})()

export const min: (arr: number[]) => number = /* @__PURE__ */ (() => {
  const _f: any = nMin
  _f._op = 42
  return _f
})()

export const max: (arr: number[]) => number = /* @__PURE__ */ (() => {
  const _f: any = nMax
  _f._op = 43
  return _f
})()


// Sort specializations (JIT-inlined in pipe)
export const sortAsc: (arr: number[]) => number[] = /* @__PURE__ */ (() => {
  const _f: any = function sortAsc(arr: any) { return [...arr].sort((a, b) => a - b) }
  _f._op = 90
  return _f
})()

export const sortDesc: (arr: number[]) => number[] = /* @__PURE__ */ (() => {
  const _f: any = function sortDesc(arr: any) { return [...arr].sort((a, b) => b - a) }
  _f._op = 91
  return _f
})()


// --- Newly exposed from Array.res ---

// Arity 1
export const dropRepeats: <A>(arr: A[]) => A[] = /* @__PURE__ */ (() => {
  const _f: any = RS.dropRepeats
  _f._op = 0
  return _f
})()

export const shuffle: <A>(arr: A[]) => A[] = RS.shuffle
export const only: <A>(arr: A[]) => A | undefined = RS.only
export const mergeAll: <A>(arr: A[]) => A = RS.mergeAll
export const unnest: <A>(arr: A[][]) => A[] = RS.unnest

// Arity 2 — fuseable
export const reject: {
  <A>(arr: A[], pred: (a: A) => boolean): A[]
  <A>(pred: (a: A) => boolean): (arr: A[]) => A[]
} = function reject() {
  if (arguments.length >= 2) {
    const arr = arguments[0], pred = arguments[1]
    var out = [];
    for (var i = 0; i < arr.length; i++) { if (!pred(arr[i])) out.push(arr[i]); }
    return out;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, pred = _a0
    var out = [];
    for (var i = 0; i < arr.length; i++) { if (!pred(arr[i])) out.push(arr[i]); }
    return out;
  }
    _dl._op = 16
    _dl._fn = _a0
  return _dl
} as any


export const none: {
  <A>(arr: A[], pred: (a: A) => boolean): boolean
  <A>(pred: (a: A) => boolean): (arr: A[]) => boolean
} = function none() {
  if (arguments.length >= 2) {
    const arr = arguments[0], pred = arguments[1]
    for (var i = 0; i < arr.length; i++) { if (pred(arr[i])) return false; }
    return true;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, pred = _a0
    for (var i = 0; i < arr.length; i++) { if (pred(arr[i])) return false; }
    return true;
  }
    _dl._op = 17
    _dl._fn = _a0
  return _dl
} as any


export const count: {
  <A>(arr: A[], pred: (a: A) => boolean): number
  <A>(pred: (a: A) => boolean): (arr: A[]) => number
} = function count() {
  if (arguments.length >= 2) {
    const arr = arguments[0], pred = arguments[1]
    let len = arr.length;
  let c = 0;
  for (let i = 0; i < len; ++i) {
    if (pred(arr[i])) {
      c = c + 1 | 0;
    }
  }
  return c;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, pred = _a0
    let len = arr.length;
  let c = 0;
  for (let i = 0; i < len; ++i) {
    if (pred(arr[i])) {
      c = c + 1 | 0;
    }
  }
  return c;
  }
    _dl._op = 18
    _dl._fn = _a0
  return _dl
} as any


// Arity 2 — non-fuseable
export const append: {
  <A>(arr: A[], value: A): A[]
  <A>(value: A): (arr: A[]) => A[]
} = function append() {
  if (arguments.length >= 2) {
    const arr = arguments[0], value = arguments[1]
    let len = arr.length;
  let out = new Array(len + 1 | 0);
  for (let i = 0; i < len; ++i) {
    out[i] = arr[i];
  }
  out[len] = value;
  return out;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, value = _a0
    let len = arr.length;
  let out = new Array(len + 1 | 0);
  for (let i = 0; i < len; ++i) {
    out[i] = arr[i];
  }
  out[len] = value;
  return out;
  }
  return _dl
} as any


export const prepend: {
  <A>(arr: A[], value: A): A[]
  <A>(value: A): (arr: A[]) => A[]
} = function prepend() {
  if (arguments.length >= 2) {
    const arr = arguments[0], value = arguments[1]
    let len = arr.length;
  let out = new Array(len + 1 | 0);
  out[0] = value;
  for (let i = 0; i < len; ++i) {
    out[i + 1 | 0] = arr[i];
  }
  return out;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, value = _a0
    let len = arr.length;
  let out = new Array(len + 1 | 0);
  out[0] = value;
  for (let i = 0; i < len; ++i) {
    out[i + 1 | 0] = arr[i];
  }
  return out;
  }
  return _dl
} as any


export const concat: {
  <A>(a: A[], b: A[]): A[]
  <A>(b: A[]): (a: A[]) => A[]
} = function concat() {
  if (arguments.length >= 2) {
    const a = arguments[0], b = arguments[1]
    return a.concat(b)
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const a = data, b = _a0
    return a.concat(b)
  }
  return _dl
} as any


export const nth: {
  <A>(arr: A[], index: number): A | undefined
  (index: number): <A>(arr: A[]) => A | undefined
} = function nth() {
  if (arguments.length >= 2) {
    const arr = arguments[0], n = arguments[1]
    var i = n < 0 ? arr.length + n : n;
    return i < 0 || i >= arr.length ? undefined : arr[i];
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, n = _a0
    var i = n < 0 ? arr.length + n : n;
    return i < 0 || i >= arr.length ? undefined : arr[i];
  }
  return _dl
} as any


export const indexOf: {
  <A>(arr: A[], value: A): number | undefined
  <A>(value: A): (arr: A[]) => number | undefined
} = function indexOf() {
  if (arguments.length >= 2) {
    const arr = arguments[0], val = arguments[1]
    var i = arr.indexOf(val);
    return i === -1 ? undefined : i;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, val = _a0
    var i = arr.indexOf(val);
    return i === -1 ? undefined : i;
  }
  return _dl
} as any


export const lastIndexOf: {
  <A>(arr: A[], value: A): number | undefined
  <A>(value: A): (arr: A[]) => number | undefined
} = function lastIndexOf() {
  if (arguments.length >= 2) {
    const arr = arguments[0], val = arguments[1]
    var i = arr.lastIndexOf(val);
    return i === -1 ? undefined : i;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, val = _a0
    var i = arr.lastIndexOf(val);
    return i === -1 ? undefined : i;
  }
  return _dl
} as any


export const findLast: {
  <A>(arr: A[], pred: (a: A) => boolean): A | undefined
  <A>(pred: (a: A) => boolean): (arr: A[]) => A | undefined
} = function findLast() {
  if (arguments.length >= 2) {
    const arr = arguments[0], pred = arguments[1]
    for (var i = arr.length - 1; i >= 0; i--) { if (pred(arr[i])) return arr[i]; }
    return undefined;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, pred = _a0
    for (var i = arr.length - 1; i >= 0; i--) { if (pred(arr[i])) return arr[i]; }
    return undefined;
  }
  return _dl
} as any


export const findLastIndex: {
  <A>(arr: A[], pred: (a: A) => boolean): number | undefined
  <A>(pred: (a: A) => boolean): (arr: A[]) => number | undefined
} = function findLastIndex() {
  if (arguments.length >= 2) {
    const arr = arguments[0], pred = arguments[1]
    for (var i = arr.length - 1; i >= 0; i--) { if (pred(arr[i])) return i; }
    return undefined;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, pred = _a0
    for (var i = arr.length - 1; i >= 0; i--) { if (pred(arr[i])) return i; }
    return undefined;
  }
  return _dl
} as any


export const without: {
  <A>(arr: A[], values: A[]): A[]
  <A>(values: A[]): (arr: A[]) => A[]
} = function without() {
  if (arguments.length >= 2) {
    const arr = arguments[0], values = arguments[1]
    let exclude = new Set(values);
  let result = [];
  for (let i = 0, i_finish = arr.length; i < i_finish; ++i) {
    let x = arr[i];
    if (!exclude.has(x)) {
      result.push(x);
    }
  }
  return result;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, values = _a0
    let exclude = new Set(values);
  let result = [];
  for (let i = 0, i_finish = arr.length; i < i_finish; ++i) {
    let x = arr[i];
    if (!exclude.has(x)) {
      result.push(x);
    }
  }
  return result;
  }
  return _dl
} as any


export const pluck: {
  <A, B>(arr: A[], key: string): B[]
  (key: string): <A, B>(arr: A[]) => B[]
} = function pluck() {
  if (arguments.length >= 2) {
    const arr = arguments[0], key = arguments[1]
    return pluckRaw(arr, key);
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, key = _a0
    return pluckRaw(arr, key);
  }
  return _dl
} as any


export const dropRepeatsBy: {
  <A, B>(arr: A[], f: (a: A) => B): A[]
  <A, B>(f: (a: A) => B): (arr: A[]) => A[]
} = function dropRepeatsBy() {
  if (arguments.length >= 2) return RS.dropRepeatsBy(arguments[0], arguments[1])
  const _a0 = arguments[0]
  const _dl: any = (data: any) => RS.dropRepeatsBy(data, _a0)
  return _dl
} as any


export const dropRepeatsWith: {
  <A>(arr: A[], eq: (a: A, b: A) => boolean): A[]
  <A>(eq: (a: A, b: A) => boolean): (arr: A[]) => A[]
} = function dropRepeatsWith() {
  if (arguments.length >= 2) {
    const arr = arguments[0], eq = arguments[1]
    let len = arr.length;
  if (len === 0) {
    return [];
  }
  let result = [arr[0]];
  for (let i = 1; i < len; ++i) {
    let x = arr[i];
    if (!eq(arr[i - 1 | 0], x)) {
      result.push(x);
    }
  }
  return result;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, eq = _a0
    let len = arr.length;
  if (len === 0) {
    return [];
  }
  let result = [arr[0]];
  for (let i = 1; i < len; ++i) {
    let x = arr[i];
    if (!eq(arr[i - 1 | 0], x)) {
      result.push(x);
    }
  }
  return result;
  }
  return _dl
} as any


export const dropLast: {
  <A>(arr: A[], n: number): A[]
  (n: number): <A>(arr: A[]) => A[]
} = function dropLast() {
  if (arguments.length >= 2) {
    const arr = arguments[0], n = arguments[1]
    let len = arr.length;
  if (n <= 0) {
    return arr.slice(0);
  }
  if (n >= len) {
    return [];
  }
  let count = len - n | 0;
  let out = new Array(count);
  for (let i = 0; i < count; ++i) {
    out[i] = arr[i];
  }
  return out;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, n = _a0
    let len = arr.length;
  if (n <= 0) {
    return arr.slice(0);
  }
  if (n >= len) {
    return [];
  }
  let count = len - n | 0;
  let out = new Array(count);
  for (let i = 0; i < count; ++i) {
    out[i] = arr[i];
  }
  return out;
  }
  return _dl
} as any


export const dropLastWhile: {
  <A>(arr: A[], pred: (a: A) => boolean): A[]
  <A>(pred: (a: A) => boolean): (arr: A[]) => A[]
} = function dropLastWhile() {
  if (arguments.length >= 2) {
    const arr = arguments[0], pred = arguments[1]
    let len = arr.length;
  let i = len - 1 | 0;
  while (i >= 0 && pred(arr[i])) {
    i = i - 1 | 0;
  };
  let count = i + 1 | 0;
  if (count === len) {
    return arr.slice(0);
  }
  if (count <= 0) {
    return [];
  }
  let out = new Array(count);
  for (let j = 0; j < count; ++j) {
    out[j] = arr[j];
  }
  return out;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, pred = _a0
    let len = arr.length;
  let i = len - 1 | 0;
  while (i >= 0 && pred(arr[i])) {
    i = i - 1 | 0;
  };
  let count = i + 1 | 0;
  if (count === len) {
    return arr.slice(0);
  }
  if (count <= 0) {
    return [];
  }
  let out = new Array(count);
  for (let j = 0; j < count; ++j) {
    out[j] = arr[j];
  }
  return out;
  }
  return _dl
} as any


export const takeLast: {
  <A>(arr: A[], n: number): A[]
  (n: number): <A>(arr: A[]) => A[]
} = function takeLast() {
  if (arguments.length >= 2) {
    const arr = arguments[0], n = arguments[1]
    let len = arr.length;
  if (n <= 0) {
    return [];
  }
  if (n >= len) {
    return arr.slice(0);
  }
  let start = len - n | 0;
  let out = new Array(n);
  for (let i = 0; i < n; ++i) {
    out[i] = arr[start + i | 0];
  }
  return out;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, n = _a0
    let len = arr.length;
  if (n <= 0) {
    return [];
  }
  if (n >= len) {
    return arr.slice(0);
  }
  let start = len - n | 0;
  let out = new Array(n);
  for (let i = 0; i < n; ++i) {
    out[i] = arr[start + i | 0];
  }
  return out;
  }
  return _dl
} as any


export const takeLastWhile: {
  <A>(arr: A[], pred: (a: A) => boolean): A[]
  <A>(pred: (a: A) => boolean): (arr: A[]) => A[]
} = function takeLastWhile() {
  if (arguments.length >= 2) {
    const arr = arguments[0], pred = arguments[1]
    let len = arr.length;
  let i = len - 1 | 0;
  while (i >= 0 && pred(arr[i])) {
    i = i - 1 | 0;
  };
  let start = i + 1 | 0;
  let count = len - start | 0;
  if (count <= 0) {
    return [];
  }
  if (count === len) {
    return arr.slice(0);
  }
  let out = new Array(count);
  for (let j = 0; j < count; ++j) {
    out[j] = arr[start + j | 0];
  }
  return out;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, pred = _a0
    let len = arr.length;
  let i = len - 1 | 0;
  while (i >= 0 && pred(arr[i])) {
    i = i - 1 | 0;
  };
  let start = i + 1 | 0;
  let count = len - start | 0;
  if (count <= 0) {
    return [];
  }
  if (count === len) {
    return arr.slice(0);
  }
  let out = new Array(count);
  for (let j = 0; j < count; ++j) {
    out[j] = arr[start + j | 0];
  }
  return out;
  }
  return _dl
} as any


export const splitAt: {
  <A>(arr: A[], index: number): [A[], A[]]
  (index: number): <A>(arr: A[]) => [A[], A[]]
} = function splitAt() {
  if (arguments.length >= 2) {
    const arr = arguments[0], index = arguments[1]
    var i = index < 0 ? 0 : index > arr.length ? arr.length : index;
    return [arr.slice(0, i), arr.slice(i)];
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, index = _a0
    var i = index < 0 ? 0 : index > arr.length ? arr.length : index;
    return [arr.slice(0, i), arr.slice(i)];
  }
  return _dl
} as any


export const splitWhen: {
  <A>(arr: A[], pred: (a: A) => boolean): [A[], A[]]
  <A>(pred: (a: A) => boolean): (arr: A[]) => [A[], A[]]
} = function splitWhen() {
  if (arguments.length >= 2) {
    const arr = arguments[0], pred = arguments[1]
    let len = arr.length;
  let i = 0;
  let found = false;
  while (i < len && !found) {
    if (pred(arr[i])) {
      found = true;
    } else {
      i = i + 1 | 0;
    }
  };
  return splitAt(arr, i);
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, pred = _a0
    let len = arr.length;
  let i = 0;
  let found = false;
  while (i < len && !found) {
    if (pred(arr[i])) {
      found = true;
    } else {
      i = i + 1 | 0;
    }
  };
  return splitAt(arr, i);
  }
  return _dl
} as any


export const splitWhenever: {
  <A>(arr: A[], pred: (a: A) => boolean): A[][]
  <A>(pred: (a: A) => boolean): (arr: A[]) => A[][]
} = function splitWhenever() {
  if (arguments.length >= 2) {
    const arr = arguments[0], pred = arguments[1]
    let len = arr.length;
  if (len === 0) {
    return [];
  }
  let result = [];
  let current = [];
  for (let i = 0; i < len; ++i) {
    let x = arr[i];
    if (pred(x)) {
      result.push(current.slice());
      current.splice(0, current.length);
    } else {
      current.push(x);
    }
  }
  result.push(current.slice());
  return result;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, pred = _a0
    let len = arr.length;
  if (len === 0) {
    return [];
  }
  let result = [];
  let current = [];
  for (let i = 0; i < len; ++i) {
    let x = arr[i];
    if (pred(x)) {
      result.push(current.slice());
      current.splice(0, current.length);
    } else {
      current.push(x);
    }
  }
  result.push(current.slice());
  return result;
  }
  return _dl
} as any


export const join: {
  (arr: string[], sep: string): string
  (sep: string): (arr: string[]) => string
} = function join() {
  if (arguments.length >= 2) {
    const arr = arguments[0], sep = arguments[1]
    return arr.join(sep);
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, sep = _a0
    return arr.join(sep);
  }
  return _dl
} as any


export const uniqWith: {
  <A>(arr: A[], eq: (a: A, b: A) => boolean): A[]
  <A>(eq: (a: A, b: A) => boolean): (arr: A[]) => A[]
} = function uniqWith() {
  if (arguments.length >= 2) {
    const arr = arguments[0], eq = arguments[1]
    let result = [];
  for (let i = 0, i_finish = arr.length; i < i_finish; ++i) {
    let x = arr[i];
    let dup = false;
    let j = 0;
    while (j < result.length && !dup) {
      if (eq(result[j], x)) {
        dup = true;
      }
      j = j + 1 | 0;
    };
    if (!dup) {
      result.push(x);
    }
  }
  return result;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, eq = _a0
    let result = [];
  for (let i = 0, i_finish = arr.length; i < i_finish; ++i) {
    let x = arr[i];
    let dup = false;
    let j = 0;
    while (j < result.length && !dup) {
      if (eq(result[j], x)) {
        dup = true;
      }
      j = j + 1 | 0;
    };
    if (!dup) {
      result.push(x);
    }
  }
  return result;
  }
  return _dl
} as any


export const groupWith: {
  <A>(arr: A[], eq: (a: A, b: A) => boolean): A[][]
  <A>(eq: (a: A, b: A) => boolean): (arr: A[]) => A[][]
} = function groupWith() {
  if (arguments.length >= 2) {
    const arr = arguments[0], eq = arguments[1]
    let len = arr.length;
  if (len === 0) {
    return [];
  }
  let result = [];
  let current = [arr[0]];
  for (let i = 1; i < len; ++i) {
    let x = arr[i];
    if (eq(arr[i - 1 | 0], x)) {
      current.push(x);
    } else {
      result.push(current.slice());
      current.splice(0, current.length, x);
    }
  }
  result.push(current.slice());
  return result;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, eq = _a0
    let len = arr.length;
  if (len === 0) {
    return [];
  }
  let result = [];
  let current = [arr[0]];
  for (let i = 1; i < len; ++i) {
    let x = arr[i];
    if (eq(arr[i - 1 | 0], x)) {
      current.push(x);
    } else {
      result.push(current.slice());
      current.splice(0, current.length, x);
    }
  }
  result.push(current.slice());
  return result;
  }
  return _dl
} as any


export const indexBy: {
  <A>(arr: A[], f: (a: A) => string): Dict<A>
  <A>(f: (a: A) => string): (arr: A[]) => Dict<A>
} = function indexBy() {
  if (arguments.length >= 2) {
    const arr = arguments[0], f = arguments[1]
    let len = arr.length;
  let dict = {};
  for (let i = 0; i < len; ++i) {
    let x = arr[i];
    dict[f(x)] = x;
  }
  return dict;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, f = _a0
    let len = arr.length;
  let dict = {};
  for (let i = 0; i < len; ++i) {
    let x = arr[i];
    dict[f(x)] = x;
  }
  return dict;
  }
  return _dl
} as any


export const collectBy: {
  <A>(arr: A[], f: (a: A) => string): A[][]
  <A>(f: (a: A) => string): (arr: A[]) => A[][]
} = function collectBy() {
  if (arguments.length >= 2) {
    const arr = arguments[0], f = arguments[1]
    let len = arr.length;
  let dict = {};
  let keys = [];
  for (let i = 0; i < len; ++i) {
    let x = arr[i];
    let key = f(x);
    let group = dict[key];
    if (group !== undefined) {
      group.push(x);
    } else {
      dict[key] = [x];
      keys.push(key);
    }
  }
  let kLen = keys.length;
  let out = new Array(kLen);
  for (let i$1 = 0; i$1 < kLen; ++i$1) {
    let group$1 = dict[keys[i$1]];
    if (group$1 !== undefined) {
      out[i$1] = group$1;
    } else {
      out[i$1] = [];
    }
  }
  return out;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, f = _a0
    let len = arr.length;
  let dict = {};
  let keys = [];
  for (let i = 0; i < len; ++i) {
    let x = arr[i];
    let key = f(x);
    let group = dict[key];
    if (group !== undefined) {
      group.push(x);
    } else {
      dict[key] = [x];
      keys.push(key);
    }
  }
  let kLen = keys.length;
  let out = new Array(kLen);
  for (let i$1 = 0; i$1 < kLen; ++i$1) {
    let group$1 = dict[keys[i$1]];
    if (group$1 !== undefined) {
      out[i$1] = group$1;
    } else {
      out[i$1] = [];
    }
  }
  return out;
  }
  return _dl
} as any


export const sample: {
  <A>(arr: A[], n: number): A[]
  (n: number): <A>(arr: A[]) => A[]
} = function sample() {
  if (arguments.length >= 2) {
    const arr = arguments[0], n = arguments[1]
    return sampleRaw(arr, n);
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, n = _a0
    return sampleRaw(arr, n);
  }
  return _dl
} as any


export const hasAtLeast: {
  <A>(arr: A[], n: number): boolean
  (n: number): <A>(arr: A[]) => boolean
} = function hasAtLeast() {
  if (arguments.length >= 2) {
    const arr = arguments[0], n = arguments[1]
    return arr.length >= n;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, n = _a0
    return arr.length >= n;
  }
  return _dl
} as any


export const meanBy: {
  <A>(arr: A[], f: (a: A) => number): number
  <A>(f: (a: A) => number): (arr: A[]) => number
} = function meanBy() {
  if (arguments.length >= 2) {
    const arr = arguments[0], f = arguments[1]
    let len = arr.length;
  if (len === 0) {
    return 0.0;
  }
  let acc = 0.0;
  for (let i = 0; i < len; ++i) {
    acc = acc + f(arr[i]);
  }
  return acc / len;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, f = _a0
    let len = arr.length;
  if (len === 0) {
    return 0.0;
  }
  let acc = 0.0;
  for (let i = 0; i < len; ++i) {
    acc = acc + f(arr[i]);
  }
  return acc / len;
  }
  return _dl
} as any


export const sumBy: {
  <A>(arr: A[], f: (a: A) => number): number
  <A>(f: (a: A) => number): (arr: A[]) => number
} = function sumBy() {
  if (arguments.length >= 2) {
    const arr = arguments[0], f = arguments[1]
    let len = arr.length;
  let acc = 0.0;
  for (let i = 0; i < len; ++i) {
    acc = acc + f(arr[i]);
  }
  return acc;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, f = _a0
    let len = arr.length;
  let acc = 0.0;
  for (let i = 0; i < len; ++i) {
    acc = acc + f(arr[i]);
  }
  return acc;
  }
  return _dl
} as any


export const mapToObj: {
  <A, B>(arr: A[], f: (a: A) => [string, B]): Dict<B>
  <A, B>(f: (a: A) => [string, B]): (arr: A[]) => Dict<B>
} = function mapToObj() {
  if (arguments.length >= 2) {
    const arr = arguments[0], f = arguments[1]
    let len = arr.length;
  let dict = {};
  for (let i = 0; i < len; ++i) {
    let match = f(arr[i]);
    dict[match[0]] = match[1];
  }
  return dict;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, f = _a0
    let len = arr.length;
  let dict = {};
  for (let i = 0; i < len; ++i) {
    let match = f(arr[i]);
    dict[match[0]] = match[1];
  }
  return dict;
  }
  return _dl
} as any


export const zipObj: {
  <A>(keys: string[], values: A[]): Dict<A>
  <A>(values: A[]): (keys: string[]) => Dict<A>
} = function zipObj() {
  if (arguments.length >= 2) {
    const keys = arguments[0], values = arguments[1]
    let lenK = keys.length;
  let lenV = values.length;
  let len = lenK < lenV ? lenK : lenV;
  let dict = {};
  for (let i = 0; i < len; ++i) {
    dict[keys[i]] = values[i];
  }
  return dict;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const keys = data, values = _a0
    let lenK = keys.length;
  let lenV = values.length;
  let len = lenK < lenV ? lenK : lenV;
  let dict = {};
  for (let i = 0; i < len; ++i) {
    dict[keys[i]] = values[i];
  }
  return dict;
  }
  return _dl
} as any


export const groupByProp: {
  <A>(arr: A[], prop: string): Dict<A[]>
  (prop: string): <A>(arr: A[]) => Dict<A[]>
} = function groupByProp() {
  if (arguments.length >= 2) {
    const arr = arguments[0], prop = arguments[1]
    return groupByPropRaw(arr, prop);
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, prop = _a0
    return groupByPropRaw(arr, prop);
  }
  return _dl
} as any


export const arrayStartsWith: {
  <A>(arr: A[], prefix: A[]): boolean
  <A>(prefix: A[]): (arr: A[]) => boolean
} = function arrayStartsWith() {
  if (arguments.length >= 2) return RS.arrayStartsWith(arguments[0], arguments[1])
  const _a0 = arguments[0]
  const _dl: any = (data: any) => RS.arrayStartsWith(data, _a0)
  return _dl
} as any


export const arrayEndsWith: {
  <A>(arr: A[], suffix: A[]): boolean
  <A>(suffix: A[]): (arr: A[]) => boolean
} = function arrayEndsWith() {
  if (arguments.length >= 2) return RS.arrayEndsWith(arguments[0], arguments[1])
  const _a0 = arguments[0]
  const _dl: any = (data: any) => RS.arrayEndsWith(data, _a0)
  return _dl
} as any


export const sortedIndex: (arr: number[], value: number) => number = RS.sortedIndex

export const sortedLastIndex: (arr: number[], value: number) => number = RS.sortedLastIndex

export const pair: <A, B>(a: A, b: B) => [A, B] = RS.pair

// Arity 3
export const withoutBy: {
  <A>(arr: A[], values: A[], f: (a: A) => string): A[]
  <A>(values: A[], f: (a: A) => string): (arr: A[]) => A[]
} = function withoutBy() {
  if (arguments.length >= 3) {
    const arr = arguments[0], values = arguments[1], f = arguments[2]
    let exclude = new Set();
  for (let i = 0, i_finish = values.length; i < i_finish; ++i) {
    exclude.add(f(values[i]));
  }
  let result = [];
  for (let i$1 = 0, i_finish$1 = arr.length; i$1 < i_finish$1; ++i$1) {
    let x = arr[i$1];
    if (!exclude.has(f(x))) {
      result.push(x);
    }
  }
  return result;
  }
  const _a0 = arguments[0]; const _a1 = arguments[1]
  const _dl: any = function(data: any) {
    const arr = data, values = _a0, f = _a1
    let exclude = new Set();
  for (let i = 0, i_finish = values.length; i < i_finish; ++i) {
    exclude.add(f(values[i]));
  }
  let result = [];
  for (let i$1 = 0, i_finish$1 = arr.length; i$1 < i_finish$1; ++i$1) {
    let x = arr[i$1];
    if (!exclude.has(f(x))) {
      result.push(x);
    }
  }
  return result;
  }
  return _dl
} as any


export const slice: {
  <A>(arr: A[], start: number, end: number): A[]
  (start: number, end: number): <A>(arr: A[]) => A[]
} = function slice() {
  if (arguments.length >= 3) {
    const arr = arguments[0], start = arguments[1], end_ = arguments[2]
    let len = arr.length;
  let s = start < 0 ? (
      (len + start | 0) > 0 ? len + start | 0 : 0
    ) : (
      start < len ? start : len
    );
  let e = end_ < 0 ? (
      (len + end_ | 0) > 0 ? len + end_ | 0 : 0
    ) : (
      end_ < len ? end_ : len
    );
  if (s >= e) {
    return [];
  }
  let count = e - s | 0;
  let out = new Array(count);
  for (let i = 0; i < count; ++i) {
    out[i] = arr[s + i | 0];
  }
  return out;
  }
  const _a0 = arguments[0]; const _a1 = arguments[1]
  const _dl: any = function(data: any) {
    const arr = data, start = _a0, end_ = _a1
    let len = arr.length;
  let s = start < 0 ? (
      (len + start | 0) > 0 ? len + start | 0 : 0
    ) : (
      start < len ? start : len
    );
  let e = end_ < 0 ? (
      (len + end_ | 0) > 0 ? len + end_ | 0 : 0
    ) : (
      end_ < len ? end_ : len
    );
  if (s >= e) {
    return [];
  }
  let count = e - s | 0;
  let out = new Array(count);
  for (let i = 0; i < count; ++i) {
    out[i] = arr[s + i | 0];
  }
  return out;
  }
  return _dl
} as any


export const swap: {
  <A>(arr: A[], i: number, j: number): A[]
  (i: number, j: number): <A>(arr: A[]) => A[]
} = function swap() {
  if (arguments.length >= 3) {
    const arr = arguments[0], i = arguments[1], j = arguments[2]
    let len = arr.length;
  if (i < 0 || i >= len || j < 0 || j >= len) {
    return arr.slice(0);
  }
  let out = arr.slice(0);
  out[i] = arr[j];
  out[j] = arr[i];
  return out;
  }
  const _a0 = arguments[0]; const _a1 = arguments[1]
  const _dl: any = function(data: any) {
    const arr = data, i = _a0, j = _a1
    let len = arr.length;
  if (i < 0 || i >= len || j < 0 || j >= len) {
    return arr.slice(0);
  }
  let out = arr.slice(0);
  out[i] = arr[j];
  out[j] = arr[i];
  return out;
  }
  return _dl
} as any


export const insertAll: {
  <A>(arr: A[], index: number, values: A[]): A[]
  <A>(index: number, values: A[]): (arr: A[]) => A[]
} = function insertAll() {
  if (arguments.length >= 3) {
    const arr = arguments[0], index = arguments[1], values = arguments[2]
    let len = arr.length;
  let vLen = values.length;
  let idx = index < 0 ? 0 : (
      index > len ? len : index
    );
  let out = new Array(len + vLen | 0);
  for (let i = 0; i < idx; ++i) {
    out[i] = arr[i];
  }
  for (let i$1 = 0; i$1 < vLen; ++i$1) {
    out[idx + i$1 | 0] = values[i$1];
  }
  for (let i$2 = idx; i$2 < len; ++i$2) {
    out[i$2 + vLen | 0] = arr[i$2];
  }
  return out;
  }
  const _a0 = arguments[0]; const _a1 = arguments[1]
  const _dl: any = function(data: any) {
    const arr = data, index = _a0, values = _a1
    let len = arr.length;
  let vLen = values.length;
  let idx = index < 0 ? 0 : (
      index > len ? len : index
    );
  let out = new Array(len + vLen | 0);
  for (let i = 0; i < idx; ++i) {
    out[i] = arr[i];
  }
  for (let i$1 = 0; i$1 < vLen; ++i$1) {
    out[idx + i$1 | 0] = values[i$1];
  }
  for (let i$2 = idx; i$2 < len; ++i$2) {
    out[i$2 + vLen | 0] = arr[i$2];
  }
  return out;
  }
  return _dl
} as any


export const unionBy: {
  <A>(a: A[], b: A[], f: (a: A) => string): A[]
  <A>(b: A[], f: (a: A) => string): (a: A[]) => A[]
} = function unionBy() {
  if (arguments.length >= 3) {
    const a = arguments[0], b = arguments[1], f = arguments[2]
    let seen = new Set();
  let result = [];
  for (let i = 0, i_finish = a.length; i < i_finish; ++i) {
    let x = a[i];
    let k = f(x);
    if (!seen.has(k)) {
      seen.add(k);
      result.push(x);
    }
  }
  for (let i$1 = 0, i_finish$1 = b.length; i$1 < i_finish$1; ++i$1) {
    let x$1 = b[i$1];
    let k$1 = f(x$1);
    if (!seen.has(k$1)) {
      seen.add(k$1);
      result.push(x$1);
    }
  }
  return result;
  }
  const _a0 = arguments[0]; const _a1 = arguments[1]
  const _dl: any = function(data: any) {
    const a = data, b = _a0, f = _a1
    let seen = new Set();
  let result = [];
  for (let i = 0, i_finish = a.length; i < i_finish; ++i) {
    let x = a[i];
    let k = f(x);
    if (!seen.has(k)) {
      seen.add(k);
      result.push(x);
    }
  }
  for (let i$1 = 0, i_finish$1 = b.length; i$1 < i_finish$1; ++i$1) {
    let x$1 = b[i$1];
    let k$1 = f(x$1);
    if (!seen.has(k$1)) {
      seen.add(k$1);
      result.push(x$1);
    }
  }
  return result;
  }
  return _dl
} as any


export const unionWith: {
  <A>(a: A[], b: A[], eq: (a: A, b: A) => boolean): A[]
  <A>(b: A[], eq: (a: A, b: A) => boolean): (a: A[]) => A[]
} = function unionWith() {
  if (arguments.length >= 3) {
    const a = arguments[0], b = arguments[1], eq = arguments[2]
    let result = [];
  let addIfNew = x => {
    let dup = false;
    let j = 0;
    while (j < result.length && !dup) {
      if (eq(result[j], x)) {
        dup = true;
      }
      j = j + 1 | 0;
    };
    if (!dup) {
      result.push(x);
      return;
    }
  };
  for (let i = 0, i_finish = a.length; i < i_finish; ++i) {
    addIfNew(a[i]);
  }
  for (let i$1 = 0, i_finish$1 = b.length; i$1 < i_finish$1; ++i$1) {
    addIfNew(b[i$1]);
  }
  return result;
  }
  const _a0 = arguments[0]; const _a1 = arguments[1]
  const _dl: any = function(data: any) {
    const a = data, b = _a0, eq = _a1
    let result = [];
  let addIfNew = x => {
    let dup = false;
    let j = 0;
    while (j < result.length && !dup) {
      if (eq(result[j], x)) {
        dup = true;
      }
      j = j + 1 | 0;
    };
    if (!dup) {
      result.push(x);
      return;
    }
  };
  for (let i = 0, i_finish = a.length; i < i_finish; ++i) {
    addIfNew(a[i]);
  }
  for (let i$1 = 0, i_finish$1 = b.length; i$1 < i_finish$1; ++i$1) {
    addIfNew(b[i$1]);
  }
  return result;
  }
  return _dl
} as any


export const intersectionBy: {
  <A>(a: A[], b: A[], f: (a: A) => string): A[]
  <A>(b: A[], f: (a: A) => string): (a: A[]) => A[]
} = function intersectionBy() {
  if (arguments.length >= 3) {
    const a = arguments[0], b = arguments[1], f = arguments[2]
    let setB = new Set();
  for (let i = 0, i_finish = b.length; i < i_finish; ++i) {
    setB.add(f(b[i]));
  }
  let seen = new Set();
  let result = [];
  for (let i$1 = 0, i_finish$1 = a.length; i$1 < i_finish$1; ++i$1) {
    let x = a[i$1];
    let k = f(x);
    if (setB.has(k) && !seen.has(k)) {
      seen.add(k);
      result.push(x);
    }
  }
  return result;
  }
  const _a0 = arguments[0]; const _a1 = arguments[1]
  const _dl: any = function(data: any) {
    const a = data, b = _a0, f = _a1
    let setB = new Set();
  for (let i = 0, i_finish = b.length; i < i_finish; ++i) {
    setB.add(f(b[i]));
  }
  let seen = new Set();
  let result = [];
  for (let i$1 = 0, i_finish$1 = a.length; i$1 < i_finish$1; ++i$1) {
    let x = a[i$1];
    let k = f(x);
    if (setB.has(k) && !seen.has(k)) {
      seen.add(k);
      result.push(x);
    }
  }
  return result;
  }
  return _dl
} as any


export const differenceBy: {
  <A>(a: A[], b: A[], f: (a: A) => string): A[]
  <A>(b: A[], f: (a: A) => string): (a: A[]) => A[]
} = function differenceBy() {
  if (arguments.length >= 3) {
    const a = arguments[0], b = arguments[1], f = arguments[2]
    let setB = new Set();
  for (let i = 0, i_finish = b.length; i < i_finish; ++i) {
    setB.add(f(b[i]));
  }
  let seen = new Set();
  let result = [];
  for (let i$1 = 0, i_finish$1 = a.length; i$1 < i_finish$1; ++i$1) {
    let x = a[i$1];
    let k = f(x);
    if (!setB.has(k) && !seen.has(k)) {
      seen.add(k);
      result.push(x);
    }
  }
  return result;
  }
  const _a0 = arguments[0]; const _a1 = arguments[1]
  const _dl: any = function(data: any) {
    const a = data, b = _a0, f = _a1
    let setB = new Set();
  for (let i = 0, i_finish = b.length; i < i_finish; ++i) {
    setB.add(f(b[i]));
  }
  let seen = new Set();
  let result = [];
  for (let i$1 = 0, i_finish$1 = a.length; i$1 < i_finish$1; ++i$1) {
    let x = a[i$1];
    let k = f(x);
    if (!setB.has(k) && !seen.has(k)) {
      seen.add(k);
      result.push(x);
    }
  }
  return result;
  }
  return _dl
} as any


export const differenceWith: {
  <A>(a: A[], b: A[], eq: (a: A, b: A) => boolean): A[]
  <A>(b: A[], eq: (a: A, b: A) => boolean): (a: A[]) => A[]
} = function differenceWith() {
  if (arguments.length >= 3) {
    const a = arguments[0], b = arguments[1], eq = arguments[2]
    let result = [];
  for (let i = 0, i_finish = a.length; i < i_finish; ++i) {
    let x = a[i];
    let found = false;
    let j = 0;
    while (j < b.length && !found) {
      if (eq(x, b[j])) {
        found = true;
      }
      j = j + 1 | 0;
    };
    if (!found) {
      result.push(x);
    }
  }
  return result;
  }
  const _a0 = arguments[0]; const _a1 = arguments[1]
  const _dl: any = function(data: any) {
    const a = data, b = _a0, eq = _a1
    let result = [];
  for (let i = 0, i_finish = a.length; i < i_finish; ++i) {
    let x = a[i];
    let found = false;
    let j = 0;
    while (j < b.length && !found) {
      if (eq(x, b[j])) {
        found = true;
      }
      j = j + 1 | 0;
    };
    if (!found) {
      result.push(x);
    }
  }
  return result;
  }
  return _dl
} as any


export const symmetricDifferenceBy: {
  <A>(a: A[], b: A[], f: (a: A) => string): A[]
  <A>(b: A[], f: (a: A) => string): (a: A[]) => A[]
} = function symmetricDifferenceBy() {
  if (arguments.length >= 3) {
    const a = arguments[0], b = arguments[1], f = arguments[2]
    let setA = new Set();
  let setB = new Set();
  for (let i = 0, i_finish = a.length; i < i_finish; ++i) {
    setA.add(f(a[i]));
  }
  for (let i$1 = 0, i_finish$1 = b.length; i$1 < i_finish$1; ++i$1) {
    setB.add(f(b[i$1]));
  }
  let seen = new Set();
  let result = [];
  for (let i$2 = 0, i_finish$2 = a.length; i$2 < i_finish$2; ++i$2) {
    let x = a[i$2];
    let k = f(x);
    if (!setB.has(k) && !seen.has(k)) {
      seen.add(k);
      result.push(x);
    }
  }
  for (let i$3 = 0, i_finish$3 = b.length; i$3 < i_finish$3; ++i$3) {
    let x$1 = b[i$3];
    let k$1 = f(x$1);
    if (!setA.has(k$1) && !seen.has(k$1)) {
      seen.add(k$1);
      result.push(x$1);
    }
  }
  return result;
  }
  const _a0 = arguments[0]; const _a1 = arguments[1]
  const _dl: any = function(data: any) {
    const a = data, b = _a0, f = _a1
    let setA = new Set();
  let setB = new Set();
  for (let i = 0, i_finish = a.length; i < i_finish; ++i) {
    setA.add(f(a[i]));
  }
  for (let i$1 = 0, i_finish$1 = b.length; i$1 < i_finish$1; ++i$1) {
    setB.add(f(b[i$1]));
  }
  let seen = new Set();
  let result = [];
  for (let i$2 = 0, i_finish$2 = a.length; i$2 < i_finish$2; ++i$2) {
    let x = a[i$2];
    let k = f(x);
    if (!setB.has(k) && !seen.has(k)) {
      seen.add(k);
      result.push(x);
    }
  }
  for (let i$3 = 0, i_finish$3 = b.length; i$3 < i_finish$3; ++i$3) {
    let x$1 = b[i$3];
    let k$1 = f(x$1);
    if (!setA.has(k$1) && !seen.has(k$1)) {
      seen.add(k$1);
      result.push(x$1);
    }
  }
  return result;
  }
  return _dl
} as any


export const symmetricDifferenceWith: {
  <A>(a: A[], b: A[], eq: (a: A, b: A) => boolean): A[]
  <A>(b: A[], eq: (a: A, b: A) => boolean): (a: A[]) => A[]
} = function symmetricDifferenceWith() {
  if (arguments.length >= 3) {
    const a = arguments[0], b = arguments[1], eq = arguments[2]
    let result = [];
  for (let i = 0, i_finish = a.length; i < i_finish; ++i) {
    let x = a[i];
    let found = false;
    let j = 0;
    while (j < b.length && !found) {
      if (eq(x, b[j])) {
        found = true;
      }
      j = j + 1 | 0;
    };
    if (!found) {
      result.push(x);
    }
  }
  for (let i$1 = 0, i_finish$1 = b.length; i$1 < i_finish$1; ++i$1) {
    let x$1 = b[i$1];
    let found$1 = false;
    let j$1 = 0;
    while (j$1 < a.length && !found$1) {
      if (eq(x$1, a[j$1])) {
        found$1 = true;
      }
      j$1 = j$1 + 1 | 0;
    };
    if (!found$1) {
      result.push(x$1);
    }
  }
  return result;
  }
  const _a0 = arguments[0]; const _a1 = arguments[1]
  const _dl: any = function(data: any) {
    const a = data, b = _a0, eq = _a1
    let result = [];
  for (let i = 0, i_finish = a.length; i < i_finish; ++i) {
    let x = a[i];
    let found = false;
    let j = 0;
    while (j < b.length && !found) {
      if (eq(x, b[j])) {
        found = true;
      }
      j = j + 1 | 0;
    };
    if (!found) {
      result.push(x);
    }
  }
  for (let i$1 = 0, i_finish$1 = b.length; i$1 < i_finish$1; ++i$1) {
    let x$1 = b[i$1];
    let found$1 = false;
    let j$1 = 0;
    while (j$1 < a.length && !found$1) {
      if (eq(x$1, a[j$1])) {
        found$1 = true;
      }
      j$1 = j$1 + 1 | 0;
    };
    if (!found$1) {
      result.push(x$1);
    }
  }
  return result;
  }
  return _dl
} as any


export const sortedIndexBy: {
  <A>(arr: A[], value: A, f: (a: A) => number): number
  <A>(value: A, f: (a: A) => number): (arr: A[]) => number
} = function sortedIndexBy() {
  if (arguments.length >= 3) {
    const arr = arguments[0], value = arguments[1], f = arguments[2]
    let target = f(value);
  let lo = 0;
  let hi = arr.length;
  while (lo < hi) {
    let mid = (lo + hi | 0) / 2 | 0;
    if (f(arr[mid]) < target) {
      lo = mid + 1 | 0;
    } else {
      hi = mid;
    }
  };
  return lo;
  }
  const _a0 = arguments[0]; const _a1 = arguments[1]
  const _dl: any = function(data: any) {
    const arr = data, value = _a0, f = _a1
    let target = f(value);
  let lo = 0;
  let hi = arr.length;
  while (lo < hi) {
    let mid = (lo + hi | 0) / 2 | 0;
    if (f(arr[mid]) < target) {
      lo = mid + 1 | 0;
    } else {
      hi = mid;
    }
  };
  return lo;
  }
  return _dl
} as any


export const sortedIndexWith: {
  <A>(arr: A[], pred: (a: A) => boolean): number
  <A>(pred: (a: A) => boolean): (arr: A[]) => number
} = function sortedIndexWith() {
  if (arguments.length >= 2) {
    const arr = arguments[0], pred = arguments[1]
    let lo = 0;
  let hi = arr.length;
  while (lo < hi) {
    let mid = (lo + hi | 0) / 2 | 0;
    if (pred(arr[mid])) {
      hi = mid;
    } else {
      lo = mid + 1 | 0;
    }
  };
  return lo;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const arr = data, pred = _a0
    let lo = 0;
  let hi = arr.length;
  while (lo < hi) {
    let mid = (lo + hi | 0) / 2 | 0;
    if (pred(arr[mid])) {
      hi = mid;
    } else {
      lo = mid + 1 | 0;
    }
  };
  return lo;
  }
  return _dl
} as any


export const sortedLastIndexBy: {
  <A>(arr: A[], value: A, f: (a: A) => number): number
  <A>(value: A, f: (a: A) => number): (arr: A[]) => number
} = function sortedLastIndexBy() {
  if (arguments.length >= 3) {
    const arr = arguments[0], value = arguments[1], f = arguments[2]
    let target = f(value);
  let lo = 0;
  let hi = arr.length;
  while (lo < hi) {
    let mid = (lo + hi | 0) / 2 | 0;
    if (f(arr[mid]) <= target) {
      lo = mid + 1 | 0;
    } else {
      hi = mid;
    }
  };
  return lo;
  }
  const _a0 = arguments[0]; const _a1 = arguments[1]
  const _dl: any = function(data: any) {
    const arr = data, value = _a0, f = _a1
    let target = f(value);
  let lo = 0;
  let hi = arr.length;
  while (lo < hi) {
    let mid = (lo + hi | 0) / 2 | 0;
    if (f(arr[mid]) <= target) {
      lo = mid + 1 | 0;
    } else {
      hi = mid;
    }
  };
  return lo;
  }
  return _dl
} as any


export const mapAccum: {
  <A, B, C>(arr: A[], f: (acc: B, a: A) => [B, C], init: B): [B, C[]]
  <A, B, C>(f: (acc: B, a: A) => [B, C], init: B): (arr: A[]) => [B, C[]]
} = function mapAccum() {
  if (arguments.length >= 3) {
    const arr = arguments[0], f = arguments[1], init = arguments[2]
    let len = arr.length;
  let out = new Array(len);
  let acc = init;
  for (let i = 0; i < len; ++i) {
    let match = f(acc, arr[i]);
    acc = match[0];
    out[i] = match[1];
  }
  return [
    acc,
    out
  ];
  }
  const _a0 = arguments[0]; const _a1 = arguments[1]
  const _dl: any = function(data: any) {
    const arr = data, f = _a0, init = _a1
    let len = arr.length;
  let out = new Array(len);
  let acc = init;
  for (let i = 0; i < len; ++i) {
    let match = f(acc, arr[i]);
    acc = match[0];
    out[i] = match[1];
  }
  return [
    acc,
    out
  ];
  }
  return _dl
} as any


export const mapAccumRight: {
  <A, B, C>(arr: A[], f: (acc: B, a: A) => [B, C], init: B): [B, C[]]
  <A, B, C>(f: (acc: B, a: A) => [B, C], init: B): (arr: A[]) => [B, C[]]
} = function mapAccumRight() {
  if (arguments.length >= 3) {
    const arr = arguments[0], f = arguments[1], init = arguments[2]
    let len = arr.length;
  let out = new Array(len);
  let acc = init;
  for (let i = 0; i < len; ++i) {
    let j = (len - 1 | 0) - i | 0;
    let match = f(acc, arr[j]);
    acc = match[0];
    out[j] = match[1];
  }
  return [
    acc,
    out
  ];
  }
  const _a0 = arguments[0]; const _a1 = arguments[1]
  const _dl: any = function(data: any) {
    const arr = data, f = _a0, init = _a1
    let len = arr.length;
  let out = new Array(len);
  let acc = init;
  for (let i = 0; i < len; ++i) {
    let j = (len - 1 | 0) - i | 0;
    let match = f(acc, arr[j]);
    acc = match[0];
    out[j] = match[1];
  }
  return [
    acc,
    out
  ];
  }
  return _dl
} as any


// Arity 4
export const reduceBy: {
  <A, B>(arr: A[], keyFn: (a: A) => string, reducer: (acc: B, a: A) => B, init: B): Dict<B>
  <A, B>(keyFn: (a: A) => string, reducer: (acc: B, a: A) => B, init: B): (arr: A[]) => Dict<B>
} = function reduceBy() {
  if (arguments.length >= 4) return RS.reduceBy(arguments[0], arguments[1], arguments[2], arguments[3])
  const _a0 = arguments[0]; const _a1 = arguments[1]; const _a2 = arguments[2]
  const _dl: any = (data: any) => RS.reduceBy(data, _a0, _a1, _a2)
  return _dl
} as any


export const reduceWhile: {
  <A, B>(arr: A[], pred: (acc: B, a: A) => boolean, f: (acc: B, a: A) => B, init: B): B
  <A, B>(pred: (acc: B, a: A) => boolean, f: (acc: B, a: A) => B, init: B): (arr: A[]) => B
} = function reduceWhile() {
  if (arguments.length >= 4) {
    const arr = arguments[0], pred = arguments[1], f = arguments[2], init = arguments[3]
    let len = arr.length;
  let acc = init;
  let i = 0;
  let continue_ = true;
  while (i < len && continue_) {
    let x = arr[i];
    if (pred(acc, x)) {
      acc = f(acc, x);
      i = i + 1 | 0;
    } else {
      continue_ = false;
    }
  };
  return acc;
  }
  const _a0 = arguments[0]; const _a1 = arguments[1]; const _a2 = arguments[2]
  const _dl: any = function(data: any) {
    const arr = data, pred = _a0, f = _a1, init = _a2
    let len = arr.length;
  let acc = init;
  let i = 0;
  let continue_ = true;
  while (i < len && continue_) {
    let x = arr[i];
    if (pred(acc, x)) {
      acc = f(acc, x);
      i = i + 1 | 0;
    } else {
      continue_ = false;
    }
  };
  return acc;
  }
  return _dl
} as any


export const splice: {
  <A>(arr: A[], start: number, deleteCount: number, items: A[]): A[]
  <A>(start: number, deleteCount: number, items: A[]): (arr: A[]) => A[]
} = function splice() {
  if (arguments.length >= 4) {
    const arr = arguments[0], start = arguments[1], deleteCount = arguments[2], items = arguments[3]
    let len = arr.length;
  let s = start < 0 ? (
      (len + start | 0) > 0 ? len + start | 0 : 0
    ) : (
      start < len ? start : len
    );
  let dc = deleteCount < 0 ? 0 : (
      (s + deleteCount | 0) > len ? len - s | 0 : deleteCount
    );
  let itemsLen = items.length;
  let newLen = (len - dc | 0) + itemsLen | 0;
  let out = new Array(newLen);
  for (let i = 0; i < s; ++i) {
    out[i] = arr[i];
  }
  for (let i$1 = 0; i$1 < itemsLen; ++i$1) {
    out[s + i$1 | 0] = items[i$1];
  }
  for (let i$2 = s + dc | 0; i$2 < len; ++i$2) {
    out[(s + itemsLen | 0) + ((i$2 - s | 0) - dc | 0) | 0] = arr[i$2];
  }
  return out;
  }
  const _a0 = arguments[0]; const _a1 = arguments[1]; const _a2 = arguments[2]
  const _dl: any = function(data: any) {
    const arr = data, start = _a0, deleteCount = _a1, items = _a2
    let len = arr.length;
  let s = start < 0 ? (
      (len + start | 0) > 0 ? len + start | 0 : 0
    ) : (
      start < len ? start : len
    );
  let dc = deleteCount < 0 ? 0 : (
      (s + deleteCount | 0) > len ? len - s | 0 : deleteCount
    );
  let itemsLen = items.length;
  let newLen = (len - dc | 0) + itemsLen | 0;
  let out = new Array(newLen);
  for (let i = 0; i < s; ++i) {
    out[i] = arr[i];
  }
  for (let i$1 = 0; i$1 < itemsLen; ++i$1) {
    out[s + i$1 | 0] = items[i$1];
  }
  for (let i$2 = s + dc | 0; i$2 < len; ++i$2) {
    out[(s + itemsLen | 0) + ((i$2 - s | 0) - dc | 0) | 0] = arr[i$2];
  }
  return out;
  }
  return _dl
} as any

