// Auto-generated by codegen/dual-inline.ts. Do not edit
// Source of truth: codegen/defs/

type Dict<A> = Record<string, A>
import {
  max as nMax,
  maxNonEmpty as nMaxNonEmpty,
  maxOrUndefined as nMaxOrUndefined,
  min as nMin,
  minNonEmpty as nMinNonEmpty,
  minOrUndefined as nMinOrUndefined,
  sum as nSum,
} from './number'
import { none as optionNone, some as optionSome, type Option } from './option'
import { mergeSortBy, mergeSortAsc, mergeSortDesc } from './sort-kernel'

// Structural equality (deep, arrays/dates/plain-objects), used where entries need
// value comparison rather than reference identity
function structEq(a: any, b: any): boolean {
  if (a === b) return true
  if (a === null || b === null || typeof a !== typeof b) return false
  if (typeof a !== 'object') return false
  if (Array.isArray(a) || Array.isArray(b)) {
    if (!Array.isArray(a) || !Array.isArray(b) || a.length !== b.length) return false
    for (let i = 0; i < a.length; i++) if (!structEq(a[i], b[i])) return false
    return true
  }
  if (a instanceof Date && b instanceof Date) return +a === +b
  for (const k in a) if (!structEq(a[k], b[k])) return false
  for (const k in b) if (!(k in a)) return false
  return true
}

function truncate<A>(a: A[], n: number): void {
  a.length = n
}

function sameValueZero(a: unknown, b: unknown): boolean {
  return a === b || (a !== a && b !== b)
}

function pluckRaw(
  arr: readonly Readonly<Record<PropertyKey, unknown>>[],
  key: PropertyKey,
): unknown[] {
  const len = arr.length
  const out = new Array<unknown>(len)
  for (let i = 0; i < len; i++) {
    out[i] = arr[i][key]
  }
  return out
}

function sampleRaw<A>(arr: readonly A[], n: number): A[] {
  var len = arr.length
  var size = n > len ? len : n
  var copy = arr.slice()
  for (var i = len - 1; i > len - 1 - size && i > 0; i--) {
    var j = Math.floor(Math.random() * (i + 1))
    var tmp = copy[i]
    copy[i] = copy[j]
    copy[j] = tmp
  }
  return copy.slice(len - size)
}

function groupByPropRaw<A extends Readonly<Record<PropertyKey, unknown>>>(
  arr: readonly A[],
  prop: keyof A,
): Dict<A[]> {
  var dict: Dict<A[]> = {}
  for (var i = 0; i < arr.length; i++) {
    var key = String(arr[i][prop])
    if (!dict[key]) dict[key] = []
    dict[key].push(arr[i])
  }
  return dict
}

// Arity 1. Tagged for fusion engine (accessor ops get inlined in pipe)
export const headOrUndefined: <A>(arr: readonly A[]) => A | undefined = function headOrUndefined(arr: any) { return arr[0] } as any

export const head: <A>(arr: readonly A[]) => Option<A> = function head(a: any) { return (a.length === 0 ? optionNone : optionSome(a[0])) } as any

export const headNonEmpty: <A>(arr: readonly [A, ...A[]]) => A = function headNonEmpty(arr: any) { return arr[0] } as any


export const lastOrUndefined: <A>(arr: readonly A[]) => A | undefined = function lastOrUndefined(arr: any) { return arr[arr.length - 1] } as any

export const last: <A>(arr: readonly A[]) => Option<A> = function last(a: any) { return (a.length === 0 ? optionNone : optionSome(a[a.length - 1])) } as any

export const lastNonEmpty: <A>(arr: readonly [A, ...A[]]) => A = function lastNonEmpty(arr: any) { return arr[arr.length - 1] } as any

export const tail: <A>(arr: readonly A[]) => A[] = function tail(arr: any) { if (arr.length <= 1) {
      return []
    } else {
      return arr.slice(1)
    } } as any

export const init: <A>(arr: readonly A[]) => A[] = function init(arr: any) { let len = arr.length
    if (len <= 1) {
      return []
    } else {
      return arr.slice(0, (len - 1) | 0)
    } } as any

export const isEmpty: <A>(arr: readonly A[]) => boolean = function isEmpty(arr: any) { return arr.length === 0 } as any

export const length: <A>(arr: readonly A[]) => number = function length(arr: any) { return arr.length } as any

export const reverse: <A>(arr: readonly A[]) => A[] = function reverse(arr: any) { return arr.toReversed ? arr.toReversed() : arr.slice().reverse() } as any

export const flatten: <A>(arr: readonly A[][]) => A[] = function flatten(arr: any) { var out = []
    for (var i = 0; i < arr.length; i++) {
      var inner = arr[i]
      for (var j = 0; j < inner.length; j++) out.push(inner[j])
    }
    return out } as any

export const firstOrUndefined = headOrUndefined
export const first: typeof head = head

// Standalone generators (no dual)
export const range: (start: number, end: number) => number[] = (start: any, end: any) => {
  if (end <= start) return []
  const len = end - start
  const out = new Array(len)
  for (let i = 0; i < len; i++) out[i] = start + i
  return out
}
export const sort: (arr: readonly number[]) => number[] = function sort(arr: any) { return mergeSortAsc(arr) } as any

export const transpose: <A>(arr: readonly A[][]) => A[][] = function transpose(arr: any) { const rows = arr.length
    if (rows === 0) return []
    let cols = arr[0].length
    for (let i = 1; i < rows; i++) {
      const rowLen = arr[i].length
      if (rowLen < cols) cols = rowLen
    }
    if (cols === 0) return []
    const out = new Array(cols)
    for (let c = 0; c < cols; c++) {
      const col = new Array(rows)
      for (let r = 0; r < rows; r++) col[r] = arr[r][c]
      out[c] = col
    }
    return out } as any


export const repeat: <A>(n: number) => (value: A) => A[] = function repeat(n: any) {
  return function (value: any) {
    if (n <= 0) return []
    const out = new Array(n)
    for (let i = 0; i < n; i++) out[i] = value
    return out
  }
} as any


export const times: (n: number) => <A>(f: (i: number) => A) => A[] = function times(n: any) {
  return function (f: any) {
    if (n <= 0) return []
    const out = new Array(n)
    for (let i = 0; i < n; i++) out[i] = f(i)
    return out
  }
} as any


export const unfold: <A, B>(seed: B) => (f: (seed: B) => [A, B] | undefined) => A[] = function unfold(seed: any) {
  return function (f: any) {
    const result: any[] = []
    let s = seed
    while (true) {
      const match = f(s)
      if (match === undefined) break
      result.push(match[0])
      s = match[1]
    }
    return result
  }
} as any


export const xprod: <B>(b: readonly B[]) => <A>(a: readonly A[]) => [A, B][] = function xprod(b: any) {
  return function (a: any) {
    let lenA = a.length
    let lenB = b.length
    let total = (lenA * lenB) | 0
    if (total === 0) {
      return []
    }
    let out = new Array(total)
    for (let i = 0; i < lenA; ++i) {
      for (let j = 0; j < lenB; ++j) {
        out[(((i * lenB) | 0) + j) | 0] = [a[i], b[j]]
      }
    }
    return out
  }
} as any


// Arity 2
export const map: <A, B>(f: (a: A) => B) => (arr: readonly A[]) => B[] = function map(f: any) {
  return function (arr: any) {
    const len = arr.length,
      out = new Array(len)
    for (let i = 0; i < len; i++) out[i] = f(arr[i])
    return out
  }
} as any


export const mapWithIndex: <A, B>(f: (a: A, i: number) => B) => (arr: readonly A[]) => B[] = function mapWithIndex(f: any) {
  return function (arr: any) {
    const len = arr.length,
      out = new Array(len)
    for (let i = 0; i < len; i++) out[i] = f(arr[i], i)
    return out
  }
} as any


export const filter: {
  <A, B extends A>(pred: (a: A) => a is B): (arr: readonly A[]) => B[]
  <A>(pred: (a: A) => boolean): (arr: readonly A[]) => A[]
} = function filter(pred: any) {
  return function (arr: any) {
    const out: any[] = []
    for (let i = 0, len = arr.length; i < len; i++) {
      const v = arr[i]
      if (pred(v)) out.push(v)
    }
    return out
  }
} as any


export const filterWithIndex: {
  <A, B extends A>(pred: (a: A, i: number) => a is B): (arr: readonly A[]) => B[]
  <A>(pred: (a: A, i: number) => boolean): (arr: readonly A[]) => A[]
} = function filterWithIndex(pred: any) {
  return function (arr: any) {
    const out: any[] = []
    for (let i = 0, len = arr.length; i < len; i++) {
      const v = arr[i]
      if (pred(v, i)) out.push(v)
    }
    return out
  }
} as any


export const flatMap: <A, B>(f: (a: A) => B[]) => (arr: readonly A[]) => B[] = function flatMap(f: any) {
  return function (arr: any) {
    const out: any[] = []
    for (let i = 0, len = arr.length; i < len; i++) {
      const r = f(arr[i])
      for (let j = 0, rlen = r.length; j < rlen; j++) out.push(r[j])
    }
    return out
  }
} as any


export const findOrUndefined: {
  <A, B extends A>(pred: (a: A) => a is B): (arr: readonly A[]) => B | undefined
  <A>(pred: (a: A) => boolean): (arr: readonly A[]) => A | undefined
} = function findOrUndefined(pred: any) {
  return function (arr: any) {
    for (let i = 0, len = arr.length; i < len; i++) {
    const v = arr[i]
    if (pred(v)) return v
  }
  return undefined
  }
} as any


export const find: {
  <A, B extends A>(pred: (a: A) => a is B): (arr: readonly A[]) => Option<B>
  <A>(pred: (a: A) => boolean): (arr: readonly A[]) => Option<A>
} = function find(pred: any) {
  return function (arr: any) {
    for (let i = 0, len = arr.length; i < len; i++) {
      const v = arr[i]
      if (pred(v)) return optionSome(v)
    }
    return optionNone
  }
} as any


export const findIndexOrUndefined: <A>(pred: (a: A) => boolean) => (arr: readonly A[]) => number | undefined = function findIndexOrUndefined(pred: any) {
  return function (arr: any) {
    for (let i = 0, len = arr.length; i < len; i++) {
    if (pred(arr[i])) return i
  }
  return undefined
  }
} as any


export const findIndex: <A>(pred: (a: A) => boolean) => (arr: readonly A[]) => Option<number> = function findIndex(pred: any) {
  return function (arr: any) {
    for (let i = 0, len = arr.length; i < len; i++) {
      if (pred(arr[i])) return optionSome(i)
    }
    return optionNone
  }
} as any


export const every: <A>(pred: (a: A) => boolean) => (arr: readonly A[]) => boolean = function every(pred: any) {
  return function (arr: any) {
    for (let i = 0, len = arr.length; i < len; i++) {
      if (!pred(arr[i])) return false
    }
    return true
  }
} as any


export const some: <A>(pred: (a: A) => boolean) => (arr: readonly A[]) => boolean = function some(pred: any) {
  return function (arr: any) {
    for (let i = 0, len = arr.length; i < len; i++) {
      if (pred(arr[i])) return true
    }
    return false
  }
} as any


export const includes: <A>(value: A) => (arr: readonly A[]) => boolean = function includes(value: any) {
  return function (arr: any) {
    return arr.includes(value)
  }
} as any


export const sortBy: <A>(cmp: (a: A, b: A) => number) => (arr: readonly A[]) => A[] = function sortBy(cmp: any) {
  return function (arr: any) {
    return mergeSortBy(arr, cmp)
  }
} as any


// takeSortedBy must equal sortBy(cmp) |> take(k) -- stable-sort semantics,
// not merely "the k smallest by cmp" (a prior quickselect-based version broke
// this: tied keys could come out in a different relative order than a stable
// sort would give). A bounded insertion buffer reproduces stable-sort
// tie-break exactly (see takeSortedBy below) but its cost grows with k, so
// past this limit we fall back to a full stable sort (cost independent of
// k). Measured (scratch benchmarks, random + heavily-tied data, n from 1e4
// to 1e6): the bounded buffer wins decisively for small k -- the op's home
// turf, e.g. 5-12x faster than the old quickselect at k<=200, n>=1e5 -- and
// keeps beating a full sort through roughly k~2000-7000 depending on n;
// 2048 stays inside that margin across the whole range measured.
const TAKE_SORTED_BY_BOUNDED_LIMIT = 2048

export const takeSortedBy: <A>(k: number, cmp: (a: A, b: A) => number) => (arr: readonly A[]) => A[] = function takeSortedBy(k: any, cmp: any) {
  return function (arr: any) {
    var n = arr.length
  if (k <= 0) return []
  if (k >= n) return mergeSortBy(arr, cmp)
  if (k > TAKE_SORTED_BY_BOUNDED_LIMIT) return mergeSortBy(arr, cmp).slice(0, k)
  // Stable top-k: keep a sorted buffer of the k best-so-far source elements.
  // A new element either grows the buffer (while it has room) or replaces
  // the current worst kept element when strictly better than it (never on a
  // tie). Insertion shifts only elements strictly greater than the incoming
  // value, so a tied key never moves past an equal one already in the
  // buffer; composed with left-to-right source order, that reproduces a
  // stable sort's tie-break (earlier index wins) without ever comparing
  // indexes. Same algorithm fp-compiler's emitFusedSortTake fuses inline for
  // a sortBy|>take pipeline.
  var top = new Array(k)
  var size = 0
  var p
  for (var idx = 0; idx < n; idx++) {
    var v = arr[idx]
    if (size < k) {
      p = size
      while (p > 0 && cmp(top[p - 1], v) > 0) { top[p] = top[p - 1]; p-- }
      top[p] = v
      size++
    } else if (cmp(v, top[k - 1]) < 0) {
      p = k - 1
      while (p > 0 && cmp(top[p - 1], v) > 0) { top[p] = top[p - 1]; p-- }
      top[p] = v
    }
  }
  return top
  }
} as any


export const uniq: <A>(arr: readonly A[]) => A[] = function uniq(arr: any) { return Array.from(new Set(arr)) } as any


export const uniqBy: <A, B>(f: (a: A) => B) => (arr: readonly A[]) => A[] = function uniqBy(f: any) {
  return function (arr: any) {
    var seen = new Set(),
      out = []
    for (var i = 0, len = arr.length; i < len; i++) {
      var x = arr[i],
        key = f(x)
      if (!seen.has(key)) {
        seen.add(key)
        out.push(x)
      }
    }
    return out
  }
} as any


export const take: (n: number) => <A>(arr: readonly A[]) => A[] = function take(n: any) {
  return function (arr: any) {
    let len = arr.length
    if (n <= 0) {
      return []
    } else {
      return arr.slice(0, n > len ? len : n)
    }
  }
} as any


export const drop: (n: number) => <A>(arr: readonly A[]) => A[] = function drop(n: any) {
  return function (arr: any) {
    let len = arr.length
    if (n <= 0) {
      return arr.slice()
    } else if (n >= len) {
      return []
    } else {
      return arr.slice(n)
    }
  }
} as any


export const takeWhile: <A>(pred: (a: A) => boolean) => (arr: readonly A[]) => A[] = function takeWhile(pred: any) {
  return function (arr: any) {
    var len = arr.length
    var i = 0
    while (i < len && pred(arr[i])) i++
    return arr.slice(0, i)
  }
} as any


export const dropWhile: <A>(pred: (a: A) => boolean) => (arr: readonly A[]) => A[] = function dropWhile(pred: any) {
  return function (arr: any) {
    for (var i = 0, len = arr.length; i < len; i++) {
      if (!pred(arr[i])) return arr.slice(i)
    }
    return []
  }
} as any


export const chunk: (n: number) => <A>(arr: readonly A[]) => A[][] = function chunk(n: any) {
  return function (arr: any) {
    var len = arr.length
    if (n <= 0 || len === 0) return []
    var numChunks = ((len + n - 1) / n) | 0
    var out = new Array(numChunks)
    for (var i = 0; i < numChunks; i++) {
      out[i] = arr.slice(i * n, i * n + n)
    }
    return out
  }
} as any


export const slidingWindow: (n: number) => <A>(arr: readonly A[]) => A[][] = function slidingWindow(n: any) {
  return function (arr: any) {
    let len = arr.length
    if (n <= 0 || n > len) {
      return []
    }
    let numWindows = (((len - n) | 0) + 1) | 0
    let out = new Array(numWindows)
    for (let wi = 0; wi < numWindows; ++wi) {
      let win = new Array(n)
      for (let j = 0; j < n; ++j) {
        win[j] = arr[(wi + j) | 0]
      }
      out[wi] = win
    }
    return out
  }
} as any


export const intersperse: <A>(sep: A) => (arr: readonly A[]) => A[] = function intersperse(sep: any) {
  return function (arr: any) {
    let len = arr.length
    if (len <= 1) {
      return arr.slice(0)
    }
    let outLen = ((len << 1) - 1) | 0
    let out = new Array(outLen)
    for (let i = 0; i < len; ++i) {
      out[i << 1] = arr[i]
      if (i < ((len - 1) | 0)) {
        out[((i << 1) + 1) | 0] = sep
      }
    }
    return out
  }
} as any


export const forEach: <A>(f: (a: A) => void) => (arr: readonly A[]) => void = function forEach(f: any) {
  return function (arr: any) {
    for (let i = 0, len = arr.length; i < len; i++) f(arr[i])
  }
} as any


export const forEachWithIndex: <A>(f: (a: A, i: number) => void) => (arr: readonly A[]) => void = function forEachWithIndex(f: any) {
  return function (arr: any) {
    for (let i = 0, len = arr.length; i < len; i++) f(arr[i], i)
  }
} as any


export const groupBy: <A>(f: (a: A) => string) => (arr: readonly A[]) => Dict<A[]> = function groupBy(f: any) {
  return function (arr: any) {
    var out: Dict<any[]> = {}
    for (var i = 0, len = arr.length; i < len; i++) {
      var x = arr[i],
        key = f(x)
      var existing = out[key]
      if (existing !== undefined) existing.push(x)
      else out[key] = [x]
    }
    return out
  }
} as any


export const partition: <A>(pred: (a: A) => boolean) => (arr: readonly A[]) => [A[], A[]] = function partition(pred: any) {
  return function (arr: any) {
    let len = arr.length
    let pass = new Array(len)
    let fail = new Array(len)
    let pi = 0
    let fi = 0
    for (let i = 0; i < len; ++i) {
      let x = arr[i]
      if (pred(x)) {
        pass[pi] = x
        pi = (pi + 1) | 0
      } else {
        fail[fi] = x
        fi = (fi + 1) | 0
      }
    }
    truncate(pass, pi)
    truncate(fail, fi)
    return [pass, fail]
  }
} as any


export const aperture: (n: number) => <A>(arr: readonly A[]) => A[][] = function aperture(n: any) {
  return function (arr: any) {
    let len = arr.length
    if (n <= 0 || n > len) {
      return []
    }
    let numWindows = (((len - n) | 0) + 1) | 0
    let out = new Array(numWindows)
    for (let wi = 0; wi < numWindows; ++wi) {
      let win = new Array(n)
      for (let j = 0; j < n; ++j) {
        win[j] = arr[(wi + j) | 0]
      }
      out[wi] = win
    }
    return out
  }
} as any


export const intersection: <A>(b: readonly A[]) => (a: readonly A[]) => A[] = function intersection(b: any) {
  return function (a: any) {
    const included = new Set(b)
    const emitted = new Set()
    const out = []
    for (let i = 0; i < a.length; i++) {
      const value = a[i]
      if (included.has(value) && !emitted.has(value)) {
        emitted.add(value)
        out.push(value)
      }
    }
    return out
  }
} as any


export const union: <A>(b: readonly A[]) => (a: readonly A[]) => A[] = function union(b: any) {
  return function (a: any) {
    const seen = new Set()
    const out = []
    for (let i = 0; i < a.length; i++) {
      const value = a[i]
      if (!seen.has(value)) {
        seen.add(value)
        out.push(value)
      }
    }
    for (let i = 0; i < b.length; i++) {
      const value = b[i]
      if (!seen.has(value)) {
        seen.add(value)
        out.push(value)
      }
    }
    return out
  }
} as any


export const difference: <A>(b: readonly A[]) => (a: readonly A[]) => A[] = function difference(b: any) {
  return function (a: any) {
    const excluded = new Set(b)
    const emitted = new Set()
    const out = []
    for (let i = 0; i < a.length; i++) {
      const value = a[i]
      if (!excluded.has(value) && !emitted.has(value)) {
        emitted.add(value)
        out.push(value)
      }
    }
    return out
  }
} as any


export const symmetricDifference: <A>(b: readonly A[]) => (a: readonly A[]) => A[] = function symmetricDifference(b: any) {
  return function (a: any) {
    const setA = new Set(a)
    const setB = new Set(b)
    const emitted = new Set()
    const out = []
    for (let i = 0; i < a.length; i++) {
      const value = a[i]
      if (!setB.has(value) && !emitted.has(value)) {
        emitted.add(value)
        out.push(value)
      }
    }
    for (let i = 0; i < b.length; i++) {
      const value = b[i]
      if (!setA.has(value) && !emitted.has(value)) {
        emitted.add(value)
        out.push(value)
      }
    }
    return out
  }
} as any


// Arity 3
export const reduce: <A, B>(f: (acc: B, a: A) => B, init: B) => (arr: readonly A[]) => B = function reduce(f: any, init: any) {
  return function (arr: any) {
    let acc = init
    for (let i = 0, len = arr.length; i < len; i++) acc = f(acc, arr[i])
    return acc
  }
} as any


export const reduceRight: <A, B>(f: (acc: B, a: A) => B, init: B) => (arr: readonly A[]) => B = function reduceRight(f: any, init: any) {
  return function (arr: any) {
    let acc = init
    for (let i = arr.length - 1; i >= 0; i--) acc = f(acc, arr[i])
    return acc
  }
} as any


export const zip: <B>(b: readonly B[]) => <A>(a: readonly A[]) => [A, B][] = function zip(b: any) {
  return function (a: any) {
    var len = a.length < b.length ? a.length : b.length
    var out = new Array(len),
      i = 0
    while (i < len) {
      out[i] = [a[i], b[i]]
      i++
    }
    return out
  }
} as any


export const zipWith: <A, B, C>(b: readonly B[], f: (a: A, b: B) => C) => (a: readonly A[]) => C[] = function zipWith(b: any, f: any) {
  return function (a: any) {
    let lenA = a.length
    let lenB = b.length
    let len = lenA < lenB ? lenA : lenB
    let out = new Array(len)
    for (let i = 0; i < len; ++i) {
      out[i] = f(a[i], b[i])
    }
    return out
  }
} as any


export const adjust: <A>(index: number, f: (a: A) => A) => (arr: readonly A[]) => A[] = function adjust(index: any, f: any) {
  return function (arr: any) {
    let len = arr.length
    if (index < 0 || index >= len) {
      return arr.slice(0)
    }
    let out = arr.slice(0)
    out[index] = f(arr[index])
    return out
  }
} as any


export const update: <A>(index: number, value: A) => (arr: readonly A[]) => A[] = function update(index: any, value: any) {
  return function (arr: any) {
    var len = arr.length
    if (index < 0 || index >= len) return arr.slice()
    var out = arr.slice()
    out[index] = value
    return out
  }
} as any


export const insert: <A>(index: number, value: A) => (arr: readonly A[]) => A[] = function insert(index: any, value: any) {
  return function (arr: any) {
    let len = arr.length
    let idx = index < 0 ? 0 : index > len ? len : index
    let out = new Array((len + 1) | 0)
    for (let i = 0; i < idx; ++i) {
      out[i] = arr[i]
    }
    out[idx] = value
    for (let i$1 = idx; i$1 < len; ++i$1) {
      out[(i$1 + 1) | 0] = arr[i$1]
    }
    return out
  }
} as any


export const remove: (index: number, count: number) => <A>(arr: readonly A[]) => A[] = function remove(index: any, count: any) {
  return function (arr: any) {
    let len = arr.length
    if (index < 0 || index >= len || count <= 0) {
      return arr.slice(0)
    }
    let actual = ((index + count) | 0) > len ? (len - index) | 0 : count
    let newLen = (len - actual) | 0
    let out = new Array(newLen)
    for (let i = 0; i < index; ++i) {
      out[i] = arr[i]
    }
    for (let i$1 = (index + actual) | 0; i$1 < len; ++i$1) {
      out[(i$1 - actual) | 0] = arr[i$1]
    }
    return out
  }
} as any


export const scan: <A, B>(f: (acc: B, a: A) => B, init: B) => (arr: readonly A[]) => B[] = function scan(f: any, init: any) {
  return function (arr: any) {
    let len = arr.length
    let out = new Array((len + 1) | 0)
    let acc = init
    out[0] = init
    for (let i = 0; i < len; ++i) {
      acc = f(acc, arr[i])
      out[(i + 1) | 0] = acc
    }
    return out
  }
} as any


// Array numeric terminals (JIT-inlined in pipe)
export const sum: (arr: readonly number[]) => number = nSum

export const minOrUndefined: (arr: readonly number[]) => number | undefined = function minOrUndefined(arr: any) { return nMinOrUndefined(arr) } as any

export const min: (arr: readonly number[]) => Option<number> = nMin

export const minNonEmpty: (arr: readonly [number, ...number[]]) => number = function minNonEmpty(arr: any) { return nMinNonEmpty(arr) } as any

export const maxOrUndefined: (arr: readonly number[]) => number | undefined = function maxOrUndefined(arr: any) { return nMaxOrUndefined(arr) } as any

export const max: (arr: readonly number[]) => Option<number> = nMax

export const maxNonEmpty: (arr: readonly [number, ...number[]]) => number = function maxNonEmpty(arr: any) { return nMaxNonEmpty(arr) } as any


// Sort specializations (JIT-inlined in pipe)
export const sortAsc: (arr: readonly number[]) => number[] = function sortAsc(arr: any) { return mergeSortAsc(arr) } as any

export const sortDesc: (arr: readonly number[]) => number[] = function sortDesc(arr: any) { return mergeSortDesc(arr) } as any


// --- Newly exposed from Array.res ---

// Arity 1
export const dropRepeats: <A>(arr: readonly A[]) => A[] = function dropRepeats(arr: any) { const len = arr.length
    if (len === 0) return []
    const result = [arr[0]]
    for (let i = 1; i < len; i++) {
      const x = arr[i]
      if (!structEq(x, arr[i - 1])) result.push(x)
    }
    return result } as any

export const shuffle: <A>(arr: readonly A[]) => A[] = function shuffle(arr: any) { const copy = arr.slice()
    for (let i = copy.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1))
      const tmp = copy[i]
      copy[i] = copy[j]
      copy[j] = tmp
    }
    return copy } as any

export const onlyOrUndefined: <A>(arr: readonly A[]) => A | undefined = function onlyOrUndefined(arr: any) { return (arr.length === 1 ? arr[0] : undefined) } as any

export const only: <A>(arr: readonly A[]) => Option<A> = function only(arr: any) { return (arr.length === 1 ? optionSome(arr[0]) : optionNone) } as any

export const mergeAll: <A>(arr: readonly A[]) => A = function mergeAll(arr: any) { return Object.assign({}, ...arr) } as any

export const unnest: <A>(arr: readonly A[][]) => A[] = function unnest(arr: any) { return flatten(arr as any) } as any


// Arity 2. Fuseable
export const reject: <A>(pred: (a: A) => boolean) => (arr: readonly A[]) => A[] = function reject(pred: any) {
  return function (arr: any) {
    const len = arr.length
    var out = []
    for (var i = 0; i < len; i++) {
      if (!pred(arr[i])) out.push(arr[i])
    }
    return out
  }
} as any


export const none: <A>(pred: (a: A) => boolean) => (arr: readonly A[]) => boolean = function none(pred: any) {
  return function (arr: any) {
    const len = arr.length
    for (var i = 0; i < len; i++) {
      if (pred(arr[i])) return false
    }
    return true
  }
} as any


export const count: <A>(pred: (a: A) => boolean) => (arr: readonly A[]) => number = function count(pred: any) {
  return function (arr: any) {
    let len = arr.length
    let c = 0
    for (let i = 0; i < len; ++i) {
      if (pred(arr[i])) {
        c = (c + 1) | 0
      }
    }
    return c
  }
} as any


export const filterMap: <A, B>(f: (a: A) => B | null | undefined) => (arr: readonly A[]) => B[] = function filterMap(f: any) {
  return function (arr: any) {
    const out: any[] = []
    for (let i = 0, len = arr.length; i < len; i++) {
      const mapped = f(arr[i])
      if (mapped != null) out.push(mapped)
    }
    return out
  }
} as any


export const findMapOrUndefined: <A, B>(f: (a: A) => B | null | undefined) => (arr: readonly A[]) => B | undefined = function findMapOrUndefined(f: any) {
  return function (arr: any) {
    for (let i = 0, len = arr.length; i < len; i++) {
    const mapped = f(arr[i])
    if (mapped != null) return mapped
  }
  return undefined
  }
} as any


export const findMap: <A, B>(f: (a: A) => B | null | undefined) => (arr: readonly A[]) => Option<NonNullable<B>> = function findMap(f: any) {
  return function (arr: any) {
    for (let i = 0, len = arr.length; i < len; i++) {
      const mapped = f(arr[i])
      if (mapped != null) return optionSome(mapped)
    }
    return optionNone
  }
} as any


export const mapWhile: <A, B>(f: (a: A) => B | null | undefined) => (arr: readonly A[]) => B[] = function mapWhile(f: any) {
  return function (arr: any) {
    const out: any[] = []
    for (let i = 0, len = arr.length; i < len; i++) {
      const mapped = f(arr[i])
      if (mapped == null) break
      out.push(mapped)
    }
    return out
  }
} as any


export const takeUntil: <A>(pred: (a: A) => boolean) => (arr: readonly A[]) => A[] = function takeUntil(pred: any) {
  return function (arr: any) {
    const len = arr.length
    let i = 0
    while (i < len && !pred(arr[i])) i++
    return arr.slice(0, i)
  }
} as any


// Arity 2. Non-fuseable
export const append: <A>(value: A) => (arr: readonly A[]) => A[] = function append(value: any) {
  return function (arr: any) {
    let len = arr.length
  let out = new Array((len + 1) | 0)
  for (let i = 0; i < len; ++i) {
    out[i] = arr[i]
  }
  out[len] = value
  return out
  }
} as any


export const prepend: <A>(value: A) => (arr: readonly A[]) => A[] = function prepend(value: any) {
  return function (arr: any) {
    let len = arr.length
  let out = new Array((len + 1) | 0)
  out[0] = value
  for (let i = 0; i < len; ++i) {
    out[(i + 1) | 0] = arr[i]
  }
  return out
  }
} as any


export const concat: <A>(b: readonly A[]) => (a: readonly A[]) => A[] = function concat(b: any) {
  return function (a: any) {
    return a.concat(b)
  }
} as any


export const nthOrUndefined: (index: number) => <A>(arr: readonly A[]) => A | undefined = function nthOrUndefined(n: any) {
  return function (arr: any) {
    var i = n < 0 ? arr.length + n : n
  return i < 0 || i >= arr.length ? undefined : arr[i]
  }
} as any


export const nth: (index: number) => <A>(arr: readonly A[]) => Option<A> = function nth(n: any) {
  return function (arr: any) {
    var i = n < 0 ? arr.length + n : n
  return i < 0 || i >= arr.length ? optionNone : optionSome(arr[i])
  }
} as any


export const indexOfOrUndefined: <A>(value: A) => (arr: readonly A[]) => number | undefined = function indexOfOrUndefined(val: any) {
  return function (arr: any) {
    var i = arr.indexOf(val)
  return i === -1 ? undefined : i
  }
} as any


export const indexOf: <A>(value: A) => (arr: readonly A[]) => Option<number> = function indexOf(val: any) {
  return function (arr: any) {
    var i = arr.indexOf(val)
  return i === -1 ? optionNone : optionSome(i)
  }
} as any


export const lastIndexOfOrUndefined: <A>(value: A) => (arr: readonly A[]) => number | undefined = function lastIndexOfOrUndefined(val: any) {
  return function (arr: any) {
    var i = arr.lastIndexOf(val)
  return i === -1 ? undefined : i
  }
} as any


export const lastIndexOf: <A>(value: A) => (arr: readonly A[]) => Option<number> = function lastIndexOf(val: any) {
  return function (arr: any) {
    var i = arr.lastIndexOf(val)
  return i === -1 ? optionNone : optionSome(i)
  }
} as any


export const findLastOrUndefined: {
  <A, B extends A>(pred: (a: A) => a is B): (arr: readonly A[]) => B | undefined
  <A>(pred: (a: A) => boolean): (arr: readonly A[]) => A | undefined
} = function findLastOrUndefined(pred: any) {
  return function (arr: any) {
    for (var i = arr.length - 1; i >= 0; i--) {
    if (pred(arr[i])) return arr[i]
  }
  return undefined
  }
} as any


export const findLast: {
  <A, B extends A>(pred: (a: A) => a is B): (arr: readonly A[]) => Option<B>
  <A>(pred: (a: A) => boolean): (arr: readonly A[]) => Option<A>
} = function findLast(pred: any) {
  return function (arr: any) {
    for (var i = arr.length - 1; i >= 0; i--) {
    if (pred(arr[i])) return optionSome(arr[i])
  }
  return optionNone
  }
} as any


export const findLastIndexOrUndefined: <A>(pred: (a: A) => boolean) => (arr: readonly A[]) => number | undefined = function findLastIndexOrUndefined(pred: any) {
  return function (arr: any) {
    for (var i = arr.length - 1; i >= 0; i--) {
    if (pred(arr[i])) return i
  }
  return undefined
  }
} as any


export const findLastIndex: <A>(pred: (a: A) => boolean) => (arr: readonly A[]) => Option<number> = function findLastIndex(pred: any) {
  return function (arr: any) {
    for (var i = arr.length - 1; i >= 0; i--) {
    if (pred(arr[i])) return optionSome(i)
  }
  return optionNone
  }
} as any


const withoutCopyRaw = (arr: any): any[] => {
  const len = arr.length
  const result = new Array(len)
  for (let i = 0; i < len; ++i) result[i] = arr[i]
  return result
}

const without1Raw = (arr: any, v0: any): any[] => {
  const len = arr.length
  const result = new Array(len)
  let outputLength = 0
  const hasNaN = v0 !== v0
  for (let i = 0; i < len; ++i) {
    const x = arr[i]
    if (!(x !== x ? hasNaN : x === v0)) result[outputLength++] = x
  }
  result.length = outputLength
  return result
}

const without2Raw = (arr: any, v0: any, v1: any): any[] => {
  const len = arr.length
  const result = []
  const hasNaN = v0 !== v0 || v1 !== v1
  for (let i = 0; i < len; ++i) {
    const x = arr[i]
    if (!(x !== x ? hasNaN : x === v0 || x === v1)) result.push(x)
  }
  return result
}

const without3Raw = (arr: any, v0: any, v1: any, v2: any): any[] => {
  const len = arr.length
  const result = []
  const hasNaN = v0 !== v0 || v1 !== v1 || v2 !== v2
  for (let i = 0; i < len; ++i) {
    const x = arr[i]
    if (!(x !== x ? hasNaN : x === v0 || x === v1 || x === v2)) result.push(x)
  }
  return result
}

const without4Raw = (arr: any, v0: any, v1: any, v2: any, v3: any): any[] => {
  const len = arr.length
  const result = new Array(len)
  let outputLength = 0
  const hasNaN = v0 !== v0 || v1 !== v1 || v2 !== v2 || v3 !== v3
  for (let i = 0; i < len; ++i) {
    const x = arr[i]
    if (!(x !== x ? hasNaN : x === v0 || x === v1 || x === v2 || x === v3)) {
      result[outputLength++] = x
    }
  }
  result.length = outputLength
  return result
}

const without5Raw = (arr: any, v0: any, v1: any, v2: any, v3: any, v4: any): any[] => {
  const len = arr.length
  const result = new Array(len)
  let outputLength = 0
  const hasNaN = v0 !== v0 || v1 !== v1 || v2 !== v2 || v3 !== v3 || v4 !== v4
  for (let i = 0; i < len; ++i) {
    const x = arr[i]
    if (!(x !== x ? hasNaN : x === v0 || x === v1 || x === v2 || x === v3 || x === v4)) {
      result[outputLength++] = x
    }
  }
  result.length = outputLength
  return result
}

const without6Raw = (arr: any, v0: any, v1: any, v2: any, v3: any, v4: any, v5: any): any[] => {
  const len = arr.length
  const result = []
  const hasNaN = v0 !== v0 || v1 !== v1 || v2 !== v2 || v3 !== v3 || v4 !== v4 || v5 !== v5
  for (let i = 0; i < len; ++i) {
    const x = arr[i]
    if (
      !(x !== x ? hasNaN : x === v0 || x === v1 || x === v2 || x === v3 || x === v4 || x === v5)
    ) {
      result.push(x)
    }
  }
  return result
}

const without7Raw = (
  arr: any,
  v0: any,
  v1: any,
  v2: any,
  v3: any,
  v4: any,
  v5: any,
  v6: any,
): any[] => {
  const len = arr.length
  const result = []
  const hasNaN =
    v0 !== v0 || v1 !== v1 || v2 !== v2 || v3 !== v3 || v4 !== v4 || v5 !== v5 || v6 !== v6
  for (let i = 0; i < len; ++i) {
    const x = arr[i]
    if (
      !(x !== x
        ? hasNaN
        : x === v0 || x === v1 || x === v2 || x === v3 || x === v4 || x === v5 || x === v6)
    ) {
      result.push(x)
    }
  }
  return result
}

const without8Raw = (
  arr: any,
  v0: any,
  v1: any,
  v2: any,
  v3: any,
  v4: any,
  v5: any,
  v6: any,
  v7: any,
): any[] => {
  const len = arr.length
  const result = new Array(len)
  let outputLength = 0
  const hasNaN =
    v0 !== v0 ||
    v1 !== v1 ||
    v2 !== v2 ||
    v3 !== v3 ||
    v4 !== v4 ||
    v5 !== v5 ||
    v6 !== v6 ||
    v7 !== v7
  for (let i = 0; i < len; ++i) {
    const x = arr[i]
    if (
      !(x !== x
        ? hasNaN
        : x === v0 ||
          x === v1 ||
          x === v2 ||
          x === v3 ||
          x === v4 ||
          x === v5 ||
          x === v6 ||
          x === v7)
    ) {
      result[outputLength++] = x
    }
  }
  result.length = outputLength
  return result
}

const withoutLinearRaw = (arr: any, values: any): any[] => {
  const len = arr.length
  const valuesLength = values.length
  const result = []
  outer: for (let i = 0; i < len; ++i) {
    const x = arr[i]
    for (let j = 0; j < valuesLength; ++j) {
      if (sameValueZero(x, values[j])) continue outer
    }
    result.push(x)
  }
  return result
}

const withoutSetRaw = (arr: any, values: any): any[] => {
  const len = arr.length
  const exclude = new Set(values)
  const result = []
  for (let i = 0; i < len; ++i) {
    const x = arr[i]
    if (!exclude.has(x)) result.push(x)
  }
  return result
}

const withoutDispatchRaw = (arr: any, values: any): any[] => {
  const valuesLength = values.length
  // Once the source is moderately large, Set's SameValueZero lookup pays for
  // its construction above the fully unrolled small-exclusion kernels.
  if (arr.length >= 512 && valuesLength > 8) return withoutSetRaw(arr, values)
  switch (valuesLength) {
    case 0:
      return withoutCopyRaw(arr)
    case 1:
      return without1Raw(arr, values[0])
    case 2:
      return without2Raw(arr, values[0], values[1])
    case 3:
      return without3Raw(arr, values[0], values[1], values[2])
    case 4:
      return without4Raw(arr, values[0], values[1], values[2], values[3])
    case 5:
      return without5Raw(arr, values[0], values[1], values[2], values[3], values[4])
    case 6:
      return without6Raw(arr, values[0], values[1], values[2], values[3], values[4], values[5])
    case 7:
      return without7Raw(
        arr,
        values[0],
        values[1],
        values[2],
        values[3],
        values[4],
        values[5],
        values[6],
      )
    case 8:
      return without8Raw(
        arr,
        values[0],
        values[1],
        values[2],
        values[3],
        values[4],
        values[5],
        values[6],
        values[7],
      )
    default:
      return valuesLength <= 32 ? withoutLinearRaw(arr, values) : withoutSetRaw(arr, values)
  }
}

// values is a single array-valued argument here, not variadic. Both call
// styles share the same size-specialized dispatcher.
export const without: <A>(values: readonly A[]) => (arr: readonly A[]) => A[] = function without(_a0: any) {
  return function (data: any) {
    return withoutDispatchRaw(data, _a0)
  }
} as any


export const pluck: <K extends PropertyKey>(
    key: K,
  ) => <A extends Readonly<Record<K, unknown>>>(arr: readonly A[]) => A[K][] = function pluck(key: any) {
  return function (arr: any) {
    return pluckRaw(arr, key)
  }
} as any


export const dropRepeatsBy: <A, B>(f: (a: A) => B) => (arr: readonly A[]) => A[] = function dropRepeatsBy(f: any) {
  return function (arr: any) {
    const len = arr.length
  if (len === 0) return []
  const first = arr[0]
  const result = [first]
  let lastKey = f(first)
  for (let i = 1; i < len; i++) {
    const x = arr[i]
    const key = f(x)
    if (!structEq(key, lastKey)) {
      result.push(x)
      lastKey = key
    }
  }
  return result
  }
} as any


export const dropRepeatsWith: <A>(eq: (a: A, b: A) => boolean) => (arr: readonly A[]) => A[] = function dropRepeatsWith(eq: any) {
  return function (arr: any) {
    let len = arr.length
  if (len === 0) {
    return []
  }
  let result = [arr[0]]
  for (let i = 1; i < len; ++i) {
    let x = arr[i]
    if (!eq(arr[(i - 1) | 0], x)) {
      result.push(x)
    }
  }
  return result
  }
} as any


export const dropLast: (n: number) => <A>(arr: readonly A[]) => A[] = function dropLast(n: any) {
  return function (arr: any) {
    let len = arr.length
  if (n <= 0) {
    return arr.slice(0)
  }
  if (n >= len) {
    return []
  }
  let count = (len - n) | 0
  let out = new Array(count)
  for (let i = 0; i < count; ++i) {
    out[i] = arr[i]
  }
  return out
  }
} as any


export const dropLastWhile: <A>(pred: (a: A) => boolean) => (arr: readonly A[]) => A[] = function dropLastWhile(pred: any) {
  return function (arr: any) {
    let len = arr.length
  let i = (len - 1) | 0
  while (i >= 0 && pred(arr[i])) {
    i = (i - 1) | 0
  }
  let count = (i + 1) | 0
  if (count === len) {
    return arr.slice(0)
  }
  if (count <= 0) {
    return []
  }
  let out = new Array(count)
  for (let j = 0; j < count; ++j) {
    out[j] = arr[j]
  }
  return out
  }
} as any


export const takeLast: (n: number) => <A>(arr: readonly A[]) => A[] = function takeLast(n: any) {
  return function (arr: any) {
    let len = arr.length
  if (n <= 0) {
    return []
  }
  if (n >= len) {
    return arr.slice(0)
  }
  let start = (len - n) | 0
  let out = new Array(n)
  for (let i = 0; i < n; ++i) {
    out[i] = arr[(start + i) | 0]
  }
  return out
  }
} as any


export const takeLastWhile: <A>(pred: (a: A) => boolean) => (arr: readonly A[]) => A[] = function takeLastWhile(pred: any) {
  return function (arr: any) {
    let len = arr.length
  let i = (len - 1) | 0
  while (i >= 0 && pred(arr[i])) {
    i = (i - 1) | 0
  }
  let start = (i + 1) | 0
  let count = (len - start) | 0
  if (count <= 0) {
    return []
  }
  if (count === len) {
    return arr.slice(0)
  }
  let out = new Array(count)
  for (let j = 0; j < count; ++j) {
    out[j] = arr[(start + j) | 0]
  }
  return out
  }
} as any


export const splitAt: (index: number) => <A>(arr: readonly A[]) => [A[], A[]] = function splitAt(index: any) {
  return function (arr: any) {
    var i = index < 0 ? 0 : index > arr.length ? arr.length : index
  return [arr.slice(0, i), arr.slice(i)]
  }
} as any


export const splitWhen: <A>(pred: (a: A) => boolean) => (arr: readonly A[]) => [A[], A[]] = function splitWhen(pred: any) {
  return function (arr: any) {
    let len = arr.length
  let i = 0
  let found = false
  while (i < len && !found) {
    if (pred(arr[i])) {
      found = true
    } else {
      i = (i + 1) | 0
    }
  }
  return splitAt(i)(arr)
  }
} as any


export const splitWhenever: <A>(pred: (a: A) => boolean) => (arr: readonly A[]) => A[][] = function splitWhenever(pred: any) {
  return function (arr: any) {
    let len = arr.length
  if (len === 0) {
    return []
  }
  let result = []
  let current = []
  for (let i = 0; i < len; ++i) {
    let x = arr[i]
    if (pred(x)) {
      result.push(current.slice())
      current.splice(0, current.length)
    } else {
      current.push(x)
    }
  }
  result.push(current.slice())
  return result
  }
} as any


export const join: (sep: string) => (arr: readonly string[]) => string = function join(sep: any) {
  return function (arr: any) {
    return arr.join(sep)
  }
} as any


export const uniqWith: <A>(eq: (a: A, b: A) => boolean) => (arr: readonly A[]) => A[] = function uniqWith(eq: any) {
  return function (arr: any) {
    let result = []
  for (let i = 0, i_finish = arr.length; i < i_finish; ++i) {
    let x = arr[i]
    let dup = false
    let j = 0
    while (j < result.length && !dup) {
      if (eq(result[j], x)) {
        dup = true
      }
      j = (j + 1) | 0
    }
    if (!dup) {
      result.push(x)
    }
  }
  return result
  }
} as any


export const groupWith: <A>(eq: (a: A, b: A) => boolean) => (arr: readonly A[]) => A[][] = function groupWith(eq: any) {
  return function (arr: any) {
    let len = arr.length
  if (len === 0) {
    return []
  }
  let result = []
  let current = [arr[0]]
  for (let i = 1; i < len; ++i) {
    let x = arr[i]
    if (eq(arr[(i - 1) | 0], x)) {
      current.push(x)
    } else {
      result.push(current.slice())
      current.splice(0, current.length, x)
    }
  }
  result.push(current.slice())
  return result
  }
} as any


export const indexBy: <A>(f: (a: A) => string) => (arr: readonly A[]) => Dict<A> = function indexBy(f: any) {
  return function (arr: any) {
    let len = arr.length
  let dict: Dict<any> = {}
  for (let i = 0; i < len; ++i) {
    let x = arr[i]
    dict[f(x)] = x
  }
  return dict
  }
} as any


export const collectBy: <A>(f: (a: A) => string) => (arr: readonly A[]) => A[][] = function collectBy(f: any) {
  return function (arr: any) {
    let len = arr.length
  let dict: Dict<any[]> = {}
  let keys: string[] = []
  for (let i = 0; i < len; ++i) {
    let x = arr[i]
    let key = f(x)
    let group = dict[key]
    if (group !== undefined) {
      group.push(x)
    } else {
      dict[key] = [x]
      keys.push(key)
    }
  }
  let kLen = keys.length
  let out = new Array(kLen)
  for (let i$1 = 0; i$1 < kLen; ++i$1) {
    let group$1 = dict[keys[i$1]]
    if (group$1 !== undefined) {
      out[i$1] = group$1
    } else {
      out[i$1] = []
    }
  }
  return out
  }
} as any


export const sample: (n: number) => <A>(arr: readonly A[]) => A[] = function sample(n: any) {
  return function (arr: any) {
    return sampleRaw(arr, n)
  }
} as any


export const hasAtLeast: (n: number) => <A>(arr: readonly A[]) => boolean = function hasAtLeast(n: any) {
  return function (arr: any) {
    return arr.length >= n
  }
} as any


export const meanByOrUndefined: <A>(f: (a: A) => number) => (arr: readonly A[]) => number | undefined = function meanByOrUndefined(f: any) {
  return function (arr: any) {
    let len = arr.length
  if (len === 0) {
    return undefined
  }
  let acc = 0.0
  for (let i = 0; i < len; ++i) {
    acc = acc + f(arr[i])
  }
  return acc / len
  }
} as any


export const meanBy: <A>(f: (a: A) => number) => (arr: readonly A[]) => Option<number> = function meanBy(f: any) {
  return function (arr: any) {
    const value = meanByOrUndefined(f)(arr)
  return value === undefined ? optionNone : optionSome(value)
  }
} as any


export const meanByNonEmpty: <A>(f: (a: A) => number) => (arr: readonly [A, ...A[]]) => number = function meanByNonEmpty(f: any) {
  return function (arr: any) {
    return meanByOrUndefined(f)(arr) as number
  }
} as any


export const sumBy: <A>(f: (a: A) => number) => (arr: readonly A[]) => number = function sumBy(f: any) {
  return function (arr: any) {
    let len = arr.length
  let acc = 0.0
  for (let i = 0; i < len; ++i) {
    acc = acc + f(arr[i])
  }
  return acc
  }
} as any


export const mapToObj: <A, B>(f: (a: A) => [string, B]) => (arr: readonly A[]) => Dict<B> = function mapToObj(f: any) {
  return function (arr: any) {
    let len = arr.length
  let dict: Dict<any> = {}
  for (let i = 0; i < len; ++i) {
    let match = f(arr[i])
    dict[match[0]] = match[1]
  }
  return dict
  }
} as any


export const zipObj: <A>(values: readonly A[]) => (keys: readonly string[]) => Dict<A> = function zipObj(values: any) {
  return function (keys: any) {
    let lenK = keys.length
  let lenV = values.length
  let len = lenK < lenV ? lenK : lenV
  let dict: Dict<any> = {}
  for (let i = 0; i < len; ++i) {
    dict[keys[i]] = values[i]
  }
  return dict
  }
} as any


export const groupByProp: (prop: string) => <A>(arr: readonly A[]) => Dict<A[]> = function groupByProp(prop: any) {
  return function (arr: any) {
    return groupByPropRaw(arr, prop)
  }
} as any


export const arrayStartsWith: <A>(prefix: readonly A[]) => (arr: readonly A[]) => boolean = function arrayStartsWith(prefix: any) {
  return function (arr: any) {
    const lenA = arr.length
  const lenP = prefix.length
  if (lenP > lenA) return false
  for (let i = 0; i < lenP; i++) if (!structEq(arr[i], prefix[i])) return false
  return true
  }
} as any


export const arrayEndsWith: <A>(suffix: readonly A[]) => (arr: readonly A[]) => boolean = function arrayEndsWith(suffix: any) {
  return function (arr: any) {
    const lenA = arr.length
  const lenS = suffix.length
  if (lenS > lenA) return false
  const offset = lenA - lenS
  for (let i = 0; i < lenS; i++) if (!structEq(arr[offset + i], suffix[i])) return false
  return true
  }
} as any


export const sortedIndex: (value: number) => (arr: readonly number[]) => number = function sortedIndex(value: any) {
  return function (arr: any) {
    let lo = 0,
      hi = arr.length
    while (lo < hi) {
      const mid = (lo + hi) >> 1
      if (arr[mid] < value) lo = mid + 1
      else hi = mid
    }
    return lo
  }
} as any


export const sortedLastIndex: (value: number) => (arr: readonly number[]) => number = function sortedLastIndex(value: any) {
  return function (arr: any) {
    let lo = 0,
      hi = arr.length
    while (lo < hi) {
      const mid = (lo + hi) >> 1
      if (arr[mid] <= value) lo = mid + 1
      else hi = mid
    }
    return lo
  }
} as any


export const pair: <A, B>(a: A, b: B) => [A, B] = (a: any, b: any) => [a, b]

// Arity 3
export const withoutBy: <A>(values: readonly A[], f: (a: A) => string) => (arr: readonly A[]) => A[] = function withoutBy(values: any, f: any) {
  return function (arr: any) {
    let exclude = new Set()
  for (let i = 0, i_finish = values.length; i < i_finish; ++i) {
    exclude.add(f(values[i]))
  }
  let result = []
  for (let i$1 = 0, i_finish$1 = arr.length; i$1 < i_finish$1; ++i$1) {
    let x = arr[i$1]
    if (!exclude.has(f(x))) {
      result.push(x)
    }
  }
  return result
  }
} as any


export const slice: (start: number, end: number) => <A>(arr: readonly A[]) => A[] = function slice(start: any, end_: any) {
  return function (arr: any) {
    let len = arr.length
  let s = start < 0 ? (((len + start) | 0) > 0 ? (len + start) | 0 : 0) : start < len ? start : len
  let e = end_ < 0 ? (((len + end_) | 0) > 0 ? (len + end_) | 0 : 0) : end_ < len ? end_ : len
  if (s >= e) {
    return []
  }
  let count = (e - s) | 0
  let out = new Array(count)
  for (let i = 0; i < count; ++i) {
    out[i] = arr[(s + i) | 0]
  }
  return out
  }
} as any


export const swap: (i: number, j: number) => <A>(arr: readonly A[]) => A[] = function swap(i: any, j: any) {
  return function (arr: any) {
    let len = arr.length
  if (i < 0 || i >= len || j < 0 || j >= len) {
    return arr.slice(0)
  }
  let out = arr.slice(0)
  out[i] = arr[j]
  out[j] = arr[i]
  return out
  }
} as any


export const insertAll: <A>(index: number, values: readonly A[]) => (arr: readonly A[]) => A[] = function insertAll(index: any, values: any) {
  return function (arr: any) {
    let len = arr.length
  let vLen = values.length
  let idx = index < 0 ? 0 : index > len ? len : index
  let out = new Array((len + vLen) | 0)
  for (let i = 0; i < idx; ++i) {
    out[i] = arr[i]
  }
  for (let i$1 = 0; i$1 < vLen; ++i$1) {
    out[(idx + i$1) | 0] = values[i$1]
  }
  for (let i$2 = idx; i$2 < len; ++i$2) {
    out[(i$2 + vLen) | 0] = arr[i$2]
  }
  return out
  }
} as any


export const unionBy: <A>(b: readonly A[], f: (a: A) => string) => (a: readonly A[]) => A[] = function unionBy(b: any, f: any) {
  return function (a: any) {
    let seen = new Set()
  let result = []
  for (let i = 0, i_finish = a.length; i < i_finish; ++i) {
    let x = a[i]
    let k = f(x)
    if (!seen.has(k)) {
      seen.add(k)
      result.push(x)
    }
  }
  for (let i$1 = 0, i_finish$1 = b.length; i$1 < i_finish$1; ++i$1) {
    let x$1 = b[i$1]
    let k$1 = f(x$1)
    if (!seen.has(k$1)) {
      seen.add(k$1)
      result.push(x$1)
    }
  }
  return result
  }
} as any


export const unionWith: <A>(b: readonly A[], eq: (a: A, b: A) => boolean) => (a: readonly A[]) => A[] = function unionWith(b: any, eq: any) {
  return function (a: any) {
    let result: any[] = []
  let addIfNew = (x: any): void => {
    let dup = false
    let j = 0
    while (j < result.length && !dup) {
      if (eq(result[j], x)) {
        dup = true
      }
      j = (j + 1) | 0
    }
    if (!dup) {
      result.push(x)
      return
    }
  }
  for (let i = 0, i_finish = a.length; i < i_finish; ++i) {
    addIfNew(a[i])
  }
  for (let i$1 = 0, i_finish$1 = b.length; i$1 < i_finish$1; ++i$1) {
    addIfNew(b[i$1])
  }
  return result
  }
} as any


export const intersectionBy: <A>(b: readonly A[], f: (a: A) => string) => (a: readonly A[]) => A[] = function intersectionBy(b: any, f: any) {
  return function (a: any) {
    let setB = new Set()
  for (let i = 0, i_finish = b.length; i < i_finish; ++i) {
    setB.add(f(b[i]))
  }
  let seen = new Set()
  let result = []
  for (let i$1 = 0, i_finish$1 = a.length; i$1 < i_finish$1; ++i$1) {
    let x = a[i$1]
    let k = f(x)
    if (setB.has(k) && !seen.has(k)) {
      seen.add(k)
      result.push(x)
    }
  }
  return result
  }
} as any


export const differenceBy: <A>(b: readonly A[], f: (a: A) => string) => (a: readonly A[]) => A[] = function differenceBy(b: any, f: any) {
  return function (a: any) {
    let setB = new Set()
  for (let i = 0, i_finish = b.length; i < i_finish; ++i) {
    setB.add(f(b[i]))
  }
  let seen = new Set()
  let result = []
  for (let i$1 = 0, i_finish$1 = a.length; i$1 < i_finish$1; ++i$1) {
    let x = a[i$1]
    let k = f(x)
    if (!setB.has(k) && !seen.has(k)) {
      seen.add(k)
      result.push(x)
    }
  }
  return result
  }
} as any


export const differenceWith: <A>(b: readonly A[], eq: (a: A, b: A) => boolean) => (a: readonly A[]) => A[] = function differenceWith(b: any, eq: any) {
  return function (a: any) {
    let result = []
  for (let i = 0, i_finish = a.length; i < i_finish; ++i) {
    let x = a[i]
    let found = false
    let j = 0
    while (j < b.length && !found) {
      if (eq(x, b[j])) {
        found = true
      }
      j = (j + 1) | 0
    }
    if (!found) {
      result.push(x)
    }
  }
  return result
  }
} as any


export const symmetricDifferenceBy: <A>(b: readonly A[], f: (a: A) => string) => (a: readonly A[]) => A[] = function symmetricDifferenceBy(b: any, f: any) {
  return function (a: any) {
    let setA = new Set()
  let setB = new Set()
  for (let i = 0, i_finish = a.length; i < i_finish; ++i) {
    setA.add(f(a[i]))
  }
  for (let i$1 = 0, i_finish$1 = b.length; i$1 < i_finish$1; ++i$1) {
    setB.add(f(b[i$1]))
  }
  let seen = new Set()
  let result = []
  for (let i$2 = 0, i_finish$2 = a.length; i$2 < i_finish$2; ++i$2) {
    let x = a[i$2]
    let k = f(x)
    if (!setB.has(k) && !seen.has(k)) {
      seen.add(k)
      result.push(x)
    }
  }
  for (let i$3 = 0, i_finish$3 = b.length; i$3 < i_finish$3; ++i$3) {
    let x$1 = b[i$3]
    let k$1 = f(x$1)
    if (!setA.has(k$1) && !seen.has(k$1)) {
      seen.add(k$1)
      result.push(x$1)
    }
  }
  return result
  }
} as any


export const symmetricDifferenceWith: <A>(b: readonly A[], eq: (a: A, b: A) => boolean) => (a: readonly A[]) => A[] = function symmetricDifferenceWith(b: any, eq: any) {
  return function (a: any) {
    let result = []
  for (let i = 0, i_finish = a.length; i < i_finish; ++i) {
    let x = a[i]
    let found = false
    let j = 0
    while (j < b.length && !found) {
      if (eq(x, b[j])) {
        found = true
      }
      j = (j + 1) | 0
    }
    if (!found) {
      result.push(x)
    }
  }
  for (let i$1 = 0, i_finish$1 = b.length; i$1 < i_finish$1; ++i$1) {
    let x$1 = b[i$1]
    let found$1 = false
    let j$1 = 0
    while (j$1 < a.length && !found$1) {
      if (eq(x$1, a[j$1])) {
        found$1 = true
      }
      j$1 = (j$1 + 1) | 0
    }
    if (!found$1) {
      result.push(x$1)
    }
  }
  return result
  }
} as any


export const sortedIndexBy: <A>(value: A, f: (a: A) => number) => (arr: readonly A[]) => number = function sortedIndexBy(value: any, f: any) {
  return function (arr: any) {
    let target = f(value)
  let lo = 0
  let hi = arr.length
  while (lo < hi) {
    let mid = (((lo + hi) | 0) / 2) | 0
    if (f(arr[mid]) < target) {
      lo = (mid + 1) | 0
    } else {
      hi = mid
    }
  }
  return lo
  }
} as any


export const sortedIndexWith: <A>(pred: (a: A) => boolean) => (arr: readonly A[]) => number = function sortedIndexWith(pred: any) {
  return function (arr: any) {
    let lo = 0
  let hi = arr.length
  while (lo < hi) {
    let mid = (((lo + hi) | 0) / 2) | 0
    if (pred(arr[mid])) {
      hi = mid
    } else {
      lo = (mid + 1) | 0
    }
  }
  return lo
  }
} as any


export const sortedLastIndexBy: <A>(value: A, f: (a: A) => number) => (arr: readonly A[]) => number = function sortedLastIndexBy(value: any, f: any) {
  return function (arr: any) {
    let target = f(value)
  let lo = 0
  let hi = arr.length
  while (lo < hi) {
    let mid = (((lo + hi) | 0) / 2) | 0
    if (f(arr[mid]) <= target) {
      lo = (mid + 1) | 0
    } else {
      hi = mid
    }
  }
  return lo
  }
} as any


export const mapAccum: <A, B, C>(f: (acc: B, a: A) => [B, C], init: B) => (arr: readonly A[]) => [B, C[]] = function mapAccum(f: any, init: any) {
  return function (arr: any) {
    let len = arr.length
  let out = new Array(len)
  let acc = init
  for (let i = 0; i < len; ++i) {
    let match = f(acc, arr[i])
    acc = match[0]
    out[i] = match[1]
  }
  return [acc, out]
  }
} as any


export const mapAccumRight: <A, B, C>(f: (acc: B, a: A) => [B, C], init: B) => (arr: readonly A[]) => [B, C[]] = function mapAccumRight(f: any, init: any) {
  return function (arr: any) {
    let len = arr.length
  let out = new Array(len)
  let acc = init
  for (let i = 0; i < len; ++i) {
    let j = (((len - 1) | 0) - i) | 0
    let match = f(acc, arr[j])
    acc = match[0]
    out[j] = match[1]
  }
  return [acc, out]
  }
} as any


// Arity 4
export const reduceBy: <A, B>(
    keyFn: (a: A) => string,
    reducer: (acc: B, a: A) => B,
    init: B,
  ) => (arr: readonly A[]) => Dict<B> = function reduceBy(keyFn: any, reducer: any, init: any) {
  return function (arr: any) {
    const dict: Record<string, any> = {}
  for (let i = 0; i < arr.length; i++) {
    const x = arr[i]
    const key = keyFn(x)
    const acc = dict[key] !== undefined ? dict[key] : init
    dict[key] = reducer(acc, x)
  }
  return dict
  }
} as any


export const reduceWhile: <A, B>(pred: (acc: B, a: A) => boolean, f: (acc: B, a: A) => B, init: B) => (arr: readonly A[]) => B = function reduceWhile(pred: any, f: any, init: any) {
  return function (arr: any) {
    let len = arr.length
  let acc = init
  let i = 0
  let continue_ = true
  while (i < len && continue_) {
    let x = arr[i]
    if (pred(acc, x)) {
      acc = f(acc, x)
      i = (i + 1) | 0
    } else {
      continue_ = false
    }
  }
  return acc
  }
} as any


export const splice: <A>(start: number, deleteCount: number, items: readonly A[]) => (arr: readonly A[]) => A[] = function splice(start: any, deleteCount: any, items: any) {
  return function (arr: any) {
    let len = arr.length
  let s = start < 0 ? (((len + start) | 0) > 0 ? (len + start) | 0 : 0) : start < len ? start : len
  let dc = deleteCount < 0 ? 0 : ((s + deleteCount) | 0) > len ? (len - s) | 0 : deleteCount
  let itemsLen = items.length
  let newLen = (((len - dc) | 0) + itemsLen) | 0
  let out = new Array(newLen)
  for (let i = 0; i < s; ++i) {
    out[i] = arr[i]
  }
  for (let i$1 = 0; i$1 < itemsLen; ++i$1) {
    out[(s + i$1) | 0] = items[i$1]
  }
  for (let i$2 = (s + dc) | 0; i$2 < len; ++i$2) {
    out[(((s + itemsLen) | 0) + ((((i$2 - s) | 0) - dc) | 0)) | 0] = arr[i$2]
  }
  return out
  }
} as any



export * from './array-extra'
