// Generated by ReScript, PLEASE EDIT WITH CARE


function ifElse(cond, onTrue, onFalse) {
  if (cond) {
    return onTrue();
  } else {
    return onFalse();
  }
}

function and_(a, b) {
  if (a) {
    return b;
  } else {
    return false;
  }
}

function or_(a, b) {
  if (a) {
    return true;
  } else {
    return b;
  }
}

function not_(a) {
  return !a;
}

export {
  ifElse,
  and_,
  or_,
  not_,
}
/* No side effect */
