// Auto-generated by codegen/dual-inline.ts. Do not edit
// Source of truth: codegen/defs/


// Arity 1
export const not_: (a: boolean) => boolean = (a: any) => !a

// Arity 2
export const and_: {
  (a: boolean, b: boolean): boolean
  (b: boolean): (a: boolean) => boolean
} = function and_(a0: any, a1?: any): any {
  if (arguments.length >= 2) {
    const a = a0,
      b = a1
    if (a) {
    return b;
  } else {
    return false;
  }
  }
  const b = a0
  return function (a: any) {
    if (a) {
    return b;
  } else {
    return false;
  }
  }
} as any


export const or_: {
  (a: boolean, b: boolean): boolean
  (b: boolean): (a: boolean) => boolean
} = function or_(a0: any, a1?: any): any {
  if (arguments.length >= 2) {
    const a = a0,
      b = a1
    if (a) {
    return true;
  } else {
    return b;
  }
  }
  const b = a0
  return function (a: any) {
    if (a) {
    return true;
  } else {
    return b;
  }
  }
} as any


// Arity 3
export const ifElse: {
  <A>(cond: boolean, onTrue: () => A, onFalse: () => A): A
  <A>(onTrue: () => A, onFalse: () => A): (cond: boolean) => A
} = function ifElse(onTrue: any, onFalse?: any, __df?: any): any {
  if (arguments.length >= 3) return ifElse(onFalse, __df)(onTrue)
  return function (cond: any) {
    if (cond) {
    return onTrue();
  } else {
    return onFalse();
  }
  }
} as any

