// @ts-nocheck
// Auto-generated by codegen/dual-inline.ts. Do not edit
// Source of truth: codegen/defs/
import * as RS from './Boolean.gen'


// Arity 1
export const not_: (a: boolean) => boolean = RS.not_

// Arity 2
export const and_: {
  (a: boolean, b: boolean): boolean
  (b: boolean): (a: boolean) => boolean
} = function and_() {
  if (arguments.length >= 2) {
    const a = arguments[0], b = arguments[1]
    if (a) {
    return b;
  } else {
    return false;
  }
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const a = data, b = _a0
    if (a) {
    return b;
  } else {
    return false;
  }
  }
  return _dl
} as any


export const or_: {
  (a: boolean, b: boolean): boolean
  (b: boolean): (a: boolean) => boolean
} = function or_() {
  if (arguments.length >= 2) {
    const a = arguments[0], b = arguments[1]
    if (a) {
    return true;
  } else {
    return b;
  }
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const a = data, b = _a0
    if (a) {
    return true;
  } else {
    return b;
  }
  }
  return _dl
} as any


// Arity 3
export const ifElse: {
  <A>(cond: boolean, onTrue: () => A, onFalse: () => A): A
  <A>(onTrue: () => A, onFalse: () => A): (cond: boolean) => A
} = function ifElse() {
  if (arguments.length >= 3) {
    const cond = arguments[0], onTrue = arguments[1], onFalse = arguments[2]
    if (cond) {
    return onTrue();
  } else {
    return onFalse();
  }
  }
  const _a0 = arguments[0]; const _a1 = arguments[1]
  const _dl: any = function(data: any) {
    const cond = data, onTrue = _a0, onFalse = _a1
    if (cond) {
    return onTrue();
  } else {
    return onFalse();
  }
  }
  return _dl
} as any

