// @ts-nocheck
// Auto-generated by codegen/dual-inline.ts. Do not edit
// Source of truth: codegen/defs/


type Dict<A> = { [id: string]: A }

export const keys: <A>(d: Dict<A>) => string[] = Object.keys as any
export const values: <A>(d: Dict<A>) => A[] = Object.values as any
export const toEntries: <A>(d: Dict<A>) => [string, A][] = Object.entries as any
export function isEmpty<A>(d: Dict<A>): boolean { for (const _ in d) return false; return true }
export function fromEntries<A>(entries: [string, A][]): Dict<A> {
  const out: any = {}
  for (let i = 0, len = entries.length; i < len; i++) out[entries[i][0]] = entries[i][1]
  return out
}

export const map: {
  <A, B>(d: Dict<A>, f: (a: A, key: string) => B): Dict<B>
  <A, B>(f: (a: A, key: string) => B): (d: Dict<A>) => Dict<B>
} = function map() {
  if (arguments.length >= 2) {
    const d = arguments[0], f = arguments[1]
    const out: any = {}
  for (const k in d) out[k] = f(d[k], k)
  return out
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const d = data, f = _a0
    const out: any = {}
  for (const k in d) out[k] = f(d[k], k)
  return out
  }
  return _dl
} as any


export const filter: {
  <A>(d: Dict<A>, pred: (a: A, key: string) => boolean): Dict<A>
  <A>(pred: (a: A, key: string) => boolean): (d: Dict<A>) => Dict<A>
} = function filter() {
  if (arguments.length >= 2) {
    const d = arguments[0], pred = arguments[1]
    const out: any = {}
  for (const k in d) if (pred(d[k], k)) out[k] = d[k]
  return out
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const d = data, pred = _a0
    const out: any = {}
  for (const k in d) if (pred(d[k], k)) out[k] = d[k]
  return out
  }
  return _dl
} as any


export const get: {
  <A>(d: Dict<A>, key: string): A | undefined
  (key: string): <A>(d: Dict<A>) => A | undefined
} = function get() {
  if (arguments.length >= 2) {
    const d = arguments[0], key = arguments[1]
    return key in d ? d[key] : undefined
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const d = data, key = _a0
    return key in d ? d[key] : undefined
  }
  return _dl
} as any


export const merge: {
  <A>(a: Dict<A>, b: Dict<A>): Dict<A>
  <A>(b: Dict<A>): (a: Dict<A>) => Dict<A>
} = function merge() {
  if (arguments.length >= 2) {
    const a = arguments[0], b = arguments[1]
    const out: any = {}
  for (const k in a) out[k] = a[k]
  for (const k in b) out[k] = b[k]
  return out
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const a = data, b = _a0
    const out: any = {}
  for (const k in a) out[k] = a[k]
  for (const k in b) out[k] = b[k]
  return out
  }
  return _dl
} as any

