// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let assignRaw = (function(a, b) { return Object.assign({}, a, b) });

let hasRaw = (function(d, k) { return k in d });

function fromEntries(entries) {
  let out = {};
  for (let i = 0, i_finish = entries.length; i < i_finish; ++i) {
    let match = entries[i];
    out[match[0]] = match[1];
  }
  return out;
}

function toEntries(d) {
  let ks = Object.keys(d);
  let len = ks.length;
  let out = new Array(len);
  for (let i = 0; i < len; ++i) {
    let k = ks[i];
    out[i] = [
      k,
      d[k]
    ];
  }
  return out;
}

function keys(d) {
  return Object.keys(d);
}

function values(d) {
  return Object.values(d);
}

function map(d, f) {
  let ks = Object.keys(d);
  let out = {};
  for (let i = 0, i_finish = ks.length; i < i_finish; ++i) {
    let k = ks[i];
    out[k] = f(d[k], k);
  }
  return out;
}

function filter(d, pred) {
  let out = {};
  let ks = Object.keys(d);
  for (let i = 0, i_finish = ks.length; i < i_finish; ++i) {
    let k = ks[i];
    let v = d[k];
    if (pred(v, k)) {
      out[k] = v;
    }
  }
  return out;
}

function merge(a, b) {
  return assignRaw(a, b);
}

function get(d, key) {
  if (hasRaw(d, key)) {
    return Primitive_option.some(d[key]);
  }
}

function isEmpty(d) {
  return Object.keys(d).length === 0;
}

export {
  assignRaw,
  hasRaw,
  fromEntries,
  toEntries,
  keys,
  values,
  map,
  filter,
  merge,
  get,
  isEmpty,
}
/* No side effect */
