// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function identity(a) {
  return a;
}

function always(a) {
  return param => a;
}

function flip(fn) {
  return (b, a) => fn(a, b);
}

function complement(pred) {
  return a => !pred(a);
}

function once(fn) {
  let lastResult = {
    contents: undefined
  };
  return a => {
    let result = lastResult.contents;
    if (result !== undefined) {
      return Primitive_option.valFromOption(result);
    }
    let result$1 = fn(a);
    lastResult.contents = Primitive_option.some(result$1);
    return result$1;
  };
}

let memoize = once;

function converge(after, fns) {
  return a => after(fns.map(f => f(a)));
}

function juxt(fns) {
  return a => fns.map(f => f(a));
}

function t() {
  return true;
}

function f() {
  return false;
}

function tap(value, fn) {
  fn(value);
  return value;
}

function memoizeWith(keyFn, fn) {
  let cache = {};
  return a => {
    let key = keyFn(a);
    let result = cache[key];
    if (result !== undefined) {
      return Primitive_option.valFromOption(result);
    }
    let result$1 = fn(a);
    cache[key] = result$1;
    return result$1;
  };
}

function on(f, g) {
  return (a1, a2) => f(g(a1), g(a2));
}

function o(f, g) {
  return a => f(g(a));
}

function applyTo(value, fn) {
  return fn(value);
}

function ascend(fn) {
  return (a, b) => {
    let aa = fn(a);
    let bb = fn(b);
    if (aa < bb) {
      return -1;
    } else if (aa > bb) {
      return 1;
    } else {
      return 0;
    }
  };
}

function descend(fn) {
  return (a, b) => {
    let aa = fn(a);
    let bb = fn(b);
    if (aa > bb) {
      return -1;
    } else if (aa < bb) {
      return 1;
    } else {
      return 0;
    }
  };
}

function comparator(pred) {
  return (a, b) => {
    if (pred(a, b)) {
      return -1;
    } else if (pred(b, a)) {
      return 1;
    } else {
      return 0;
    }
  };
}

function doNothing(param) {
  
}

let tryCatchRaw = (function(tryer, catcher) {
    return function(a) { try { return tryer(a); } catch(e) { return catcher(e, a); } };
  });

function tryCatch(tryer, catcher) {
  return tryCatchRaw(tryer, catcher);
}

let thunkifyRaw = (function(fn) { return function(a) { return function() { return fn(a); }; }; });

function thunkify(fn) {
  return thunkifyRaw(fn);
}

let nthArgRaw = (function(n) { return function() { return arguments[n < 0 ? arguments.length + n : n]; }; });

function nthArg(n) {
  return nthArgRaw(n);
}

let nAryRaw = (function(n, fn) {
    switch (n) {
      case 0: return function() { return fn.apply(this, arguments); };
      case 1: return function(a) { return fn.apply(this, arguments); };
      case 2: return function(a, b) { return fn.apply(this, arguments); };
      case 3: return function(a, b, c) { return fn.apply(this, arguments); };
      default: return function() { return fn.apply(this, Array.prototype.slice.call(arguments, 0, n)); };
    }
  });

function nAry(n, fn) {
  return nAryRaw(n, fn);
}

function unary(fn) {
  return nAryRaw(1, fn);
}

function binary(fn) {
  return nAryRaw(2, fn);
}

let partialRaw = (function(fn, args) {
    return function() {
      return fn.apply(this, args.concat(Array.prototype.slice.call(arguments)));
    };
  });

function partial(fn, args) {
  return partialRaw(fn, args);
}

let partialRightRaw = (function(fn, args) {
    return function() {
      return fn.apply(this, Array.prototype.slice.call(arguments).concat(args));
    };
  });

function partialRight(fn, args) {
  return partialRightRaw(fn, args);
}

let partialObjectRaw = (function(fn, partial) {
    return function(obj) {
      return fn(Object.assign({}, partial, obj));
    };
  });

function partialObject(fn, partial) {
  return partialObjectRaw(fn, partial);
}

let applySpecRaw = (function applySpec(spec) {
    return function() {
      var args = arguments;
      function apply(s) {
        if (typeof s === 'function') return s.apply(null, args);
        if (Array.isArray(s)) return s.map(apply);
        if (typeof s === 'object' && s !== null) {
          var out = {};
          var keys = Object.keys(s);
          for (var i = 0; i < keys.length; i++) out[keys[i]] = apply(s[keys[i]]);
          return out;
        }
        return s;
      }
      return apply(spec);
    };
  });

function applySpec(spec) {
  return applySpecRaw(spec);
}

let useWithRaw = (function(fn, transformers) {
    return function() {
      var args = [];
      for (var i = 0; i < transformers.length; i++) {
        args.push(transformers[i](arguments[i]));
      }
      return fn.apply(null, args);
    };
  });

function useWith(fn, transformers) {
  return useWithRaw(fn, transformers);
}

let ascendNaturalRaw = (function(fn) {
    return function(a, b) { return fn(a).localeCompare(fn(b)); };
  });

function ascendNatural(fn) {
  return ascendNaturalRaw(fn);
}

let descendNaturalRaw = (function(fn) {
    return function(a, b) { return fn(b).localeCompare(fn(a)); };
  });

function descendNatural(fn) {
  return descendNaturalRaw(fn);
}

let andThenRaw = (function(p, fn) { return p.then(fn); });

function andThen(p, fn) {
  return andThenRaw(p, fn);
}

let otherwiseRaw = (function(p, fn) { return p.catch(fn); });

function otherwise(p, fn) {
  return otherwiseRaw(p, fn);
}

let unapplyRaw = (function(fn) { return function() { return fn(Array.prototype.slice.call(arguments)); }; });

function unapply(fn) {
  return unapplyRaw(fn);
}

export {
  identity,
  always,
  flip,
  complement,
  once,
  memoize,
  converge,
  juxt,
  t,
  f,
  tap,
  memoizeWith,
  on,
  o,
  applyTo,
  ascend,
  descend,
  comparator,
  doNothing,
  tryCatchRaw,
  tryCatch,
  thunkifyRaw,
  thunkify,
  nthArgRaw,
  nthArg,
  nAryRaw,
  nAry,
  unary,
  binary,
  partialRaw,
  partial,
  partialRightRaw,
  partialRight,
  partialObjectRaw,
  partialObject,
  applySpecRaw,
  applySpec,
  useWithRaw,
  useWith,
  ascendNaturalRaw,
  ascendNatural,
  descendNaturalRaw,
  descendNatural,
  andThenRaw,
  andThen,
  otherwiseRaw,
  otherwise,
  unapplyRaw,
  unapply,
}
/* No side effect */
