/**
 * GENERATED by codegen/iter-kernels.ts. Do not edit.
 *
 * One indexed Array loop per (terminal, shape) pair, with the terminal inlined
 * at the emission point so no value crosses a shared emit callback. Selection
 * is bounded: anything not in this table executes on the generic Iter path.
 */

import type { Option } from './option'

export const ITER_MAP = 0
export const ITER_FILTER = 1
export const ITER_FILTER_MAP = 2
export const ITER_FLAT_MAP = 3
export const ITER_TAKE = 4
export const ITER_DROP = 5
export const ITER_TAKE_WHILE = 6
export const ITER_DROP_WHILE = 7
export const ITER_SCAN = 8

export const ITER_TERMINAL_TO_ARRAY = 0
export const ITER_TERMINAL_TO_ARRAY_INTO = 1
export const ITER_TERMINAL_REDUCE = 2
export const ITER_TERMINAL_FIND = 3
export const ITER_TERMINAL_SOME = 4
export const ITER_TERMINAL_EVERY = 5
export const ITER_TERMINAL_COUNT = 6
export const ITER_TERMINAL_FOR_EACH = 7
export const ITER_TERMINAL_FIRST = 8
export const ITER_TERMINAL_LAST = 9
export const ITER_TERMINAL_NTH = 10

/**
 * The observable facts a kernel reads from a plan step. Kernels never read
 * fusion state, provenance, or operator identity.
 */
export interface IterKernelStep {
  readonly op: number
  readonly fn?: unknown
  readonly count?: number
  readonly initial?: unknown
}

/** Returned by a kernel whose terminal produced nothing. */
export const ITER_KERNEL_MISSING: unknown = Symbol('stopcock.iter.missing')

type KernelUnary = (value: unknown, index: number) => unknown
type KernelPredicate = (value: unknown, index: number) => boolean
type KernelReducer = (state: unknown, value: unknown, index: number) => unknown
type KernelEffect = (value: unknown, index: number) => void

export type IterArrayKernel = (
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a?: unknown,
  b?: unknown,
) => unknown

/**
 * Bounded positional encoding of a plan's op sequence. Shapes longer than three
 * stages are never admitted, so `-1` means "generic path".
 */
export const iterArrayShapeCode = (steps: readonly IterKernelStep[]): number => {
  const length = steps.length
  if (length === 0 || length > 3) return -1
  let code = 0
  for (let index = 0; index < length; index++) code = code * 16 + steps[index].op + 1
  return code
}

function kernel$map$toArray(source: readonly unknown[], steps: readonly IterKernelStep[]): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const out: unknown[] = []
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    out.push(value0)
  }
  return out
}

function kernel$filter$toArray(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
): unknown {
  const fn0 = steps[0].fn as KernelPredicate
  let index0 = 0
  const out: unknown[] = []
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    if (fn0(value, index0++)) {
      out.push(value)
    }
  }
  return out
}

function kernel$map$filter$toArray(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const fn1 = steps[1].fn as KernelPredicate
  let index1 = 0
  const out: unknown[] = []
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (fn1(value0, index1++)) {
      out.push(value0)
    }
  }
  return out
}

function kernel$map$filter$take$toArray(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const fn1 = steps[1].fn as KernelPredicate
  let index1 = 0
  const limit2 = steps[2].count as number
  let taken2 = 0
  const out: unknown[] = []
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (fn1(value0, index1++)) {
      if (taken2 >= limit2) break
      taken2++
      out.push(value0)
      if (taken2 >= limit2) break
    }
  }
  return out
}

function kernel$filterMap$take$toArray(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const limit1 = steps[1].count as number
  let taken1 = 0
  const out: unknown[] = []
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const option0 = fn0(value, index0++) as Option<unknown>
    if (option0._tag === 1) {
      const value0 = option0.value
      if (taken1 >= limit1) break
      taken1++
      out.push(value0)
      if (taken1 >= limit1) break
    }
  }
  return out
}

function kernel$map$toArrayInto(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const out = a as unknown[]
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    out.push(value0)
  }
  return out
}

function kernel$filter$toArrayInto(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelPredicate
  let index0 = 0
  const out = a as unknown[]
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    if (fn0(value, index0++)) {
      out.push(value)
    }
  }
  return out
}

function kernel$map$filter$toArrayInto(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const fn1 = steps[1].fn as KernelPredicate
  let index1 = 0
  const out = a as unknown[]
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (fn1(value0, index1++)) {
      out.push(value0)
    }
  }
  return out
}

function kernel$map$filter$take$toArrayInto(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const fn1 = steps[1].fn as KernelPredicate
  let index1 = 0
  const limit2 = steps[2].count as number
  let taken2 = 0
  const out = a as unknown[]
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (fn1(value0, index1++)) {
      if (taken2 >= limit2) break
      taken2++
      out.push(value0)
      if (taken2 >= limit2) break
    }
  }
  return out
}

function kernel$filterMap$take$toArrayInto(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const limit1 = steps[1].count as number
  let taken1 = 0
  const out = a as unknown[]
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const option0 = fn0(value, index0++) as Option<unknown>
    if (option0._tag === 1) {
      const value0 = option0.value
      if (taken1 >= limit1) break
      taken1++
      out.push(value0)
      if (taken1 >= limit1) break
    }
  }
  return out
}

function kernel$map$reduce(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
  b: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const reducer = a as KernelReducer
  let state = b
  let at = 0
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    state = reducer(state, value0, at++)
  }
  return state
}

function kernel$filter$reduce(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
  b: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelPredicate
  let index0 = 0
  const reducer = a as KernelReducer
  let state = b
  let at = 0
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    if (fn0(value, index0++)) {
      state = reducer(state, value, at++)
    }
  }
  return state
}

function kernel$map$filter$reduce(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
  b: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const fn1 = steps[1].fn as KernelPredicate
  let index1 = 0
  const reducer = a as KernelReducer
  let state = b
  let at = 0
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (fn1(value0, index1++)) {
      state = reducer(state, value0, at++)
    }
  }
  return state
}

function kernel$map$filter$take$reduce(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
  b: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const fn1 = steps[1].fn as KernelPredicate
  let index1 = 0
  const limit2 = steps[2].count as number
  let taken2 = 0
  const reducer = a as KernelReducer
  let state = b
  let at = 0
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (fn1(value0, index1++)) {
      if (taken2 >= limit2) break
      taken2++
      state = reducer(state, value0, at++)
      if (taken2 >= limit2) break
    }
  }
  return state
}

function kernel$filterMap$take$reduce(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
  b: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const limit1 = steps[1].count as number
  let taken1 = 0
  const reducer = a as KernelReducer
  let state = b
  let at = 0
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const option0 = fn0(value, index0++) as Option<unknown>
    if (option0._tag === 1) {
      const value0 = option0.value
      if (taken1 >= limit1) break
      taken1++
      state = reducer(state, value0, at++)
      if (taken1 >= limit1) break
    }
  }
  return state
}

function kernel$map$find(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const predicate = a as KernelPredicate
  let at = 0
  let result: unknown = ITER_KERNEL_MISSING
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (predicate(value0, at++)) {
      result = value0
      break
    }
  }
  return result
}

function kernel$filter$find(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelPredicate
  let index0 = 0
  const predicate = a as KernelPredicate
  let at = 0
  let result: unknown = ITER_KERNEL_MISSING
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    if (fn0(value, index0++)) {
      if (predicate(value, at++)) {
        result = value
        break
      }
    }
  }
  return result
}

function kernel$map$filter$find(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const fn1 = steps[1].fn as KernelPredicate
  let index1 = 0
  const predicate = a as KernelPredicate
  let at = 0
  let result: unknown = ITER_KERNEL_MISSING
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (fn1(value0, index1++)) {
      if (predicate(value0, at++)) {
        result = value0
        break
      }
    }
  }
  return result
}

function kernel$map$filter$take$find(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const fn1 = steps[1].fn as KernelPredicate
  let index1 = 0
  const limit2 = steps[2].count as number
  let taken2 = 0
  const predicate = a as KernelPredicate
  let at = 0
  let result: unknown = ITER_KERNEL_MISSING
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (fn1(value0, index1++)) {
      if (taken2 >= limit2) break
      taken2++
      if (predicate(value0, at++)) {
        result = value0
        break
      }
      if (taken2 >= limit2) break
    }
  }
  return result
}

function kernel$filterMap$take$find(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const limit1 = steps[1].count as number
  let taken1 = 0
  const predicate = a as KernelPredicate
  let at = 0
  let result: unknown = ITER_KERNEL_MISSING
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const option0 = fn0(value, index0++) as Option<unknown>
    if (option0._tag === 1) {
      const value0 = option0.value
      if (taken1 >= limit1) break
      taken1++
      if (predicate(value0, at++)) {
        result = value0
        break
      }
      if (taken1 >= limit1) break
    }
  }
  return result
}

function kernel$map$some(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const predicate = a as KernelPredicate
  let at = 0
  let result = false
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (predicate(value0, at++)) {
      result = true
      break
    }
  }
  return result
}

function kernel$filter$some(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelPredicate
  let index0 = 0
  const predicate = a as KernelPredicate
  let at = 0
  let result = false
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    if (fn0(value, index0++)) {
      if (predicate(value, at++)) {
        result = true
        break
      }
    }
  }
  return result
}

function kernel$map$filter$some(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const fn1 = steps[1].fn as KernelPredicate
  let index1 = 0
  const predicate = a as KernelPredicate
  let at = 0
  let result = false
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (fn1(value0, index1++)) {
      if (predicate(value0, at++)) {
        result = true
        break
      }
    }
  }
  return result
}

function kernel$map$filter$take$some(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const fn1 = steps[1].fn as KernelPredicate
  let index1 = 0
  const limit2 = steps[2].count as number
  let taken2 = 0
  const predicate = a as KernelPredicate
  let at = 0
  let result = false
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (fn1(value0, index1++)) {
      if (taken2 >= limit2) break
      taken2++
      if (predicate(value0, at++)) {
        result = true
        break
      }
      if (taken2 >= limit2) break
    }
  }
  return result
}

function kernel$filterMap$take$some(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const limit1 = steps[1].count as number
  let taken1 = 0
  const predicate = a as KernelPredicate
  let at = 0
  let result = false
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const option0 = fn0(value, index0++) as Option<unknown>
    if (option0._tag === 1) {
      const value0 = option0.value
      if (taken1 >= limit1) break
      taken1++
      if (predicate(value0, at++)) {
        result = true
        break
      }
      if (taken1 >= limit1) break
    }
  }
  return result
}

function kernel$map$every(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const predicate = a as KernelPredicate
  let at = 0
  let result = true
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (!predicate(value0, at++)) {
      result = false
      break
    }
  }
  return result
}

function kernel$filter$every(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelPredicate
  let index0 = 0
  const predicate = a as KernelPredicate
  let at = 0
  let result = true
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    if (fn0(value, index0++)) {
      if (!predicate(value, at++)) {
        result = false
        break
      }
    }
  }
  return result
}

function kernel$map$filter$every(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const fn1 = steps[1].fn as KernelPredicate
  let index1 = 0
  const predicate = a as KernelPredicate
  let at = 0
  let result = true
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (fn1(value0, index1++)) {
      if (!predicate(value0, at++)) {
        result = false
        break
      }
    }
  }
  return result
}

function kernel$map$filter$take$every(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const fn1 = steps[1].fn as KernelPredicate
  let index1 = 0
  const limit2 = steps[2].count as number
  let taken2 = 0
  const predicate = a as KernelPredicate
  let at = 0
  let result = true
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (fn1(value0, index1++)) {
      if (taken2 >= limit2) break
      taken2++
      if (!predicate(value0, at++)) {
        result = false
        break
      }
      if (taken2 >= limit2) break
    }
  }
  return result
}

function kernel$filterMap$take$every(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const limit1 = steps[1].count as number
  let taken1 = 0
  const predicate = a as KernelPredicate
  let at = 0
  let result = true
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const option0 = fn0(value, index0++) as Option<unknown>
    if (option0._tag === 1) {
      const value0 = option0.value
      if (taken1 >= limit1) break
      taken1++
      if (!predicate(value0, at++)) {
        result = false
        break
      }
      if (taken1 >= limit1) break
    }
  }
  return result
}

function kernel$map$count(source: readonly unknown[], steps: readonly IterKernelStep[]): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  let total = 0
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    total++
  }
  return total
}

function kernel$filter$count(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
): unknown {
  const fn0 = steps[0].fn as KernelPredicate
  let index0 = 0
  let total = 0
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    if (fn0(value, index0++)) {
      total++
    }
  }
  return total
}

function kernel$map$filter$count(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const fn1 = steps[1].fn as KernelPredicate
  let index1 = 0
  let total = 0
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (fn1(value0, index1++)) {
      total++
    }
  }
  return total
}

function kernel$map$filter$take$count(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const fn1 = steps[1].fn as KernelPredicate
  let index1 = 0
  const limit2 = steps[2].count as number
  let taken2 = 0
  let total = 0
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (fn1(value0, index1++)) {
      if (taken2 >= limit2) break
      taken2++
      total++
      if (taken2 >= limit2) break
    }
  }
  return total
}

function kernel$filterMap$take$count(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const limit1 = steps[1].count as number
  let taken1 = 0
  let total = 0
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const option0 = fn0(value, index0++) as Option<unknown>
    if (option0._tag === 1) {
      const value0 = option0.value
      if (taken1 >= limit1) break
      taken1++
      total++
      if (taken1 >= limit1) break
    }
  }
  return total
}

function kernel$map$forEach(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const effect = a as KernelEffect
  let at = 0
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    effect(value0, at++)
  }
  return undefined
}

function kernel$filter$forEach(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelPredicate
  let index0 = 0
  const effect = a as KernelEffect
  let at = 0
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    if (fn0(value, index0++)) {
      effect(value, at++)
    }
  }
  return undefined
}

function kernel$map$filter$forEach(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const fn1 = steps[1].fn as KernelPredicate
  let index1 = 0
  const effect = a as KernelEffect
  let at = 0
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (fn1(value0, index1++)) {
      effect(value0, at++)
    }
  }
  return undefined
}

function kernel$map$filter$take$forEach(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const fn1 = steps[1].fn as KernelPredicate
  let index1 = 0
  const limit2 = steps[2].count as number
  let taken2 = 0
  const effect = a as KernelEffect
  let at = 0
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (fn1(value0, index1++)) {
      if (taken2 >= limit2) break
      taken2++
      effect(value0, at++)
      if (taken2 >= limit2) break
    }
  }
  return undefined
}

function kernel$filterMap$take$forEach(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const limit1 = steps[1].count as number
  let taken1 = 0
  const effect = a as KernelEffect
  let at = 0
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const option0 = fn0(value, index0++) as Option<unknown>
    if (option0._tag === 1) {
      const value0 = option0.value
      if (taken1 >= limit1) break
      taken1++
      effect(value0, at++)
      if (taken1 >= limit1) break
    }
  }
  return undefined
}

function kernel$map$first(source: readonly unknown[], steps: readonly IterKernelStep[]): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  let result: unknown = ITER_KERNEL_MISSING
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    result = value0
    break
  }
  return result
}

function kernel$filter$first(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
): unknown {
  const fn0 = steps[0].fn as KernelPredicate
  let index0 = 0
  let result: unknown = ITER_KERNEL_MISSING
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    if (fn0(value, index0++)) {
      result = value
      break
    }
  }
  return result
}

function kernel$map$filter$first(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const fn1 = steps[1].fn as KernelPredicate
  let index1 = 0
  let result: unknown = ITER_KERNEL_MISSING
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (fn1(value0, index1++)) {
      result = value0
      break
    }
  }
  return result
}

function kernel$map$filter$take$first(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const fn1 = steps[1].fn as KernelPredicate
  let index1 = 0
  const limit2 = steps[2].count as number
  let taken2 = 0
  let result: unknown = ITER_KERNEL_MISSING
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (fn1(value0, index1++)) {
      if (taken2 >= limit2) break
      taken2++
      result = value0
      break
    }
  }
  return result
}

function kernel$filterMap$take$first(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const limit1 = steps[1].count as number
  let taken1 = 0
  let result: unknown = ITER_KERNEL_MISSING
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const option0 = fn0(value, index0++) as Option<unknown>
    if (option0._tag === 1) {
      const value0 = option0.value
      if (taken1 >= limit1) break
      taken1++
      result = value0
      break
    }
  }
  return result
}

function kernel$map$last(source: readonly unknown[], steps: readonly IterKernelStep[]): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  let result: unknown = ITER_KERNEL_MISSING
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    result = value0
  }
  return result
}

function kernel$filter$last(source: readonly unknown[], steps: readonly IterKernelStep[]): unknown {
  const fn0 = steps[0].fn as KernelPredicate
  let index0 = 0
  let result: unknown = ITER_KERNEL_MISSING
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    if (fn0(value, index0++)) {
      result = value
    }
  }
  return result
}

function kernel$map$filter$last(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const fn1 = steps[1].fn as KernelPredicate
  let index1 = 0
  let result: unknown = ITER_KERNEL_MISSING
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (fn1(value0, index1++)) {
      result = value0
    }
  }
  return result
}

function kernel$map$filter$take$last(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const fn1 = steps[1].fn as KernelPredicate
  let index1 = 0
  const limit2 = steps[2].count as number
  let taken2 = 0
  let result: unknown = ITER_KERNEL_MISSING
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (fn1(value0, index1++)) {
      if (taken2 >= limit2) break
      taken2++
      result = value0
      if (taken2 >= limit2) break
    }
  }
  return result
}

function kernel$filterMap$take$last(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const limit1 = steps[1].count as number
  let taken1 = 0
  let result: unknown = ITER_KERNEL_MISSING
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const option0 = fn0(value, index0++) as Option<unknown>
    if (option0._tag === 1) {
      const value0 = option0.value
      if (taken1 >= limit1) break
      taken1++
      result = value0
      if (taken1 >= limit1) break
    }
  }
  return result
}

function kernel$map$nth(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const wanted = a as number
  let at = 0
  let result: unknown = ITER_KERNEL_MISSING
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (at++ === wanted) {
      result = value0
      break
    }
  }
  return result
}

function kernel$filter$nth(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelPredicate
  let index0 = 0
  const wanted = a as number
  let at = 0
  let result: unknown = ITER_KERNEL_MISSING
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    if (fn0(value, index0++)) {
      if (at++ === wanted) {
        result = value
        break
      }
    }
  }
  return result
}

function kernel$map$filter$nth(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const fn1 = steps[1].fn as KernelPredicate
  let index1 = 0
  const wanted = a as number
  let at = 0
  let result: unknown = ITER_KERNEL_MISSING
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (fn1(value0, index1++)) {
      if (at++ === wanted) {
        result = value0
        break
      }
    }
  }
  return result
}

function kernel$map$filter$take$nth(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const fn1 = steps[1].fn as KernelPredicate
  let index1 = 0
  const limit2 = steps[2].count as number
  let taken2 = 0
  const wanted = a as number
  let at = 0
  let result: unknown = ITER_KERNEL_MISSING
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (fn1(value0, index1++)) {
      if (taken2 >= limit2) break
      taken2++
      if (at++ === wanted) {
        result = value0
        break
      }
      if (taken2 >= limit2) break
    }
  }
  return result
}

function kernel$filterMap$take$nth(
  source: readonly unknown[],
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const limit1 = steps[1].count as number
  let taken1 = 0
  const wanted = a as number
  let at = 0
  let result: unknown = ITER_KERNEL_MISSING
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const option0 = fn0(value, index0++) as Option<unknown>
    if (option0._tag === 1) {
      const value0 = option0.value
      if (taken1 >= limit1) break
      taken1++
      if (at++ === wanted) {
        result = value0
        break
      }
      if (taken1 >= limit1) break
    }
  }
  return result
}

const ARRAY_KERNELS = new Map<number, IterArrayKernel>([
  [16, kernel$map$toArray],
  [32, kernel$filter$toArray],
  [288, kernel$map$filter$toArray],
  [4688, kernel$map$filter$take$toArray],
  [848, kernel$filterMap$take$toArray],
  [17, kernel$map$toArrayInto],
  [33, kernel$filter$toArrayInto],
  [289, kernel$map$filter$toArrayInto],
  [4689, kernel$map$filter$take$toArrayInto],
  [849, kernel$filterMap$take$toArrayInto],
  [18, kernel$map$reduce],
  [34, kernel$filter$reduce],
  [290, kernel$map$filter$reduce],
  [4690, kernel$map$filter$take$reduce],
  [850, kernel$filterMap$take$reduce],
  [19, kernel$map$find],
  [35, kernel$filter$find],
  [291, kernel$map$filter$find],
  [4691, kernel$map$filter$take$find],
  [851, kernel$filterMap$take$find],
  [20, kernel$map$some],
  [36, kernel$filter$some],
  [292, kernel$map$filter$some],
  [4692, kernel$map$filter$take$some],
  [852, kernel$filterMap$take$some],
  [21, kernel$map$every],
  [37, kernel$filter$every],
  [293, kernel$map$filter$every],
  [4693, kernel$map$filter$take$every],
  [853, kernel$filterMap$take$every],
  [22, kernel$map$count],
  [38, kernel$filter$count],
  [294, kernel$map$filter$count],
  [4694, kernel$map$filter$take$count],
  [854, kernel$filterMap$take$count],
  [23, kernel$map$forEach],
  [39, kernel$filter$forEach],
  [295, kernel$map$filter$forEach],
  [4695, kernel$map$filter$take$forEach],
  [855, kernel$filterMap$take$forEach],
  [24, kernel$map$first],
  [40, kernel$filter$first],
  [296, kernel$map$filter$first],
  [4696, kernel$map$filter$take$first],
  [856, kernel$filterMap$take$first],
  [25, kernel$map$last],
  [41, kernel$filter$last],
  [297, kernel$map$filter$last],
  [4697, kernel$map$filter$take$last],
  [857, kernel$filterMap$take$last],
  [26, kernel$map$nth],
  [42, kernel$filter$nth],
  [298, kernel$map$filter$nth],
  [4698, kernel$map$filter$take$nth],
  [858, kernel$filterMap$take$nth],
])

export const iterArrayKernel = (shapeCode: number, terminal: number): IterArrayKernel | undefined =>
  shapeCode < 0 ? undefined : ARRAY_KERNELS.get(shapeCode * 16 + terminal)

export type IterViewKernel = (
  source: ArrayLike<unknown>,
  steps: readonly IterKernelStep[],
  a?: unknown,
  b?: unknown,
) => unknown

function viewKernel$map$toArray(
  source: ArrayLike<unknown>,
  steps: readonly IterKernelStep[],
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const out: unknown[] = []
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    out.push(value0)
  }
  return out
}

function viewKernel$filter$toArray(
  source: ArrayLike<unknown>,
  steps: readonly IterKernelStep[],
): unknown {
  const fn0 = steps[0].fn as KernelPredicate
  let index0 = 0
  const out: unknown[] = []
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    if (fn0(value, index0++)) {
      out.push(value)
    }
  }
  return out
}

function viewKernel$map$filter$toArray(
  source: ArrayLike<unknown>,
  steps: readonly IterKernelStep[],
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const fn1 = steps[1].fn as KernelPredicate
  let index1 = 0
  const out: unknown[] = []
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (fn1(value0, index1++)) {
      out.push(value0)
    }
  }
  return out
}

function viewKernel$map$toArrayInto(
  source: ArrayLike<unknown>,
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const out = a as unknown[]
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    out.push(value0)
  }
  return out
}

function viewKernel$filter$toArrayInto(
  source: ArrayLike<unknown>,
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelPredicate
  let index0 = 0
  const out = a as unknown[]
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    if (fn0(value, index0++)) {
      out.push(value)
    }
  }
  return out
}

function viewKernel$map$filter$toArrayInto(
  source: ArrayLike<unknown>,
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const fn1 = steps[1].fn as KernelPredicate
  let index1 = 0
  const out = a as unknown[]
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (fn1(value0, index1++)) {
      out.push(value0)
    }
  }
  return out
}

function viewKernel$map$reduce(
  source: ArrayLike<unknown>,
  steps: readonly IterKernelStep[],
  a: unknown,
  b: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const reducer = a as KernelReducer
  let state = b
  let at = 0
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    state = reducer(state, value0, at++)
  }
  return state
}

function viewKernel$filter$reduce(
  source: ArrayLike<unknown>,
  steps: readonly IterKernelStep[],
  a: unknown,
  b: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelPredicate
  let index0 = 0
  const reducer = a as KernelReducer
  let state = b
  let at = 0
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    if (fn0(value, index0++)) {
      state = reducer(state, value, at++)
    }
  }
  return state
}

function viewKernel$map$filter$reduce(
  source: ArrayLike<unknown>,
  steps: readonly IterKernelStep[],
  a: unknown,
  b: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const fn1 = steps[1].fn as KernelPredicate
  let index1 = 0
  const reducer = a as KernelReducer
  let state = b
  let at = 0
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (fn1(value0, index1++)) {
      state = reducer(state, value0, at++)
    }
  }
  return state
}

function viewKernel$map$count(
  source: ArrayLike<unknown>,
  steps: readonly IterKernelStep[],
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  let total = 0
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    total++
  }
  return total
}

function viewKernel$filter$count(
  source: ArrayLike<unknown>,
  steps: readonly IterKernelStep[],
): unknown {
  const fn0 = steps[0].fn as KernelPredicate
  let index0 = 0
  let total = 0
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    if (fn0(value, index0++)) {
      total++
    }
  }
  return total
}

function viewKernel$map$filter$count(
  source: ArrayLike<unknown>,
  steps: readonly IterKernelStep[],
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const fn1 = steps[1].fn as KernelPredicate
  let index1 = 0
  let total = 0
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (fn1(value0, index1++)) {
      total++
    }
  }
  return total
}

function viewKernel$map$forEach(
  source: ArrayLike<unknown>,
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const effect = a as KernelEffect
  let at = 0
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    effect(value0, at++)
  }
  return undefined
}

function viewKernel$filter$forEach(
  source: ArrayLike<unknown>,
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelPredicate
  let index0 = 0
  const effect = a as KernelEffect
  let at = 0
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    if (fn0(value, index0++)) {
      effect(value, at++)
    }
  }
  return undefined
}

function viewKernel$map$filter$forEach(
  source: ArrayLike<unknown>,
  steps: readonly IterKernelStep[],
  a: unknown,
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const fn1 = steps[1].fn as KernelPredicate
  let index1 = 0
  const effect = a as KernelEffect
  let at = 0
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (fn1(value0, index1++)) {
      effect(value0, at++)
    }
  }
  return undefined
}

function viewKernel$map$last(
  source: ArrayLike<unknown>,
  steps: readonly IterKernelStep[],
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  let result: unknown = ITER_KERNEL_MISSING
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    result = value0
  }
  return result
}

function viewKernel$filter$last(
  source: ArrayLike<unknown>,
  steps: readonly IterKernelStep[],
): unknown {
  const fn0 = steps[0].fn as KernelPredicate
  let index0 = 0
  let result: unknown = ITER_KERNEL_MISSING
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    if (fn0(value, index0++)) {
      result = value
    }
  }
  return result
}

function viewKernel$map$filter$last(
  source: ArrayLike<unknown>,
  steps: readonly IterKernelStep[],
): unknown {
  const fn0 = steps[0].fn as KernelUnary
  let index0 = 0
  const fn1 = steps[1].fn as KernelPredicate
  let index1 = 0
  let result: unknown = ITER_KERNEL_MISSING
  for (let cursor = 0; cursor < source.length; cursor++) {
    const value = source[cursor]
    const value0 = fn0(value, index0++)
    if (fn1(value0, index1++)) {
      result = value0
    }
  }
  return result
}

/**
 * Separate from ARRAY_KERNELS on purpose. The bodies are identical, but one
 * function that reads elements from both a plain Array and a view specialises
 * for neither, which measured a 0.53 geomean on the Array rows.
 */
const VIEW_KERNELS = new Map<number, IterViewKernel>([
  [16, viewKernel$map$toArray],
  [32, viewKernel$filter$toArray],
  [288, viewKernel$map$filter$toArray],
  [17, viewKernel$map$toArrayInto],
  [33, viewKernel$filter$toArrayInto],
  [289, viewKernel$map$filter$toArrayInto],
  [18, viewKernel$map$reduce],
  [34, viewKernel$filter$reduce],
  [290, viewKernel$map$filter$reduce],
  [22, viewKernel$map$count],
  [38, viewKernel$filter$count],
  [294, viewKernel$map$filter$count],
  [23, viewKernel$map$forEach],
  [39, viewKernel$filter$forEach],
  [295, viewKernel$map$filter$forEach],
  [25, viewKernel$map$last],
  [41, viewKernel$filter$last],
  [297, viewKernel$map$filter$last],
])

export const iterViewKernel = (shapeCode: number, terminal: number): IterViewKernel | undefined =>
  shapeCode < 0 ? undefined : VIEW_KERNELS.get(shapeCode * 16 + terminal)
