// Generated by ReScript, PLEASE EDIT WITH CARE


function lens(getter, setter) {
  return {
    get: getter,
    set: setter
  };
}

let lensIndexRaw = (function(n) {
    return {
      get: function(arr) { return arr[n]; },
      set: function(arr, val) { var out = arr.slice(); out[n] = val; return out; }
    };
  });

function lensIndex(n) {
  return lensIndexRaw(n);
}

let lensPathRaw = (function(path) {
    return {
      get: function(obj) {
        var cur = obj;
        for (var i = 0; i < path.length; i++) { if (cur == null) return undefined; cur = cur[path[i]]; }
        return cur;
      },
      set: function(obj, val) {
        if (path.length === 0) return val;
        function s(o, i) {
          var out = Array.isArray(o) ? o.slice() : Object.assign({}, o);
          if (i === path.length - 1) { out[path[i]] = val; return out; }
          out[path[i]] = s(out[path[i]] != null ? out[path[i]] : {}, i + 1);
          return out;
        }
        return s(obj, 0);
      }
    };
  });

function lensPath(path) {
  return lensPathRaw(path);
}

let lensPropRaw = (function(k) {
    return {
      get: function(obj) { return obj[k]; },
      set: function(obj, val) { var out = Object.assign({}, obj); out[k] = val; return out; }
    };
  });

function lensProp(key) {
  return lensPropRaw(key);
}

function view(l, obj) {
  return l.get(obj);
}

function set(l, val, obj) {
  return l.set(obj, val);
}

function over(l, fn, obj) {
  return l.set(obj, fn(l.get(obj)));
}

export {
  lens,
  lensIndexRaw,
  lensIndex,
  lensPathRaw,
  lensPath,
  lensPropRaw,
  lensProp,
  view,
  set,
  over,
}
/* No side effect */
