// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let equals = Primitive_object.equal;

function defaultTo(fallback, opt) {
  if (opt !== undefined) {
    return Primitive_option.valFromOption(opt);
  } else {
    return fallback;
  }
}

function when_(value, pred, f) {
  if (pred(value)) {
    return f(value);
  } else {
    return value;
  }
}

function unless(value, pred, f) {
  if (pred(value)) {
    return value;
  } else {
    return f(value);
  }
}

function cond(conditions, value) {
  let len = conditions.length;
  let i = 0;
  let result;
  while (i < len && result === undefined) {
    let match = conditions[i];
    if (match[0](value)) {
      result = Primitive_option.some(match[1](value));
    }
    i = i + 1 | 0;
  };
  return result;
}

function both(p1, p2) {
  return x => {
    if (p1(x)) {
      return p2(x);
    } else {
      return false;
    }
  };
}

function either(p1, p2) {
  return x => {
    if (p1(x)) {
      return true;
    } else {
      return p2(x);
    }
  };
}

function allPass(preds) {
  return x => {
    let len = preds.length;
    let i = 0;
    let ok = true;
    while (i < len && ok) {
      if (!preds[i](x)) {
        ok = false;
      }
      i = i + 1 | 0;
    };
    return ok;
  };
}

function anyPass(preds) {
  return x => {
    let len = preds.length;
    let i = 0;
    let found = false;
    while (i < len && !found) {
      if (preds[i](x)) {
        found = true;
      }
      i = i + 1 | 0;
    };
    return found;
  };
}

let logicIsEmptyRaw = (function(x) {
    if (x == null) return true;
    if (typeof x === 'string' || Array.isArray(x)) return x.length === 0;
    if (typeof x === 'object') return Object.keys(x).length === 0;
    return false;
  });

function logicIsEmpty(x) {
  return logicIsEmptyRaw(x);
}

function isNotEmpty(x) {
  return !logicIsEmptyRaw(x);
}

let pathSatisfiesRaw = (function(path, pred, obj) {
    let val = obj;
    for (let i = 0; i < path.length; i++) {
      if (val == null) return false;
      val = val[path[i]];
    }
    return pred(val);
  });

function pathSatisfies(path, pred, obj) {
  return pathSatisfiesRaw(path, pred, obj);
}

let propSatisfiesRaw = (function(prop, pred, obj) { return pred(obj[prop]); });

function propSatisfies(prop, pred, obj) {
  return propSatisfiesRaw(prop, pred, obj);
}

function until(value, pred, f) {
  let val = value;
  while (!pred(val)) {
    val = f(val);
  };
  return val;
}

function xor(a, b) {
  if (a && !b) {
    return true;
  } else if (a) {
    return false;
  } else {
    return b;
  }
}

export {
  equals,
  defaultTo,
  when_,
  unless,
  cond,
  both,
  either,
  allPass,
  anyPass,
  logicIsEmptyRaw,
  logicIsEmpty,
  isNotEmpty,
  pathSatisfiesRaw,
  pathSatisfies,
  propSatisfiesRaw,
  propSatisfies,
  until,
  xor,
}
/* No side effect */
