// @ts-nocheck
// Auto-generated by codegen/dual-inline.ts. Do not edit
// Source of truth: codegen/defs/
import * as RS from './Math.gen'


// Arity 1. Tagged for scalar JIT
export const inc: (n: number) => number = /* @__PURE__ */ (() => {
  const _f: any = function inc(n: any) { return n + 1.0; }
  _f._op = 75
  return _f
})()

export const dec: (n: number) => number = /* @__PURE__ */ (() => {
  const _f: any = function dec(n: any) { return n - 1.0; }
  _f._op = 76
  return _f
})()

export const negate: (n: number) => number = /* @__PURE__ */ (() => {
  const _f: any = function negate(n: any) { return - n; }
  _f._op = 74
  return _f
})()

export const product: (arr: number[]) => number = RS.product

// Arity 2. Tagged for scalar JIT (v=v+n, v=v*n, etc.)
export const add: {
  (a: number, b: number): number
  (b: number): (a: number) => number
} = function add() {
  if (arguments.length >= 2) {
    const a = arguments[0], b = arguments[1]
    return a + b;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const a = data, b = _a0
    return a + b;
  }
    _dl._op = 70
    _dl._fn = _a0
  return _dl
} as any


export const subtract: {
  (a: number, b: number): number
  (b: number): (a: number) => number
} = function subtract() {
  if (arguments.length >= 2) {
    const a = arguments[0], b = arguments[1]
    return a - b;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const a = data, b = _a0
    return a - b;
  }
    _dl._op = 71
    _dl._fn = _a0
  return _dl
} as any


export const multiply: {
  (a: number, b: number): number
  (b: number): (a: number) => number
} = function multiply() {
  if (arguments.length >= 2) {
    const a = arguments[0], b = arguments[1]
    return a * b;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const a = data, b = _a0
    return a * b;
  }
    _dl._op = 72
    _dl._fn = _a0
  return _dl
} as any


export const divide: {
  (a: number, b: number): number
  (b: number): (a: number) => number
} = function divide() {
  if (arguments.length >= 2) {
    const a = arguments[0], b = arguments[1]
    return a / b;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const a = data, b = _a0
    return a / b;
  }
    _dl._op = 73
    _dl._fn = _a0
  return _dl
} as any


export const modulo: {
  (a: number, b: number): number
  (b: number): (a: number) => number
} = function modulo() {
  if (arguments.length >= 2) {
    const a = arguments[0], b = arguments[1]
    return a % b;
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const a = data, b = _a0
    return a % b;
  }
  return _dl
} as any

