// Auto-generated by codegen/dual-inline.ts. Do not edit
// Source of truth: codegen/defs/


// Arity 1
export const inc: (n: number) => number = function inc(n: any) { return n + 1.0; } as any

export const dec: (n: number) => number = function dec(n: any) { return n - 1.0; } as any

export const negate: (n: number) => number = function negate(n: any) { return - n; } as any

export const product: (arr: number[]) => number = (arr: any) => {
  const len = arr.length
  let acc = 1.0
  for (let i = 0; i < len; i++) acc = acc * arr[i]
  return acc
}

// Arity 2
export const add: (b: number) => (a: number) => number = function add(b: any) {
  return function (a: any) {
    return a + b;
  }
} as any


export const subtract: (b: number) => (a: number) => number = function subtract(b: any) {
  return function (a: any) {
    return a - b;
  }
} as any


export const multiply: (b: number) => (a: number) => number = function multiply(b: any) {
  return function (a: any) {
    return a * b;
  }
} as any


export const divide: (b: number) => (a: number) => number = function divide(b: any) {
  return function (a: any) {
    return a / b;
  }
} as any


export const modulo: (b: number) => (a: number) => number = function modulo(b: any) {
  return function (a: any) {
    return a % b;
  }
} as any

