// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";
import * as Belt_SortArray from "@rescript/runtime/lib/es6/Belt_SortArray.js";

function add(a, b) {
  return a + b;
}

function subtract(a, b) {
  return a - b;
}

function multiply(a, b) {
  return a * b;
}

function divide(a, b) {
  return a / b;
}

function modulo(a, b) {
  return a % b;
}

function inc(n) {
  return n + 1.0;
}

function dec(n) {
  return n - 1.0;
}

function negate(n) {
  return - n;
}

function product(arr) {
  let len = arr.length;
  let acc = 1.0;
  for (let i = 0; i < len; ++i) {
    acc = acc * arr[i];
  }
  return acc;
}

function sum(arr) {
  let len = arr.length;
  let acc = 0.0;
  for (let i = 0; i < len; ++i) {
    acc = acc + arr[i];
  }
  return acc;
}

function mean(arr) {
  let len = arr.length;
  if (len === 0) {
    return 0.0;
  } else {
    return sum(arr) / len;
  }
}

function median(arr) {
  let len = arr.length;
  if (len === 0) {
    return 0.0;
  }
  let sorted = arr.slice(0);
  Belt_SortArray.stableSortInPlaceBy(sorted, (a, b) => {
    if (a < b) {
      return -1;
    } else if (a > b) {
      return 1;
    } else {
      return 0;
    }
  });
  let mid = len / 2 | 0;
  if (len % 2 === 0) {
    return (sorted[mid - 1 | 0] + sorted[mid]) / 2.0;
  } else {
    return sorted[mid];
  }
}

function mathMod(a, b) {
  if (b === 0) {
    return 0;
  }
  let r = Primitive_int.mod_(a, b);
  if (r < 0) {
    return r + (
      b < 0 ? -b | 0 : b
    ) | 0;
  } else {
    return r;
  }
}

export {
  add,
  subtract,
  multiply,
  divide,
  modulo,
  inc,
  dec,
  negate,
  product,
  sum,
  mean,
  median,
  mathMod,
}
/* No side effect */
