// Auto-generated by codegen/dual-inline.ts. Do not edit
// Source of truth: codegen/defs/

import { registerTrustedOperator } from './internal/provenance'


// Arity 1. Tagged for scalar JIT
export const inc: (n: number) => number = /* @__PURE__ */ (() => {
  const _f: any = function inc(n: any) { return n + 1.0; }
  _f._op = 75
  return registerTrustedOperator(_f, 75)
})()

export const dec: (n: number) => number = /* @__PURE__ */ (() => {
  const _f: any = function dec(n: any) { return n - 1.0; }
  _f._op = 76
  return registerTrustedOperator(_f, 76)
})()

export const negate: (n: number) => number = /* @__PURE__ */ (() => {
  const _f: any = function negate(n: any) { return - n; }
  _f._op = 74
  return registerTrustedOperator(_f, 74)
})()

export const product: (arr: number[]) => number = (arr: any) => {
  const len = arr.length
  let acc = 1.0
  for (let i = 0; i < len; i++) acc = acc * arr[i]
  return acc
}

// Arity 2. Tagged for scalar JIT (v=v+n, v=v*n, etc.)
export const add: {
  (a: number, b: number): number
  (b: number): (a: number) => number
} = function add(_arg0?: any, _arg1?: any) {
  if (arguments.length < 2) {
    const _a0 = _arg0
    const _dl: any = function(data: any) {
      const a = data, b = _a0
      return a + b;
    }
    _dl._op = 70
    _dl._fn = _a0
    return registerTrustedOperator(_dl, 70, _a0)
  }
  const a = _arg0, b = _arg1
  return a + b;
} as any


export const subtract: {
  (a: number, b: number): number
  (b: number): (a: number) => number
} = function subtract(_arg0?: any, _arg1?: any) {
  if (arguments.length < 2) {
    const _a0 = _arg0
    const _dl: any = function(data: any) {
      const a = data, b = _a0
      return a - b;
    }
    _dl._op = 71
    _dl._fn = _a0
    return registerTrustedOperator(_dl, 71, _a0)
  }
  const a = _arg0, b = _arg1
  return a - b;
} as any


export const multiply: {
  (a: number, b: number): number
  (b: number): (a: number) => number
} = function multiply(_arg0?: any, _arg1?: any) {
  if (arguments.length < 2) {
    const _a0 = _arg0
    const _dl: any = function(data: any) {
      const a = data, b = _a0
      return a * b;
    }
    _dl._op = 72
    _dl._fn = _a0
    return registerTrustedOperator(_dl, 72, _a0)
  }
  const a = _arg0, b = _arg1
  return a * b;
} as any


export const divide: {
  (a: number, b: number): number
  (b: number): (a: number) => number
} = function divide(_arg0?: any, _arg1?: any) {
  if (arguments.length < 2) {
    const _a0 = _arg0
    const _dl: any = function(data: any) {
      const a = data, b = _a0
      return a / b;
    }
    _dl._op = 73
    _dl._fn = _a0
    return registerTrustedOperator(_dl, 73, _a0)
  }
  const a = _arg0, b = _arg1
  return a / b;
} as any


export const modulo: {
  (a: number, b: number): number
  (b: number): (a: number) => number
} = function modulo(_arg0?: any, _arg1?: any) {
  if (arguments.length < 2) {
    const _a0 = _arg0
    const _dl: any = function(data: any) {
      const a = data, b = _a0
      return a % b;
    }
    return _dl
  }
  const a = _arg0, b = _arg1
  return a % b;
} as any

