// Generated by ReScript, PLEASE EDIT WITH CARE


function clamp(value, min, max) {
  let match = min > max ? [
      max,
      min
    ] : [
      min,
      max
    ];
  return Math.min(Math.max(value, match[0]), match[1]);
}

function isEven(n) {
  return n % 2 === 0;
}

function isOdd(n) {
  return n % 2 !== 0;
}

function ceil(n) {
  return Math.ceil(n);
}

function floor(n) {
  return Math.floor(n);
}

function round(n) {
  return Math.round(n);
}

export {
  clamp,
  isEven,
  isOdd,
  ceil,
  floor,
  round,
}
/* No side effect */
