// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let hasOwn = (function(o, k) { return Object.prototype.hasOwnProperty.call(o, k) });

let deleteKey = (function(o, k) { delete o[k] });

let isPlainObject = (function(v) { return typeof v === "object" && v !== null && !Array.isArray(v) });

let isFunction = (function(v) { return typeof v === "function" });

let toStr = (function(v) { return String(v) });

let isNullish = (function(v) { return v == null });

function emptyObj() {
  return {};
}

function pick(obj, ks) {
  let out = emptyObj();
  for (let i = 0, i_finish = ks.length; i < i_finish; ++i) {
    let k = ks[i];
    if (hasOwn(obj, k)) {
      out[k] = obj[k];
    }
  }
  return out;
}

let omit = (function(obj, ks) {
    var idx = {}, i = 0, len = ks.length;
    while (i < len) { idx[ks[i]] = 1; i++; }
    var out = {};
    for (var k in obj) {
      if (!idx.hasOwnProperty(k)) out[k] = obj[k];
    }
    return out;
  });

function assoc(obj, key, value) {
  let out = Object.assign(emptyObj(), obj);
  out[key] = value;
  return out;
}

function dissoc(obj, key) {
  let out = emptyObj();
  let allKeys = Object.keys(obj);
  for (let i = 0, i_finish = allKeys.length; i < i_finish; ++i) {
    let k = allKeys[i];
    if (k !== key) {
      out[k] = obj[k];
    }
  }
  return out;
}

function mergeDeep(left, right, leftWins) {
  let out = Object.assign(emptyObj(), left);
  let ks = Object.keys(right);
  for (let i = 0, i_finish = ks.length; i < i_finish; ++i) {
    let k = ks[i];
    let outV = out[k];
    let rightV = right[k];
    if (isPlainObject(outV) && isPlainObject(rightV)) {
      out[k] = mergeDeep(outV, rightV, leftWins);
    } else if (leftWins && hasOwn(out, k)) {
      
    } else {
      out[k] = rightV;
    }
  }
  return out;
}

function mergeDeepLeft(a, b) {
  return mergeDeep(a, b, true);
}

function mergeDeepRight(a, b) {
  return mergeDeep(a, b, false);
}

function mergeWith(a, b, resolver) {
  let out = Object.assign(emptyObj(), a);
  let ks = Object.keys(b);
  for (let i = 0, i_finish = ks.length; i < i_finish; ++i) {
    let k = ks[i];
    if (hasOwn(out, k)) {
      out[k] = resolver(out[k], b[k]);
    } else {
      out[k] = b[k];
    }
  }
  return out;
}

function assocPath(obj, p, value) {
  let len = p.length;
  if (len === 0) {
    return value;
  }
  let out = Object.assign(emptyObj(), obj);
  let k = p[0];
  if (len === 1) {
    out[k] = value;
  } else {
    let child = out[k];
    let next = isNullish(child) ? emptyObj() : child;
    out[k] = assocPath(next, p.slice(1), value);
  }
  return out;
}

function dissocPath(obj, p) {
  let len = p.length;
  if (len === 0) {
    return obj;
  }
  let out = Object.assign(emptyObj(), obj);
  let k = p[0];
  if (len === 1) {
    deleteKey(out, k);
  } else {
    let child = out[k];
    if (!isNullish(child)) {
      out[k] = dissocPath(child, p.slice(1));
    }
  }
  return out;
}

function clone(obj) {
  return structuredClone(obj);
}

function eqProps(key, a, b) {
  return a[key] === b[key];
}

function evolve(transformations, obj) {
  let out = Object.assign(emptyObj(), obj);
  let ks = Object.keys(transformations);
  for (let i = 0, i_finish = ks.length; i < i_finish; ++i) {
    let k = ks[i];
    if (hasOwn(out, k)) {
      let t = transformations[k];
      if (isFunction(t)) {
        out[k] = t(out[k]);
      } else if (isPlainObject(t) && isPlainObject(out[k])) {
        out[k] = evolve(t, out[k]);
      }
    }
  }
  return out;
}

function forEachObjIndexed(obj, fn) {
  let ks = Object.keys(obj);
  for (let i = 0, i_finish = ks.length; i < i_finish; ++i) {
    let k = ks[i];
    fn(obj[k], k);
  }
}

function has(obj, key) {
  return hasOwn(obj, key);
}

function hasPath(obj, p) {
  let len = p.length;
  let cur = obj;
  let ok = true;
  let i = 0;
  while (i < len && ok) {
    if (isNullish(cur) || !hasOwn(cur, p[i])) {
      ok = false;
    } else {
      cur = cur[p[i]];
      i = i + 1 | 0;
    }
  };
  return ok;
}

function invert(obj) {
  let out = emptyObj();
  let ks = Object.keys(obj);
  for (let i = 0, i_finish = ks.length; i < i_finish; ++i) {
    let k = ks[i];
    let v = toStr(obj[k]);
    let arr = out[v];
    if (arr !== undefined) {
      Primitive_option.valFromOption(arr).push(k);
    } else {
      out[v] = [k];
    }
  }
  return out;
}

function invertObj(obj) {
  let out = emptyObj();
  let ks = Object.keys(obj);
  for (let i = 0, i_finish = ks.length; i < i_finish; ++i) {
    let k = ks[i];
    out[toStr(obj[k])] = k;
  }
  return out;
}

function mapKeys(obj, fn) {
  let out = emptyObj();
  let ks = Object.keys(obj);
  for (let i = 0, i_finish = ks.length; i < i_finish; ++i) {
    let k = ks[i];
    out[fn(k)] = obj[k];
  }
  return out;
}

function mapObjIndexed(obj, fn) {
  let out = emptyObj();
  let ks = Object.keys(obj);
  for (let i = 0, i_finish = ks.length; i < i_finish; ++i) {
    let k = ks[i];
    out[k] = fn(obj[k], k);
  }
  return out;
}

function mergeDeepWith(a, b, fn) {
  let out = Object.assign(emptyObj(), a);
  let ks = Object.keys(b);
  for (let i = 0, i_finish = ks.length; i < i_finish; ++i) {
    let k = ks[i];
    let outV = out[k];
    let bV = b[k];
    if (isPlainObject(outV) && isPlainObject(bV)) {
      out[k] = mergeDeepWith(outV, bV, fn);
    } else if (hasOwn(out, k)) {
      out[k] = fn(outV, bV);
    } else {
      out[k] = bV;
    }
  }
  return out;
}

function mergeDeepWithKey(a, b, fn) {
  let out = Object.assign(emptyObj(), a);
  let ks = Object.keys(b);
  for (let i = 0, i_finish = ks.length; i < i_finish; ++i) {
    let k = ks[i];
    let outV = out[k];
    let bV = b[k];
    if (isPlainObject(outV) && isPlainObject(bV)) {
      out[k] = mergeDeepWithKey(outV, bV, fn);
    } else if (hasOwn(out, k)) {
      out[k] = fn(k, outV, bV);
    } else {
      out[k] = bV;
    }
  }
  return out;
}

function mergeLeft(a, b) {
  return Object.assign(emptyObj(), b, a);
}

function mergeRight(a, b) {
  return Object.assign(emptyObj(), a, b);
}

function mergeWithKey(a, b, fn) {
  let out = Object.assign(emptyObj(), a);
  let ks = Object.keys(b);
  for (let i = 0, i_finish = ks.length; i < i_finish; ++i) {
    let k = ks[i];
    if (hasOwn(out, k)) {
      out[k] = fn(k, out[k], b[k]);
    } else {
      out[k] = b[k];
    }
  }
  return out;
}

function modify(obj, key, fn) {
  let out = Object.assign(emptyObj(), obj);
  out[key] = fn(out[key]);
  return out;
}

function modifyPath(obj, p, fn) {
  let len = p.length;
  if (len === 0) {
    return fn(obj);
  }
  let out = Object.assign(emptyObj(), obj);
  let k = p[0];
  if (len === 1) {
    out[k] = fn(out[k]);
  } else {
    let child = out[k];
    let next = isNullish(child) ? emptyObj() : child;
    out[k] = modifyPath(next, p.slice(1), fn);
  }
  return out;
}

function objOf(key, value) {
  let out = emptyObj();
  out[key] = value;
  return out;
}

function path(obj, p) {
  let len = p.length;
  let cur = obj;
  let i = 0;
  while (i < len && !isNullish(cur)) {
    cur = cur[p[i]];
    i = i + 1 | 0;
  };
  return cur;
}

function pathOr(obj, fallback, p) {
  let len = p.length;
  let cur = obj;
  let i = 0;
  while (i < len && !isNullish(cur)) {
    cur = cur[p[i]];
    i = i + 1 | 0;
  };
  if (isNullish(cur)) {
    return fallback;
  } else {
    return cur;
  }
}

function paths(obj, ps) {
  let len = ps.length;
  let out = new Array(len);
  for (let i = 0; i < len; ++i) {
    let p = ps[i];
    let pLen = p.length;
    let cur = obj;
    let j = 0;
    while (j < pLen && !isNullish(cur)) {
      cur = cur[p[j]];
      j = j + 1 | 0;
    };
    out[i] = cur;
  }
  return out;
}

function pickAll(obj, ks) {
  let out = emptyObj();
  for (let i = 0, i_finish = ks.length; i < i_finish; ++i) {
    let k = ks[i];
    out[k] = obj[k];
  }
  return out;
}

function pickBy(obj, pred) {
  let out = emptyObj();
  let ks = Object.keys(obj);
  for (let i = 0, i_finish = ks.length; i < i_finish; ++i) {
    let k = ks[i];
    let v = obj[k];
    if (pred(v, k)) {
      out[k] = v;
    }
  }
  return out;
}

function project(arr, ks) {
  let len = arr.length;
  let kLen = ks.length;
  let out = new Array(len);
  for (let i = 0; i < len; ++i) {
    let item = arr[i];
    let o = emptyObj();
    for (let j = 0; j < kLen; ++j) {
      let k = ks[j];
      if (hasOwn(item, k)) {
        o[k] = item[k];
      }
    }
    out[i] = o;
  }
  return out;
}

function prop(obj, key) {
  return obj[key];
}

function propOr(obj, fallback, key) {
  let v = obj[key];
  if (isNullish(v)) {
    return fallback;
  } else {
    return v;
  }
}

function props(obj, ks) {
  let len = ks.length;
  let out = new Array(len);
  for (let i = 0; i < len; ++i) {
    out[i] = obj[ks[i]];
  }
  return out;
}

function renameKeys(obj, mapping) {
  let out = emptyObj();
  let ks = Object.keys(obj);
  for (let i = 0, i_finish = ks.length; i < i_finish; ++i) {
    let k = ks[i];
    let nk = mapping[k];
    let newKey = nk !== undefined ? Primitive_option.valFromOption(nk) : k;
    out[newKey] = obj[k];
  }
  return out;
}

function toPairs(obj) {
  let ks = Object.keys(obj);
  let len = ks.length;
  let out = new Array(len);
  for (let i = 0; i < len; ++i) {
    let k = ks[i];
    out[i] = [
      k,
      obj[k]
    ];
  }
  return out;
}

function unwind(obj, key) {
  let arr = obj[key];
  if (!Array.isArray(arr)) {
    return [obj];
  }
  let len = arr.length;
  let out = new Array(len);
  for (let i = 0; i < len; ++i) {
    let copy = Object.assign(emptyObj(), obj);
    copy[key] = arr[i];
    out[i] = copy;
  }
  return out;
}

function keys(obj) {
  return Object.keys(obj);
}

function values(obj) {
  let ks = Object.keys(obj);
  let len = ks.length;
  let out = new Array(len);
  for (let i = 0; i < len; ++i) {
    out[i] = obj[ks[i]];
  }
  return out;
}

function where(spec, obj) {
  let ks = Object.keys(spec);
  let len = ks.length;
  let ok = true;
  let i = 0;
  while (i < len && ok) {
    let k = ks[i];
    let predFn = spec[k];
    if (!predFn(obj[k])) {
      ok = false;
    }
    i = i + 1 | 0;
  };
  return ok;
}

function whereAny(spec, obj) {
  let ks = Object.keys(spec);
  let len = ks.length;
  let found = false;
  let i = 0;
  while (i < len && !found) {
    let k = ks[i];
    let predFn = spec[k];
    if (predFn(obj[k])) {
      found = true;
    }
    i = i + 1 | 0;
  };
  return found;
}

function whereEq(spec, obj) {
  let ks = Object.keys(spec);
  let len = ks.length;
  let ok = true;
  let i = 0;
  while (i < len && ok) {
    let k = ks[i];
    if (obj[k] !== spec[k]) {
      ok = false;
    }
    i = i + 1 | 0;
  };
  return ok;
}

function fromKeys(ks, value) {
  let out = emptyObj();
  for (let i = 0, i_finish = ks.length; i < i_finish; ++i) {
    out[ks[i]] = value;
  }
  return out;
}

function omitBy(obj, pred) {
  let out = emptyObj();
  let ks = Object.keys(obj);
  for (let i = 0, i_finish = ks.length; i < i_finish; ++i) {
    let k = ks[i];
    let v = obj[k];
    if (!pred(v, k)) {
      out[k] = v;
    }
  }
  return out;
}

function pullObject(arr, keyFn, valFn) {
  let out = emptyObj();
  for (let i = 0, i_finish = arr.length; i < i_finish; ++i) {
    let item = arr[i];
    out[keyFn(item)] = valFn(item);
  }
  return out;
}

function swapProps(obj, k1, k2) {
  let out = Object.assign(emptyObj(), obj);
  let tmp = out[k1];
  out[k1] = out[k2];
  out[k2] = tmp;
  return out;
}

export {
  hasOwn,
  deleteKey,
  isPlainObject,
  isFunction,
  toStr,
  isNullish,
  emptyObj,
  pick,
  omit,
  assoc,
  dissoc,
  mergeDeep,
  mergeDeepLeft,
  mergeDeepRight,
  mergeWith,
  assocPath,
  dissocPath,
  clone,
  eqProps,
  evolve,
  forEachObjIndexed,
  has,
  hasPath,
  invert,
  invertObj,
  mapKeys,
  mapObjIndexed,
  mergeDeepWith,
  mergeDeepWithKey,
  mergeLeft,
  mergeRight,
  mergeWithKey,
  modify,
  modifyPath,
  objOf,
  path,
  pathOr,
  paths,
  pickAll,
  pickBy,
  project,
  prop,
  propOr,
  props,
  renameKeys,
  toPairs,
  unwind,
  keys,
  values,
  where,
  whereAny,
  whereEq,
  fromKeys,
  omitBy,
  pullObject,
  swapProps,
}
/* No side effect */
