// GENERATED FILE -- do not edit by hand.
// Compatibility runtime projection of the canonical definition-only operator protocol.
// Legacy callback/capability fields preserve 1.x bytes and never authorize a semantic or backend.
// Source: packages/fp/codegen/protocol/operator-definitions.ts
// Semantic facts hash: sha256:3c94f27ddcb427d98989804b5302d521c4d4204564f2bcde91dc2f23db941b14
import * as OpCodes from './opcodes'
import { OP_CODES, OP_NON_FUSEABLE } from './opcodes'

export type OpCode = number
export type OpDomain = 'array' | 'scalar' | 'iterable'
export type OpCardinality =
  | 'one-to-one'
  | 'filtering'
  | 'expanding'
  | 'stateful'
  | 'sink'
  | 'materializer'
export type ArgBinding = 'fn' | 'a1' | 'a2'

export interface OpMeta {
  readonly op: OpCode
  readonly name: string
  readonly inputDomain: OpDomain
  readonly outputDomain: OpDomain
  readonly cardinality: OpCardinality
  readonly callbackArity: 0 | 1 | 2
  readonly bindings: readonly ArgBinding[]
  readonly earlyTermination: boolean
  readonly constructorPreserving: boolean
  readonly denseHoles: true
  readonly reverseSafe: boolean
  readonly exactLowering: true
  readonly pureLowering: boolean
  readonly simdEligible: boolean
  readonly workerEligible: boolean
  readonly isMaterializationBoundary: boolean
}

function meta(partial: {
  op: OpCode
  name: string
  inputDomain: OpDomain
  outputDomain: OpDomain
  cardinality: OpCardinality
  callbackArity: 0 | 1 | 2
  bindings: readonly ArgBinding[]
  earlyTermination?: boolean
  constructorPreserving?: boolean
  reverseSafe?: boolean
  pureLowering?: boolean
  simdEligible?: boolean
  workerEligible?: boolean
}): OpMeta {
  const cardinality = partial.cardinality
  return {
    op: partial.op,
    name: partial.name,
    inputDomain: partial.inputDomain,
    outputDomain: partial.outputDomain,
    cardinality,
    callbackArity: partial.callbackArity,
    bindings: partial.bindings,
    earlyTermination: partial.earlyTermination ?? false,
    constructorPreserving: partial.constructorPreserving ?? false,
    denseHoles: true,
    reverseSafe: partial.reverseSafe ?? cardinality !== 'stateful',
    exactLowering: true,
    pureLowering: partial.pureLowering ?? true,
    simdEligible: partial.simdEligible ?? false,
    workerEligible: partial.workerEligible ?? false,
    isMaterializationBoundary: cardinality === 'materializer' || cardinality === 'sink',
  }
}

const REGISTRY: ReadonlyMap<OpCode, OpMeta> = new Map(
  (
    [
      meta({
        op: OpCodes.OP_MAP,
        name: 'map',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'one-to-one',
        callbackArity: 1,
        bindings: ['fn'],
        constructorPreserving: true,
      }),
      meta({
        op: OpCodes.OP_FILTER,
        name: 'filter',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'filtering',
        callbackArity: 1,
        bindings: ['fn'],
        constructorPreserving: true,
      }),
      meta({
        op: OpCodes.OP_TAKE,
        name: 'take',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'stateful',
        callbackArity: 0,
        bindings: ['fn'],
        earlyTermination: true,
        constructorPreserving: true,
      }),
      meta({
        op: OpCodes.OP_DROP,
        name: 'drop',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'stateful',
        callbackArity: 0,
        bindings: ['fn'],
        constructorPreserving: true,
      }),
      meta({
        op: OpCodes.OP_TAKE_WHILE,
        name: 'takeWhile',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'stateful',
        callbackArity: 1,
        bindings: ['fn'],
        earlyTermination: true,
        constructorPreserving: true,
      }),
      meta({
        op: OpCodes.OP_DROP_WHILE,
        name: 'dropWhile',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'stateful',
        callbackArity: 1,
        bindings: ['fn'],
        constructorPreserving: true,
      }),
      meta({
        op: OpCodes.OP_FLAT_MAP,
        name: 'flatMap',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'expanding',
        callbackArity: 1,
        bindings: ['fn'],
        earlyTermination: true,
        reverseSafe: false,
      }),
      meta({
        op: OpCodes.OP_REDUCE,
        name: 'reduce',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'sink',
        callbackArity: 2,
        bindings: ['fn', 'a1'],
        reverseSafe: false,
        pureLowering: false,
      }),
      meta({
        op: OpCodes.OP_FOR_EACH,
        name: 'forEach',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'sink',
        callbackArity: 1,
        bindings: ['fn'],
        pureLowering: false,
      }),
      meta({
        op: OpCodes.OP_EVERY,
        name: 'every',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'sink',
        callbackArity: 1,
        bindings: ['fn'],
        earlyTermination: true,
      }),
      meta({
        op: OpCodes.OP_SOME,
        name: 'some',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'sink',
        callbackArity: 1,
        bindings: ['fn'],
        earlyTermination: true,
      }),
      meta({
        op: OpCodes.OP_FIND,
        name: 'find',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'sink',
        callbackArity: 1,
        bindings: ['fn'],
        earlyTermination: true,
      }),
      meta({
        op: OpCodes.OP_FIND_INDEX,
        name: 'findIndex',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'sink',
        callbackArity: 1,
        bindings: ['fn'],
        earlyTermination: true,
        reverseSafe: false,
      }),
      meta({
        op: OpCodes.OP_FILTER_MAP,
        name: 'filterMap',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'filtering',
        callbackArity: 1,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_MAP_WHILE,
        name: 'mapWhile',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'stateful',
        callbackArity: 1,
        bindings: ['fn'],
        earlyTermination: true,
      }),
      meta({
        op: OpCodes.OP_REJECT,
        name: 'reject',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'filtering',
        callbackArity: 1,
        bindings: ['fn'],
        constructorPreserving: true,
      }),
      meta({
        op: OpCodes.OP_TAKE_UNTIL,
        name: 'takeUntil',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'stateful',
        callbackArity: 1,
        bindings: ['fn'],
        earlyTermination: true,
      }),
      meta({
        op: OpCodes.OP_NONE,
        name: 'none',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'sink',
        callbackArity: 1,
        bindings: ['fn'],
        earlyTermination: true,
      }),
      meta({
        op: OpCodes.OP_COUNT,
        name: 'count',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'sink',
        callbackArity: 1,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_FIND_MAP,
        name: 'findMap',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'sink',
        callbackArity: 1,
        bindings: ['fn'],
        earlyTermination: true,
        reverseSafe: false,
      }),
      meta({
        op: OpCodes.OP_SORT_BY,
        name: 'sortBy',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 1,
        bindings: ['fn'],
        constructorPreserving: true,
        pureLowering: true,
      }),
      meta({
        op: OpCodes.OP_SORT,
        name: 'sort',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: [],
        constructorPreserving: true,
      }),
      meta({
        op: OpCodes.OP_HEAD,
        name: 'head',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_LAST,
        name: 'last',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_LENGTH,
        name: 'length',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_IS_EMPTY,
        name: 'isEmpty',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_TAIL,
        name: 'tail',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: [],
        constructorPreserving: true,
      }),
      meta({
        op: OpCodes.OP_INIT,
        name: 'init',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: [],
        constructorPreserving: true,
      }),
      meta({
        op: OpCodes.OP_REVERSE,
        name: 'reverse',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: [],
        constructorPreserving: true,
      }),
      meta({
        op: OpCodes.OP_SORT_INLINE,
        name: 'sortInline',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 1,
        bindings: ['fn'],
        constructorPreserving: true,
      }),
      meta({
        op: OpCodes.OP_UNIQ_INLINE,
        name: 'uniq',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_JOIN,
        name: 'join',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['a1'],
      }),
      meta({
        op: OpCodes.OP_FLATTEN,
        name: 'flatten',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_SUM,
        name: 'sum',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: [],
        simdEligible: true,
        workerEligible: true,
      }),
      meta({
        op: OpCodes.OP_MIN,
        name: 'min',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: [],
        simdEligible: true,
        workerEligible: true,
      }),
      meta({
        op: OpCodes.OP_MAX,
        name: 'max',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: [],
        simdEligible: true,
        workerEligible: true,
      }),
      meta({
        op: OpCodes.OP_STR_TRIM,
        name: 'trim',
        inputDomain: 'scalar',
        outputDomain: 'scalar',
        cardinality: 'one-to-one',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_STR_LOWER,
        name: 'toLowerCase',
        inputDomain: 'scalar',
        outputDomain: 'scalar',
        cardinality: 'one-to-one',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_STR_UPPER,
        name: 'toUpperCase',
        inputDomain: 'scalar',
        outputDomain: 'scalar',
        cardinality: 'one-to-one',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_STR_TRIM_START,
        name: 'trimStart',
        inputDomain: 'scalar',
        outputDomain: 'scalar',
        cardinality: 'one-to-one',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_STR_TRIM_END,
        name: 'trimEnd',
        inputDomain: 'scalar',
        outputDomain: 'scalar',
        cardinality: 'one-to-one',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_STR_SPLIT,
        name: 'split',
        inputDomain: 'scalar',
        outputDomain: 'array',
        cardinality: 'one-to-one',
        callbackArity: 0,
        bindings: ['a1'],
      }),
      meta({
        op: OpCodes.OP_STR_LENGTH,
        name: 'strLength',
        inputDomain: 'scalar',
        outputDomain: 'scalar',
        cardinality: 'one-to-one',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_STR_IS_EMPTY,
        name: 'strIsEmpty',
        inputDomain: 'scalar',
        outputDomain: 'scalar',
        cardinality: 'one-to-one',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_DICT_KEYS,
        name: 'keys',
        inputDomain: 'scalar',
        outputDomain: 'array',
        cardinality: 'one-to-one',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_DICT_VALUES,
        name: 'values',
        inputDomain: 'scalar',
        outputDomain: 'array',
        cardinality: 'one-to-one',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_DICT_IS_EMPTY,
        name: 'dictIsEmpty',
        inputDomain: 'scalar',
        outputDomain: 'scalar',
        cardinality: 'one-to-one',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_MATH_ADD,
        name: 'add',
        inputDomain: 'scalar',
        outputDomain: 'scalar',
        cardinality: 'one-to-one',
        callbackArity: 0,
        bindings: ['a1'],
        simdEligible: true,
        workerEligible: true,
      }),
      meta({
        op: OpCodes.OP_MATH_SUBTRACT,
        name: 'subtract',
        inputDomain: 'scalar',
        outputDomain: 'scalar',
        cardinality: 'one-to-one',
        callbackArity: 0,
        bindings: ['a1'],
        simdEligible: true,
        workerEligible: true,
      }),
      meta({
        op: OpCodes.OP_MATH_MULTIPLY,
        name: 'multiply',
        inputDomain: 'scalar',
        outputDomain: 'scalar',
        cardinality: 'one-to-one',
        callbackArity: 0,
        bindings: ['a1'],
        simdEligible: true,
        workerEligible: true,
      }),
      meta({
        op: OpCodes.OP_MATH_DIVIDE,
        name: 'divide',
        inputDomain: 'scalar',
        outputDomain: 'scalar',
        cardinality: 'one-to-one',
        callbackArity: 0,
        bindings: ['a1'],
        simdEligible: true,
        workerEligible: true,
      }),
      meta({
        op: OpCodes.OP_MATH_NEGATE,
        name: 'negate',
        inputDomain: 'scalar',
        outputDomain: 'scalar',
        cardinality: 'one-to-one',
        callbackArity: 0,
        bindings: [],
        simdEligible: true,
        workerEligible: true,
      }),
      meta({
        op: OpCodes.OP_MATH_INC,
        name: 'inc',
        inputDomain: 'scalar',
        outputDomain: 'scalar',
        cardinality: 'one-to-one',
        callbackArity: 0,
        bindings: [],
        simdEligible: true,
        workerEligible: true,
      }),
      meta({
        op: OpCodes.OP_MATH_DEC,
        name: 'dec',
        inputDomain: 'scalar',
        outputDomain: 'scalar',
        cardinality: 'one-to-one',
        callbackArity: 0,
        bindings: [],
        simdEligible: true,
        workerEligible: true,
      }),
      meta({
        op: OpCodes.OP_GUARD_IS_NUMBER,
        name: 'isNumber',
        inputDomain: 'scalar',
        outputDomain: 'scalar',
        cardinality: 'one-to-one',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_GUARD_IS_STRING,
        name: 'isString',
        inputDomain: 'scalar',
        outputDomain: 'scalar',
        cardinality: 'one-to-one',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_GUARD_IS_BOOLEAN,
        name: 'isBoolean',
        inputDomain: 'scalar',
        outputDomain: 'scalar',
        cardinality: 'one-to-one',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_GUARD_IS_NIL,
        name: 'isNil',
        inputDomain: 'scalar',
        outputDomain: 'scalar',
        cardinality: 'one-to-one',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_GUARD_IS_ARRAY,
        name: 'isArray',
        inputDomain: 'scalar',
        outputDomain: 'scalar',
        cardinality: 'one-to-one',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_GUARD_IS_OBJECT,
        name: 'isObject',
        inputDomain: 'scalar',
        outputDomain: 'scalar',
        cardinality: 'one-to-one',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_GUARD_IS_FUNCTION,
        name: 'isFunction',
        inputDomain: 'scalar',
        outputDomain: 'scalar',
        cardinality: 'one-to-one',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_SORT_ASC,
        name: 'sortAsc',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_SORT_DESC,
        name: 'sortDesc',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_SCAN,
        name: 'scan',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'stateful',
        callbackArity: 2,
        bindings: ['fn', 'a1'],
        reverseSafe: false,
      }),
      meta({
        op: OpCodes.OP_WITHOUT,
        name: 'without',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
        constructorPreserving: false,
      }),
      meta({
        op: OpCodes.OP_DROP_REPEATS,
        name: 'dropRepeats',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_CHUNK,
        name: 'chunk',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_SLIDING_WINDOW,
        name: 'slidingWindow',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_APERTURE,
        name: 'aperture',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_INTERSPERSE,
        name: 'intersperse',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_UNIQ_BY,
        name: 'uniqBy',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 1,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_GROUP_BY,
        name: 'groupBy',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 1,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_PARTITION,
        name: 'partition',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 1,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_ZIP,
        name: 'zip',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_ZIP_WITH,
        name: 'zipWith',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn', 'a1'],
      }),
      meta({
        op: OpCodes.OP_XPROD,
        name: 'xprod',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_INTERSECTION,
        name: 'intersection',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_UNION,
        name: 'union',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_DIFFERENCE,
        name: 'difference',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_SYMMETRIC_DIFFERENCE,
        name: 'symmetricDifference',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_ADJUST,
        name: 'adjust',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn', 'a1'],
      }),
      meta({
        op: OpCodes.OP_UPDATE,
        name: 'update',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn', 'a1'],
      }),
      meta({
        op: OpCodes.OP_INSERT,
        name: 'insert',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn', 'a1'],
      }),
      meta({
        op: OpCodes.OP_REMOVE,
        name: 'remove',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn', 'a1'],
      }),
      meta({
        op: OpCodes.OP_INCLUDES,
        name: 'includes',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_FIND_OR_UNDEFINED,
        name: 'findOrUndefined',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 1,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_FIND_INDEX_OR_UNDEFINED,
        name: 'findIndexOrUndefined',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 1,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_FIND_MAP_OR_UNDEFINED,
        name: 'findMapOrUndefined',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 1,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_PLUCK,
        name: 'pluck',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_DROP_LAST,
        name: 'dropLast',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_TAKE_LAST,
        name: 'takeLast',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_DROP_LAST_WHILE,
        name: 'dropLastWhile',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 1,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_TAKE_LAST_WHILE,
        name: 'takeLastWhile',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 1,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_APPEND,
        name: 'append',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_PREPEND,
        name: 'prepend',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_INDEX_OF,
        name: 'indexOf',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_LAST_INDEX_OF,
        name: 'lastIndexOf',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_FIND_LAST,
        name: 'findLast',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 1,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_FIND_LAST_INDEX,
        name: 'findLastIndex',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 1,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_REDUCE_RIGHT,
        name: 'reduceRight',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 2,
        bindings: ['fn', 'a1'],
      }),
      meta({
        op: OpCodes.OP_REDUCE_WHILE,
        name: 'reduceWhile',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 2,
        bindings: ['fn', 'a1', 'a2'],
      }),
      meta({
        op: OpCodes.OP_SUM_BY,
        name: 'sumBy',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 1,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_MEAN_BY,
        name: 'meanBy',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 1,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_HAS_AT_LEAST,
        name: 'hasAtLeast',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_ARRAY_STARTS_WITH,
        name: 'arrayStartsWith',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_ARRAY_ENDS_WITH,
        name: 'arrayEndsWith',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_NTH,
        name: 'nth',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_SPLIT_AT,
        name: 'splitAt',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_SPLIT_WHEN,
        name: 'splitWhen',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 1,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_SPLIT_WHENEVER,
        name: 'splitWhenever',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 1,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_UNIQ_WITH,
        name: 'uniqWith',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_GROUP_WITH,
        name: 'groupWith',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_CONCAT,
        name: 'concat',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_INDEX_BY,
        name: 'indexBy',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 1,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_COLLECT_BY,
        name: 'collectBy',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 1,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_DROP_REPEATS_BY,
        name: 'dropRepeatsBy',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 1,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_DROP_REPEATS_WITH,
        name: 'dropRepeatsWith',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_MAP_TO_OBJ,
        name: 'mapToObj',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 1,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_ZIP_OBJ,
        name: 'zipObj',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_GROUP_BY_PROP,
        name: 'groupByProp',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_SLICE,
        name: 'slice',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn', 'a1'],
      }),
      meta({
        op: OpCodes.OP_SWAP,
        name: 'swap',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn', 'a1'],
      }),
      meta({
        op: OpCodes.OP_INSERT_ALL,
        name: 'insertAll',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn', 'a1'],
      }),
      meta({
        op: OpCodes.OP_SPLICE,
        name: 'splice',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn', 'a1', 'a2'],
      }),
      meta({
        op: OpCodes.OP_UNION_BY,
        name: 'unionBy',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn', 'a1'],
      }),
      meta({
        op: OpCodes.OP_UNION_WITH,
        name: 'unionWith',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn', 'a1'],
      }),
      meta({
        op: OpCodes.OP_INTERSECTION_BY,
        name: 'intersectionBy',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn', 'a1'],
      }),
      meta({
        op: OpCodes.OP_DIFFERENCE_BY,
        name: 'differenceBy',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn', 'a1'],
      }),
      meta({
        op: OpCodes.OP_DIFFERENCE_WITH,
        name: 'differenceWith',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn', 'a1'],
      }),
      meta({
        op: OpCodes.OP_SYMMETRIC_DIFFERENCE_BY,
        name: 'symmetricDifferenceBy',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn', 'a1'],
      }),
      meta({
        op: OpCodes.OP_SYMMETRIC_DIFFERENCE_WITH,
        name: 'symmetricDifferenceWith',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn', 'a1'],
      }),
      meta({
        op: OpCodes.OP_WITHOUT_BY,
        name: 'withoutBy',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn', 'a1'],
      }),
      meta({
        op: OpCodes.OP_MAP_ACCUM,
        name: 'mapAccum',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 2,
        bindings: ['fn', 'a1'],
      }),
      meta({
        op: OpCodes.OP_MAP_ACCUM_RIGHT,
        name: 'mapAccumRight',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 2,
        bindings: ['fn', 'a1'],
      }),
      meta({
        op: OpCodes.OP_REDUCE_BY,
        name: 'reduceBy',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 1,
        bindings: ['fn', 'a1', 'a2'],
      }),
      meta({
        op: OpCodes.OP_TAKE_SORTED_BY,
        name: 'takeSortedBy',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn', 'a1'],
      }),
      meta({
        op: OpCodes.OP_SORTED_INDEX_BY,
        name: 'sortedIndexBy',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn', 'a1'],
      }),
      meta({
        op: OpCodes.OP_SORTED_INDEX_WITH,
        name: 'sortedIndexWith',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 1,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_SORTED_LAST_INDEX_BY,
        name: 'sortedLastIndexBy',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn', 'a1'],
      }),
      meta({
        op: OpCodes.OP_NTH_OR_UNDEFINED,
        name: 'nthOrUndefined',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_INDEX_OF_OR_UNDEFINED,
        name: 'indexOfOrUndefined',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_LAST_INDEX_OF_OR_UNDEFINED,
        name: 'lastIndexOfOrUndefined',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_FIND_LAST_OR_UNDEFINED,
        name: 'findLastOrUndefined',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 1,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_FIND_LAST_INDEX_OR_UNDEFINED,
        name: 'findLastIndexOrUndefined',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 1,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_MEAN_BY_OR_UNDEFINED,
        name: 'meanByOrUndefined',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 1,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_MEAN_BY_NON_EMPTY,
        name: 'meanByNonEmpty',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 1,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_HEAD_OR_UNDEFINED,
        name: 'headOrUndefined',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_HEAD_NON_EMPTY,
        name: 'headNonEmpty',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_LAST_OR_UNDEFINED,
        name: 'lastOrUndefined',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_LAST_NON_EMPTY,
        name: 'lastNonEmpty',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_MIN_OR_UNDEFINED,
        name: 'minOrUndefined',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_MIN_NON_EMPTY,
        name: 'minNonEmpty',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_MAX_OR_UNDEFINED,
        name: 'maxOrUndefined',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_MAX_NON_EMPTY,
        name: 'maxNonEmpty',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_ONLY_OR_UNDEFINED,
        name: 'onlyOrUndefined',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_ONLY,
        name: 'only',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_MERGE_ALL,
        name: 'mergeAll',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_TRANSPOSE,
        name: 'transpose',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_UNNEST,
        name: 'unnest',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: [],
      }),
      meta({
        op: OpCodes.OP_MAP_WITH_INDEX,
        name: 'mapWithIndex',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'one-to-one',
        callbackArity: 2,
        bindings: ['fn'],
        constructorPreserving: true,
      }),
      meta({
        op: OpCodes.OP_FILTER_WITH_INDEX,
        name: 'filterWithIndex',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'filtering',
        callbackArity: 2,
        bindings: ['fn'],
        constructorPreserving: true,
      }),
      meta({
        op: OpCodes.OP_FOR_EACH_WITH_INDEX,
        name: 'forEachWithIndex',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'sink',
        callbackArity: 2,
        bindings: ['fn'],
        pureLowering: false,
      }),
      meta({
        op: OpCodes.OP_SHUFFLE,
        name: 'shuffle',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: [],
        pureLowering: false,
      }),
      meta({
        op: OpCodes.OP_SAMPLE,
        name: 'sample',
        inputDomain: 'array',
        outputDomain: 'array',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
        pureLowering: false,
      }),
      meta({
        op: OpCodes.OP_SORTED_INDEX,
        name: 'sortedIndex',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
      meta({
        op: OpCodes.OP_SORTED_LAST_INDEX,
        name: 'sortedLastIndex',
        inputDomain: 'array',
        outputDomain: 'scalar',
        cardinality: 'materializer',
        callbackArity: 0,
        bindings: ['fn'],
      }),
    ] satisfies readonly OpMeta[]
  ).map((entry) => [entry.op, entry]),
)

/** Every opcode covered by the registry, sorted ascending. */
export const REGISTERED_OP_CODES: readonly OpCode[] = Object.freeze(
  Array.from(REGISTRY.keys()).sort((a, b) => a - b),
)

export function getOpMeta(op: OpCode): OpMeta | undefined {
  return REGISTRY.get(op)
}

export function requireOpMeta(op: OpCode): OpMeta {
  const found = REGISTRY.get(op)
  if (!found) throw new Error(`registry: no metadata for opcode ${op}`)
  return found
}

export function assertOpMeta(op: OpCode): asserts op is OpCode {
  if (!REGISTRY.has(op)) throw new Error(`registry: no metadata for opcode ${op}`)
}

export function isRegisteredOp(op: OpCode): boolean {
  return REGISTRY.has(op)
}

export function isTerminal(op: OpCode): boolean {
  const found = REGISTRY.get(op)
  return (
    found !== undefined && (found.cardinality === 'sink' || found.cardinality === 'materializer')
  )
}

export function isBoundary(op: OpCode): boolean {
  const found = REGISTRY.get(op)
  return found !== undefined && found.isMaterializationBoundary
}

export function isStreamable(op: OpCode): boolean {
  const found = REGISTRY.get(op)
  if (!found) return false
  return (
    found.cardinality === 'one-to-one' ||
    found.cardinality === 'filtering' ||
    found.cardinality === 'expanding' ||
    found.cardinality === 'stateful'
  )
}

export function allSourceOpCodes(): readonly OpCode[] {
  const codes = new Set<OpCode>()
  for (const value of Object.values(OP_CODES)) codes.add(value)
  for (const [key, value] of Object.entries(OpCodes)) {
    if (key.startsWith('OP_') && typeof value === 'number' && value !== OP_NON_FUSEABLE) {
      codes.add(value)
    }
  }
  return Object.freeze(Array.from(codes).sort((a, b) => a - b))
}

export function opName(op: OpCode): string {
  return REGISTRY.get(op)?.name ?? `op:${op}`
}
