// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

function gt(a, b) {
  return a > b;
}

function gte(a, b) {
  return a >= b;
}

function lt(a, b) {
  return a < b;
}

function lte(a, b) {
  return a <= b;
}

function min(a, b) {
  if (a < b) {
    return a;
  } else {
    return b;
  }
}

function max(a, b) {
  if (a > b) {
    return a;
  } else {
    return b;
  }
}

function minBy(f, a, b) {
  if (f(a) <= f(b)) {
    return a;
  } else {
    return b;
  }
}

function maxBy(f, a, b) {
  if (f(a) >= f(b)) {
    return a;
  } else {
    return b;
  }
}

let identicalRaw = (function(a, b) { return Object.is(a, b); });

function identical(a, b) {
  return identicalRaw(a, b);
}

function eqBy(f, a, b) {
  return Primitive_object.equal(f(a), f(b));
}

function sortWith(arr, comparators) {
  let out = arr.slice(0);
  let numComps = comparators.length;
  out.sort((a, b) => {
    let result = 0.0;
    let i = 0;
    while (i < numComps && result === 0.0) {
      let cmp = comparators[i];
      let r = cmp(a, b);
      if (r !== 0) {
        result = r < 0 ? -1.0 : 1.0;
      }
      i = i + 1 | 0;
    };
    return result;
  });
  return out;
}

function countBy(arr, f) {
  let len = arr.length;
  let dict = {};
  for (let i = 0; i < len; ++i) {
    let key = f(arr[i]);
    let n = dict[key];
    if (n !== undefined) {
      dict[key] = n + 1 | 0;
    } else {
      dict[key] = 1;
    }
  }
  return dict;
}

function innerJoin(a, b, pred) {
  let lenA = a.length;
  let lenB = b.length;
  let result = [];
  for (let i = 0; i < lenA; ++i) {
    let x = a[i];
    let j = 0;
    let found = false;
    while (j < lenB && !found) {
      if (pred(x, b[j])) {
        found = true;
        result.push(x);
      }
      j = j + 1 | 0;
    };
  }
  return result;
}

let pathEqRaw = (function(path, val, obj) {
    var cur = obj;
    for (var i = 0; i < path.length; i++) {
      if (cur == null) return false;
      cur = cur[path[i]];
    }
    return cur === val;
  });

function pathEq(path, val, obj) {
  return pathEqRaw(path, val, obj);
}

let propEqRaw = (function(prop, val, obj) { return obj[prop] === val; });

function propEq(prop, val, obj) {
  return propEqRaw(prop, val, obj);
}

export {
  gt,
  gte,
  lt,
  lte,
  min,
  max,
  minBy,
  maxBy,
  identicalRaw,
  identical,
  eqBy,
  sortWith,
  countBy,
  innerJoin,
  pathEqRaw,
  pathEq,
  propEqRaw,
  propEq,
}
/* No side effect */
