// Generated by ReScript, PLEASE EDIT WITH CARE


function isEmpty(s) {
  return s === "";
}

function length(s) {
  return s.length;
}

function trim(s) {
  return s.trim();
}

function trimStart(s) {
  return s.trimStart();
}

function trimEnd(s) {
  return s.trimEnd();
}

function startsWith(s, search) {
  return s.startsWith(search);
}

function endsWith(s, search) {
  return s.endsWith(search);
}

function includes(s, search) {
  return s.includes(search);
}

function split(s, sep) {
  return s.split(sep);
}

function toLowerCase(s) {
  return s.toLowerCase();
}

function toUpperCase(s) {
  return s.toUpperCase();
}

function slice(s, start, end_) {
  return s.slice(start, end_);
}

function replaceAll(s, search, replacement) {
  return s.replaceAll(search, replacement);
}

function repeat(s, n) {
  return s.repeat(n);
}

let matchRaw = (function(s, re) { return s.match(re) || []; });

function match_(s, regex) {
  return matchRaw(s, regex);
}

let replaceRaw = (function(s, re, rep) { return s.replace(re, rep); });

function replaceRegex(s, regex, replacement) {
  return replaceRaw(s, regex, replacement);
}

function test_(s, regex) {
  return regex.test(s);
}

let toStringRaw = (function(x) { return String(x); });

function toString_(x) {
  return toStringRaw(x);
}

function capitalize(s) {
  if (s === "") {
    return "";
  } else {
    return s.charAt(0).toUpperCase() + s.slice(1);
  }
}

function uncapitalize(s) {
  if (s === "") {
    return "";
  } else {
    return s.charAt(0).toLowerCase() + s.slice(1);
  }
}

let toCamelCaseRaw = (function(s) {
    return s.replace(/[-_\s]+(.)?/g, function(_, c) { return c ? c.toUpperCase() : ''; })
            .replace(/^[A-Z]/, function(c) { return c.toLowerCase(); });
  });

function toCamelCase(s) {
  return toCamelCaseRaw(s);
}

let toKebabCaseRaw = (function(s) {
    return s.replace(/([a-z])([A-Z])/g, '$1-$2')
            .replace(/[\s_]+/g, '-')
            .toLowerCase();
  });

function toKebabCase(s) {
  return toKebabCaseRaw(s);
}

let toSnakeCaseRaw = (function(s) {
    return s.replace(/([a-z])([A-Z])/g, '$1_$2')
            .replace(/[\s-]+/g, '_')
            .toLowerCase();
  });

function toSnakeCase(s) {
  return toSnakeCaseRaw(s);
}

let toTitleCaseRaw = (function(s) {
    return s.replace(/\b\w/g, function(c) { return c.toUpperCase(); });
  });

function toTitleCase(s) {
  return toTitleCaseRaw(s);
}

function truncate(s, maxLen, ellipsis) {
  if (s.length <= maxLen) {
    return s;
  } else {
    return s.slice(0, maxLen) + ellipsis;
  }
}

export {
  isEmpty,
  length,
  trim,
  trimStart,
  trimEnd,
  startsWith,
  endsWith,
  includes,
  split,
  toLowerCase,
  toUpperCase,
  slice,
  replaceAll,
  repeat,
  matchRaw,
  match_,
  replaceRaw,
  replaceRegex,
  test_,
  toStringRaw,
  toString_,
  capitalize,
  uncapitalize,
  toCamelCaseRaw,
  toCamelCase,
  toKebabCaseRaw,
  toKebabCase,
  toSnakeCaseRaw,
  toSnakeCase,
  toTitleCaseRaw,
  toTitleCase,
  truncate,
}
/* No side effect */
