// @ts-nocheck
// Auto-generated by codegen/dual-inline.ts — do not edit
// Source of truth: codegen/defs/


// Arity 1 — tagged for scalar JIT
export const isEmpty = /* @__PURE__ */ (() => {
  const _f: any = function isEmpty(s: any) { return s === '' }
  _f._op = 57
  return _f
})()

export const length = /* @__PURE__ */ (() => {
  const _f: any = function length(s: any) { return s.length }
  _f._op = 56
  return _f
})()

export const trim = /* @__PURE__ */ (() => {
  const _f: any = function trim(s: any) { return s.trim() }
  _f._op = 50
  return _f
})()

export const trimStart = /* @__PURE__ */ (() => {
  const _f: any = function trimStart(s: any) { return s.trimStart() }
  _f._op = 53
  return _f
})()

export const trimEnd = /* @__PURE__ */ (() => {
  const _f: any = function trimEnd(s: any) { return s.trimEnd() }
  _f._op = 54
  return _f
})()

export const toLowerCase = /* @__PURE__ */ (() => {
  const _f: any = function toLowerCase(s: any) { return s.toLowerCase() }
  _f._op = 51
  return _f
})()

export const toUpperCase = /* @__PURE__ */ (() => {
  const _f: any = function toUpperCase(s: any) { return s.toUpperCase() }
  _f._op = 52
  return _f
})()


// Arity 2 — tagged for scalar JIT
export const startsWith: {
  (s: string, search: string): boolean
  (search: string): (s: string) => boolean
} = function startsWith() {
  if (arguments.length >= 2) {
    const s = arguments[0], search = arguments[1]
    return s.startsWith(search)
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const s = data, search = _a0
    return s.startsWith(search)
  }
  return _dl
} as any


export const endsWith: {
  (s: string, search: string): boolean
  (search: string): (s: string) => boolean
} = function endsWith() {
  if (arguments.length >= 2) {
    const s = arguments[0], search = arguments[1]
    return s.endsWith(search)
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const s = data, search = _a0
    return s.endsWith(search)
  }
  return _dl
} as any


export const includes: {
  (s: string, search: string): boolean
  (search: string): (s: string) => boolean
} = function includes() {
  if (arguments.length >= 2) {
    const s = arguments[0], search = arguments[1]
    return s.includes(search)
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const s = data, search = _a0
    return s.includes(search)
  }
  return _dl
} as any


export const split: {
  (s: string, sep: string): string[]
  (sep: string): (s: string) => string[]
} = function split() {
  if (arguments.length >= 2) {
    const s = arguments[0], sep = arguments[1]
    return s.split(sep)
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const s = data, sep = _a0
    return s.split(sep)
  }
    _dl._op = 55
    _dl._fn = _a0
  return _dl
} as any


export const repeat: {
  (s: string, n: number): string
  (n: number): (s: string) => string
} = function repeat() {
  if (arguments.length >= 2) {
    const s = arguments[0], n = arguments[1]
    return s.repeat(n)
  }
  const _a0 = arguments[0]
  const _dl: any = function(data: any) {
    const s = data, n = _a0
    return s.repeat(n)
  }
  return _dl
} as any


// Arity 3
export const slice: {
  (s: string, start: number, end: number): string
  (start: number, end: number): (s: string) => string
} = function slice() {
  if (arguments.length >= 3) {
    const s = arguments[0], start = arguments[1], end = arguments[2]
    return s.slice(start, end)
  }
  const _a0 = arguments[0]; const _a1 = arguments[1]
  const _dl: any = function(data: any) {
    const s = data, start = _a0, end = _a1
    return s.slice(start, end)
  }
  return _dl
} as any


export const replaceAll: {
  (s: string, search: string, replacement: string): string
  (search: string, replacement: string): (s: string) => string
} = function replaceAll() {
  if (arguments.length >= 3) {
    const s = arguments[0], search = arguments[1], replacement = arguments[2]
    return s.replaceAll(search, replacement)
  }
  const _a0 = arguments[0]; const _a1 = arguments[1]
  const _dl: any = function(data: any) {
    const s = data, search = _a0, replacement = _a1
    return s.replaceAll(search, replacement)
  }
  return _dl
} as any

