// Generated by ReScript, PLEASE EDIT WITH CARE


let typeRaw = (function(x) {
    if (x === null) return "Null";
    if (x === undefined) return "Undefined";
    return Object.prototype.toString.call(x).slice(8, -1);
  });

function type_(x) {
  return typeRaw(x);
}

let stringToPathRaw = (function(s) {
    return s.replace(/\[(\d+)\]/g, '.$1').split('.').filter(Boolean);
  });

function stringToPath(s) {
  return stringToPathRaw(s);
}

export {
  typeRaw,
  type_,
  stringToPathRaw,
  stringToPath,
}
/* No side effect */
