import { defineConfig } from 'tsup'
export default defineConfig({
  entry: [
    'src/index.ts',
    'src/lens.ts',
    'src/dual-lite.ts',
    'src/guard.ts',
    'src/result.ts',
    'src/option.ts',
    'src/stream.ts',
    'src/array.ts',
    'src/object.ts',
    'src/dict.ts',
    'src/string.ts',
    'src/number.ts',
    'src/math.ts',
    'src/boolean.ts',
    'src/logic.ts',
    'src/function.ts',
  ],
  format: ['esm'],
  dts: true,
  clean: true,
  treeshake: true,
  minify: true,
})
