use crate::runtime_core_effects::{
    render_bitcrush, render_compressor, render_degrade, render_ensemble_chorus,
    render_frequency_shifter, render_micro_pitch, render_multi_tap_delay, render_nonlinear_reverb,
    render_phaser, render_plate_reverb, render_rotary_speaker, render_saturator, render_space_echo,
    render_spring_reverb, render_stereo_spread, render_tape_delay, render_tilt_eq,
    render_wavefolder,
};
use crate::runtime_dispatch::RenderContext;
use crate::runtime_node::RuntimeNode;
use crate::runtime_state::NodeBuffer;

#[inline(always)]
pub(super) fn render_core_effect_node(
    node: &mut RuntimeNode,
    ctx: &RenderContext<'_>,
    out: &mut NodeBuffer,
) -> Option<()> {
    match node {
        RuntimeNode::SpaceEcho {
            input,
            time_ms,
            feedback,
            mix,
            reverb_mix,
            wow,
            flutter,
            tape_age,
            drive,
            head_count,
            head1,
            head2,
            head3,
            state,
        } => render_space_echo(
            *input,
            *time_ms,
            *feedback,
            *mix,
            *reverb_mix,
            *wow,
            *flutter,
            *tape_age,
            *drive,
            *head_count,
            *head1,
            *head2,
            *head3,
            state,
            ctx.access,
            ctx.prior,
            ctx.params,
            out,
            ctx.frames,
            ctx.sample_rate,
            ctx.frame_start,
        ),
        RuntimeNode::TapeDelay {
            input,
            time_ms,
            feedback,
            mix,
            wow,
            flutter,
            tape_age,
            drive,
            tone,
            width,
            state,
        } => render_tape_delay(
            *input,
            *time_ms,
            *feedback,
            *mix,
            *wow,
            *flutter,
            *tape_age,
            *drive,
            *tone,
            *width,
            state,
            ctx.access,
            ctx.prior,
            ctx.params,
            out,
            ctx.frames,
            ctx.sample_rate,
        ),
        RuntimeNode::PlateReverb {
            input,
            pre_delay_ms,
            decay,
            damping,
            diffusion,
            modulation,
            mix,
            width,
            state,
        } => render_plate_reverb(
            *input,
            *pre_delay_ms,
            *decay,
            *damping,
            *diffusion,
            *modulation,
            *mix,
            *width,
            state,
            ctx.access,
            ctx.prior,
            ctx.params,
            out,
            ctx.frames,
            ctx.sample_rate,
        ),
        RuntimeNode::SpringReverb {
            input,
            decay,
            damping,
            tension,
            drip,
            mix,
            width,
            state,
        } => render_spring_reverb(
            *input,
            *decay,
            *damping,
            *tension,
            *drip,
            *mix,
            *width,
            state,
            ctx.access,
            ctx.prior,
            ctx.params,
            out,
            ctx.frames,
            ctx.sample_rate,
        ),
        RuntimeNode::NonlinearReverb {
            input,
            time_ms,
            decay,
            damping,
            drive,
            mix,
            width,
            state,
        } => render_nonlinear_reverb(
            *input,
            *time_ms,
            *decay,
            *damping,
            *drive,
            *mix,
            *width,
            state,
            ctx.access,
            ctx.prior,
            ctx.params,
            out,
            ctx.frames,
            ctx.sample_rate,
        ),
        RuntimeNode::Compressor {
            input,
            threshold,
            ratio,
            attack,
            release,
            knee,
            left,
            right,
            ..
        } => render_compressor(
            *input,
            *threshold,
            *ratio,
            *attack,
            *release,
            *knee,
            left,
            right,
            ctx.access,
            ctx.prior,
            ctx.params,
            out,
            ctx.frames,
            ctx.sample_rate,
        ),
        RuntimeNode::Bitcrush {
            input,
            bits,
            downsample,
            left,
            right,
            ..
        } => render_bitcrush(
            *input,
            *bits,
            *downsample,
            left,
            right,
            ctx.access,
            ctx.prior,
            ctx.params,
            out,
            ctx.frames,
        ),
        RuntimeNode::MicroPitch {
            input,
            detune,
            width,
            delay_ms,
            mix,
            state,
        } => render_micro_pitch(
            *input,
            *detune,
            *width,
            *delay_ms,
            *mix,
            state,
            ctx.access,
            ctx.prior,
            ctx.params,
            out,
            ctx.frames,
            ctx.sample_rate,
        ),
        RuntimeNode::MultiTapDelay {
            input,
            time_ms,
            feedback,
            mix,
            tone,
            width,
            taps,
            state,
        } => render_multi_tap_delay(
            *input,
            *time_ms,
            *feedback,
            *mix,
            *tone,
            *width,
            taps,
            state,
            ctx.access,
            ctx.prior,
            ctx.params,
            out,
            ctx.frames,
            ctx.sample_rate,
        ),
        RuntimeNode::Saturator {
            input,
            drive,
            asymmetry,
            tone,
            mix,
            output,
            state,
            ..
        } => render_saturator(
            *input,
            *drive,
            *asymmetry,
            *tone,
            *mix,
            *output,
            state,
            ctx.access,
            ctx.prior,
            ctx.params,
            out,
            ctx.frames,
            ctx.sample_rate,
        ),
        RuntimeNode::Wavefolder {
            input,
            drive,
            depth,
            asymmetry,
            tone,
            mix,
            output,
            state,
            ..
        } => render_wavefolder(
            *input,
            *drive,
            *depth,
            *asymmetry,
            *tone,
            *mix,
            *output,
            state,
            ctx.access,
            ctx.prior,
            ctx.params,
            out,
            ctx.frames,
            ctx.sample_rate,
        ),
        RuntimeNode::Degrade {
            input,
            bits,
            downsample,
            jitter,
            noise,
            tone,
            mix,
            state,
            ..
        } => render_degrade(
            *input,
            *bits,
            *downsample,
            *jitter,
            *noise,
            *tone,
            *mix,
            state,
            ctx.access,
            ctx.prior,
            ctx.params,
            out,
            ctx.frames,
            ctx.sample_rate,
        ),
        RuntimeNode::TiltEq {
            input,
            freq,
            gain_db,
            mix,
            state,
            ..
        } => render_tilt_eq(
            *input,
            *freq,
            *gain_db,
            *mix,
            state,
            ctx.access,
            ctx.prior,
            ctx.params,
            out,
            ctx.frames,
            ctx.sample_rate,
        ),
        RuntimeNode::StereoSpread {
            input,
            width,
            delay_ms,
            mix,
            state,
        } => render_stereo_spread(
            *input,
            *width,
            *delay_ms,
            *mix,
            state,
            ctx.access,
            ctx.prior,
            ctx.params,
            out,
            ctx.frames,
            ctx.sample_rate,
        ),
        RuntimeNode::FrequencyShifter {
            input,
            shift_hz,
            mix,
            state,
            ..
        } => render_frequency_shifter(
            *input,
            *shift_hz,
            *mix,
            state.as_mut(),
            ctx.access,
            ctx.prior,
            ctx.params,
            out,
            ctx.frames,
            ctx.sample_rate,
        ),
        RuntimeNode::RotarySpeaker {
            input,
            rate,
            depth,
            mix,
            drive,
            width,
            freq,
            state,
        } => render_rotary_speaker(
            *input,
            *rate,
            *depth,
            *mix,
            *drive,
            *width,
            *freq,
            state.as_mut(),
            ctx.access,
            ctx.prior,
            ctx.params,
            out,
            ctx.frames,
            ctx.sample_rate,
        ),
        RuntimeNode::EnsembleChorus {
            input,
            rate,
            depth,
            mix,
            width,
            tone,
            noise,
            state,
        } => render_ensemble_chorus(
            *input,
            *rate,
            *depth,
            *mix,
            *width,
            *tone,
            *noise,
            state,
            ctx.access,
            ctx.prior,
            ctx.params,
            out,
            ctx.frames,
            ctx.sample_rate,
        ),
        RuntimeNode::Phaser {
            input,
            voicing,
            rate,
            depth,
            mix,
            left,
            right,
            ..
        } => render_phaser(
            *input,
            *voicing,
            *rate,
            *depth,
            *mix,
            left,
            right,
            ctx.access,
            ctx.prior,
            ctx.params,
            out,
            ctx.frames,
        ),
        _ => unreachable!("non-core-effect node dispatched to core-effect renderer"),
    }
}
