use crate::runtime_dispatch::RenderContext;
use crate::runtime_instruments::{
    render_acid_bass, render_drum_voice, render_lofi_sampler, render_poly_synth,
    render_sampler_instrument, render_string_machine,
};
use crate::runtime_node::RuntimeNode;
use crate::runtime_state::NodeBuffer;

#[inline(always)]
pub(super) fn render_instrument_node(
    node: &mut RuntimeNode,
    ctx: &RenderContext<'_>,
    out: &mut NodeBuffer,
) -> Option<()> {
    match node {
        RuntimeNode::SamplerInstrument {
            zones,
            freq,
            velocity: node_velocity,
            attack,
            release,
            level,
            state,
        } => render_sampler_instrument(
            zones,
            ctx.trigger_freq.unwrap_or(*freq),
            *node_velocity,
            *attack,
            *release,
            *level,
            state,
            ctx.access,
            ctx.prior,
            ctx.params,
            out,
            ctx.frames,
            ctx.sample_rate,
            ctx.gate_sec,
            ctx.velocity,
        ),
        RuntimeNode::LofiSampler {
            zones,
            freq,
            velocity: node_velocity,
            attack,
            release,
            level,
            bits,
            downsample,
            jitter,
            noise,
            tone,
            drive,
            mix,
            state,
        } => render_lofi_sampler(
            zones,
            ctx.trigger_freq.unwrap_or(*freq),
            *node_velocity,
            *attack,
            *release,
            *level,
            *bits,
            *downsample,
            *jitter,
            *noise,
            *tone,
            *drive,
            *mix,
            state,
            ctx.access,
            ctx.prior,
            ctx.params,
            out,
            ctx.frames,
            ctx.sample_rate,
            ctx.gate_sec,
            ctx.velocity,
        ),
        RuntimeNode::AcidBass {
            wave,
            freq,
            velocity: node_velocity,
            cutoff,
            resonance,
            env_mod,
            decay,
            accent,
            slide,
            drive,
            level,
            state,
        } => render_acid_bass(
            *wave,
            ctx.trigger_freq.unwrap_or(*freq),
            *node_velocity,
            *cutoff,
            *resonance,
            *env_mod,
            *decay,
            *accent,
            *slide,
            *drive,
            *level,
            state,
            ctx.access,
            ctx.prior,
            ctx.params,
            out,
            ctx.frames,
            ctx.sample_rate,
            ctx.gate_sec,
            ctx.velocity,
        ),
        RuntimeNode::DrumVoice {
            kind,
            freq,
            velocity: node_velocity,
            decay,
            tone,
            snap,
            noise,
            drive,
            level,
            state,
        } => render_drum_voice(
            *kind,
            ctx.trigger_freq.unwrap_or(*freq),
            *node_velocity,
            *decay,
            *tone,
            *snap,
            *noise,
            *drive,
            *level,
            state,
            ctx.access,
            ctx.prior,
            ctx.params,
            out,
            ctx.frames,
            ctx.sample_rate,
            ctx.gate_sec,
            ctx.velocity,
        ),
        RuntimeNode::StringMachine {
            freq,
            velocity: node_velocity,
            detune,
            attack,
            release,
            tone,
            depth,
            modulation,
            width,
            level,
            state,
        } => render_string_machine(
            ctx.trigger_freq.unwrap_or(*freq),
            *node_velocity,
            *detune,
            *attack,
            *release,
            *tone,
            *depth,
            *modulation,
            *width,
            *level,
            state,
            ctx.access,
            ctx.prior,
            ctx.params,
            out,
            ctx.frames,
            ctx.sample_rate,
            ctx.gate_sec,
            ctx.velocity,
        ),
        RuntimeNode::PolySynth {
            freq,
            velocity: node_velocity,
            detune,
            pulse_width,
            sub,
            noise,
            cutoff,
            resonance,
            env_mod,
            attack,
            decay,
            sustain,
            release,
            drive,
            chorus,
            modulation,
            width,
            level,
            state,
        } => render_poly_synth(
            ctx.trigger_freq.unwrap_or(*freq),
            *node_velocity,
            *detune,
            *pulse_width,
            *sub,
            *noise,
            *cutoff,
            *resonance,
            *env_mod,
            *attack,
            *decay,
            *sustain,
            *release,
            *drive,
            *chorus,
            *modulation,
            *width,
            *level,
            state,
            ctx.access,
            ctx.prior,
            ctx.params,
            out,
            ctx.frames,
            ctx.sample_rate,
            ctx.gate_sec,
            ctx.velocity,
        ),
        _ => unreachable!("non-instrument node dispatched to instrument renderer"),
    }
}
