/**
 * Generates the compact fact table.
 *
 * Compact fusion cannot carry the operation registry: it is 20 KB of strings
 * and metadata that exist for diagnostics, and shipping it would spend most of
 * the compact byte budget on names nobody reads at runtime. Everything the
 * planner and the generic executor actually consult is cardinality and input
 * domain, which fit in one byte per opcode.
 *
 * Generated from the same definition-only records as the registry so the two
 * cannot disagree; a test asserts the agreement holds for every registered
 * opcode.
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  runtimeRecordsInOpcodeOrderV1,
  type LegacyRuntimeFactV1,
} from './protocol/operator-definitions'

const CARDINALITY = ['one-to-one', 'filtering', 'expanding', 'stateful', 'sink', 'materializer']
const DOMAIN = ['array', 'scalar', 'iterable']

const encode = (meta: LegacyRuntimeFactV1): number => {
  const cardinality = CARDINALITY.indexOf(meta.cardinality)
  const domain = DOMAIN.indexOf(meta.inputDomain)
  if (cardinality < 0 || domain < 0) {
    throw new Error(`compact facts: opcode ${meta.opcode} has unencodable metadata`)
  }
  // Bit 7 marks presence. Without it a one-to-one array operator encodes to
  // zero and is indistinguishable from an unregistered opcode.
  return cardinality | (domain << 3) | 0x80
}

const records = runtimeRecordsInOpcodeOrderV1()
const max = Math.max(...records.map(({ legacyRuntime }) => legacyRuntime.opcode))
const table = new Array<number>(max + 1).fill(0)
for (const { legacyRuntime } of records) {
  table[legacyRuntime.opcode] = encode(legacyRuntime)
}

const out = `// Auto-generated by codegen/compact-facts.ts. Do not edit.
// One byte per opcode: cardinality in bits 0-2, input domain in bits 3-4.
// Names, descriptions, and diagnostics deliberately absent -- they live in
// fusion/debug, which production compact never imports.

export const COMPACT_CARDINALITY = ${JSON.stringify(CARDINALITY)} as const
export const COMPACT_DOMAIN = ${JSON.stringify(DOMAIN)} as const

export const CARD_ONE_TO_ONE = 0
export const CARD_FILTERING = 1
export const CARD_EXPANDING = 2
export const CARD_STATEFUL = 3
export const CARD_SINK = 4
export const CARD_MATERIALIZER = 5

/** Indexed by opcode. Bit 7 set means registered; a zero entry means absent. */
export const COMPACT_FACTS = /* @__PURE__ */ Uint8Array.from([${table.join(',')}])

export const compactCardinality = (op: number): number => COMPACT_FACTS[op] & 7
export const compactDomain = (op: number): number => (COMPACT_FACTS[op] >> 3) & 3
export const isCompactRegistered = (op: number): boolean =>
  op > 0 && op < COMPACT_FACTS.length && (COMPACT_FACTS[op] & 0x80) !== 0
`

const target = join(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  'src',
  'internal',
  'compact',
  'facts.generated.ts',
)
mkdirSync(dirname(target), { recursive: true })
writeFileSync(target, out)
console.log(`compact facts: ${records.length} opcodes, ${out.length} bytes`)
