import type { AnyParam, FmOperatorIndex, NodeKind } from '../types'

const operatorIndexes = [1, 2, 3, 4, 5, 6] as const
const fmMatrixParams = operatorIndexes.flatMap((source) =>
  operatorIndexes.map((destination) => `m${source}_${destination}` as const))
const fmOperatorParams = operatorIndexes.flatMap((index) => [
  `op${index}.ratio`,
  `op${index}.level`,
  `op${index}.feedback`,
  `op${index}.output`,
] as const)

export const params = {
  osc: { freq: 'freq', detune: 'detune', phase: 'phase' },
  wavetable: { freq: 'freq', detune: 'detune', phase: 'phase', position: 'position' },
  fm: {
    freq: 'freq',
    detune: 'detune',
    index: 'index',
    ratio: (index: FmOperatorIndex) => `op${index}.ratio` as const,
    level: (index: FmOperatorIndex) => `op${index}.level` as const,
    feedback: (index: FmOperatorIndex) => `op${index}.feedback` as const,
    output: (index: FmOperatorIndex) => `op${index}.output` as const,
    matrix: (source: FmOperatorIndex, destination: FmOperatorIndex) => `m${source}_${destination}` as const,
  },
  constant: { value: 'value' },
  samplerInstrument: { freq: 'freq', attack: 'attack', release: 'release', level: 'level' },
  lofiSampler: {
    freq: 'freq',
    attack: 'attack',
    release: 'release',
    level: 'level',
    bits: 'bits',
    downsample: 'downsample',
    jitter: 'jitter',
    noise: 'noise',
    tone: 'tone',
    drive: 'drive',
    mix: 'mix',
  },
  acidBass: {
    freq: 'freq',
    cutoff: 'cutoff',
    resonance: 'resonance',
    envMod: 'envMod',
    decay: 'decay',
    accent: 'accent',
    slide: 'slide',
    drive: 'drive',
    level: 'level',
  },
  drumVoice: { freq: 'freq', decay: 'decay', tone: 'tone', snap: 'snap', noise: 'noise', drive: 'drive', level: 'level' },
  stringMachine: {
    freq: 'freq',
    detune: 'detune',
    attack: 'attack',
    release: 'release',
    tone: 'tone',
    depth: 'depth',
    modulation: 'modulation',
    width: 'width',
    level: 'level',
  },
  polySynth: {
    freq: 'freq',
    detune: 'detune',
    pulseWidth: 'pulseWidth',
    sub: 'sub',
    noise: 'noise',
    cutoff: 'cutoff',
    resonance: 'resonance',
    envMod: 'envMod',
    attack: 'attack',
    decay: 'decay',
    sustain: 'sustain',
    release: 'release',
    drive: 'drive',
    chorus: 'chorus',
    modulation: 'modulation',
    width: 'width',
    level: 'level',
  },
  gain: { amount: 'amount' },
  pan: { position: 'position' },
  biquad: { freq: 'freq', q: 'q', gainDb: 'gainDb' },
  stateVariableFilter: { freq: 'freq', resonance: 'resonance', drive: 'drive', mix: 'mix' },
  comb: { delayMs: 'delayMs', feedback: 'feedback', damp: 'damp' },
  adsr: { attack: 'attack', decay: 'decay', sustain: 'sustain', release: 'release' },
  ar: { attack: 'attack', release: 'release' },
  exponential: { tau: 'tau' },
  delay: { delayMs: 'delayMs', feedback: 'feedback', mix: 'mix' },
  reverb: { mix: 'mix' },
  distortion: { amount: 'amount' },
  chorus: { rate: 'rate', depth: 'depth', mix: 'mix' },
  ensembleChorus: { rate: 'rate', depth: 'depth', mix: 'mix', width: 'width', tone: 'tone', noise: 'noise' },
  spaceEcho: {
    timeMs: 'timeMs',
    feedback: 'feedback',
    mix: 'mix',
    reverbMix: 'reverbMix',
    wow: 'wow',
    flutter: 'flutter',
    tapeAge: 'tapeAge',
    drive: 'drive',
  },
  tapeDelay: {
    timeMs: 'timeMs',
    feedback: 'feedback',
    mix: 'mix',
    wow: 'wow',
    flutter: 'flutter',
    tapeAge: 'tapeAge',
    drive: 'drive',
    tone: 'tone',
    width: 'width',
  },
  plateReverb: {
    preDelayMs: 'preDelayMs',
    decay: 'decay',
    damping: 'damping',
    diffusion: 'diffusion',
    modulation: 'modulation',
    mix: 'mix',
    width: 'width',
  },
  springReverb: {
    decay: 'decay',
    damping: 'damping',
    tension: 'tension',
    drip: 'drip',
    mix: 'mix',
    width: 'width',
  },
  nonlinearReverb: {
    timeMs: 'timeMs',
    decay: 'decay',
    damping: 'damping',
    drive: 'drive',
    mix: 'mix',
    width: 'width',
  },
  microPitch: { detune: 'detune', width: 'width', delayMs: 'delayMs', mix: 'mix' },
  multiTapDelay: { timeMs: 'timeMs', feedback: 'feedback', mix: 'mix', tone: 'tone', width: 'width' },
  saturator: { drive: 'drive', asymmetry: 'asymmetry', tone: 'tone', mix: 'mix', output: 'output' },
  wavefolder: { drive: 'drive', depth: 'depth', asymmetry: 'asymmetry', tone: 'tone', mix: 'mix', output: 'output' },
  degrade: { bits: 'bits', downsample: 'downsample', jitter: 'jitter', noise: 'noise', tone: 'tone', mix: 'mix' },
  tiltEq: { freq: 'freq', gainDb: 'gainDb', mix: 'mix' },
  stereoSpread: { width: 'width', delayMs: 'delayMs', mix: 'mix' },
  frequencyShifter: { shiftHz: 'shiftHz', mix: 'mix' },
  rotarySpeaker: { rate: 'rate', depth: 'depth', mix: 'mix', drive: 'drive', width: 'width', freq: 'freq' },
  phaser: { rate: 'rate', depth: 'depth', mix: 'mix' },
  compressor: { threshold: 'threshold', ratio: 'ratio', attack: 'attack', release: 'release', knee: 'knee' },
  bitcrush: { bits: 'bits', downsample: 'downsample' },
} as const

const entries = <T extends Record<string, string>>(value: T): ReadonlyArray<T[keyof T]> => Object.values(value) as Array<T[keyof T]>

export const PARAMS_BY_KIND: Readonly<Record<NodeKind, ReadonlyArray<AnyParam>>> = {
  osc: entries(params.osc),
  wavetable: entries(params.wavetable),
  fm: ['freq', 'detune', 'index', ...fmOperatorParams, ...fmMatrixParams],
  noise: [],
  constant: entries(params.constant),
  buffer: [],
  samplerInstrument: entries(params.samplerInstrument),
  lofiSampler: entries(params.lofiSampler),
  acidBass: entries(params.acidBass),
  drumVoice: entries(params.drumVoice),
  stringMachine: entries(params.stringMachine),
  polySynth: entries(params.polySynth),
  input: [],
  gain: entries(params.gain),
  pan: entries(params.pan),
  mix: [],
  stereo: [],
  biquad: entries(params.biquad),
  stateVariableFilter: entries(params.stateVariableFilter),
  comb: entries(params.comb),
  adsr: entries(params.adsr),
  ar: entries(params.ar),
  exponential: entries(params.exponential),
  delay: entries(params.delay),
  reverb: entries(params.reverb),
  distortion: entries(params.distortion),
  chorus: entries(params.chorus),
  ensembleChorus: entries(params.ensembleChorus),
  spaceEcho: entries(params.spaceEcho),
  tapeDelay: entries(params.tapeDelay),
  plateReverb: entries(params.plateReverb),
  springReverb: entries(params.springReverb),
  nonlinearReverb: entries(params.nonlinearReverb),
  microPitch: entries(params.microPitch),
  multiTapDelay: entries(params.multiTapDelay),
  saturator: entries(params.saturator),
  wavefolder: entries(params.wavefolder),
  degrade: entries(params.degrade),
  tiltEq: entries(params.tiltEq),
  stereoSpread: entries(params.stereoSpread),
  frequencyShifter: entries(params.frequencyShifter),
  rotarySpeaker: entries(params.rotarySpeaker),
  phaser: entries(params.phaser),
  compressor: entries(params.compressor),
  bitcrush: entries(params.bitcrush),
}

export function hasParam(kind: NodeKind, param: AnyParam): boolean {
  return PARAMS_BY_KIND[kind].includes(param)
}
