// Auto-generated by codegen/compact-facts.ts. Do not edit.
// One byte per opcode: cardinality in bits 0-2, input domain in bits 3-4.
// Names, descriptions, and diagnostics deliberately absent -- they live in
// fusion/debug, which production compact never imports.

export const COMPACT_CARDINALITY = [
  'one-to-one',
  'filtering',
  'expanding',
  'stateful',
  'sink',
  'materializer',
] as const
export const COMPACT_DOMAIN = ['array', 'scalar', 'iterable'] as const

export const CARD_ONE_TO_ONE = 0
export const CARD_FILTERING = 1
export const CARD_EXPANDING = 2
export const CARD_STATEFUL = 3
export const CARD_SINK = 4
export const CARD_MATERIALIZER = 5

/** Indexed by opcode. Bit 7 set means registered; a zero entry means absent. */
export const COMPACT_FACTS = /* @__PURE__ */ Uint8Array.from([
  0, 128, 129, 131, 131, 131, 131, 130, 132, 132, 132, 132, 132, 132, 129, 131, 129, 132, 132, 131,
  133, 133, 132, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133,
  133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 136, 136, 136, 136, 136, 136, 136, 136, 0,
  0, 136, 136, 136, 0, 0, 0, 0, 0, 0, 0, 136, 136, 136, 136, 136, 136, 136, 0, 0, 0, 136, 136, 136,
  136, 136, 136, 136, 0, 0, 0, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 131, 133,
  133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133,
  133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133,
  133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133,
  133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133,
])

export const compactCardinality = (op: number): number => COMPACT_FACTS[op] & 7
export const compactDomain = (op: number): number => (COMPACT_FACTS[op] >> 3) & 3
export const isCompactRegistered = (op: number): boolean =>
  op > 0 && op < COMPACT_FACTS.length && (COMPACT_FACTS[op] & 0x80) !== 0
