// Op table this compiler wave understands, derived from @stopcock/fp's
// registry so opcode metadata (arity, bindings) stays a single source of
// truth. Only a subset of the registry is supported for fusion this wave;
// anything else falls through untransformed.
//
// The registry lives in @stopcock/fp's workspace source, not its public
// entry, so a packed consumer of this package can't import it at runtime.
// ops-table.ts is a checked-in snapshot generated by scripts/gen-ops-table.ts;
// ops-table.test.ts asserts it hasn't drifted from the live registry.
import { OPS_TABLE } from './ops-table'

export type StreamOpName =
  | 'map'
  | 'filter'
  | 'reject'
  | 'filterMap'
  | 'flatMap'
  | 'take'
  | 'drop'
  | 'takeWhile'
  | 'dropWhile'

export type TerminalOpName =
  | 'sum'
  | 'count'
  | 'reduce'
  | 'forEach'
  | 'find'
  | 'findIndex'
  | 'findMap'
  | 'every'
  | 'some'
  | 'none'

export type BoundaryOpName = 'sort' | 'sortBy' | 'sortAsc' | 'sortDesc' | 'reverse' | 'uniq'

export const STREAM_OPS: ReadonlySet<string> = new Set([
  'map',
  'filter',
  'reject',
  'filterMap',
  'flatMap',
  'take',
  'drop',
  'takeWhile',
  'dropWhile',
])

export const TERMINAL_OPS: ReadonlySet<string> = new Set([
  'sum',
  'count',
  'reduce',
  'forEach',
  'find',
  'findIndex',
  'findMap',
  'every',
  'some',
  'none',
])

// Boundary ops materialize the whole array (sort/reverse/uniq the entire
// thing) rather than fusing per-item into the surrounding loop -- they split
// a pipeline into loop / materialize / loop segments. sum is also classified
// a boundary in the registry (see benchmarks/src/reference/emitter.ts's
// header comment) but this compiler still fuses it as a terminal: summing
// left-to-right is associative over the same item sequence either way, so
// the output is identical and fusing it avoids an extra materialization.
export const BOUNDARY_OPS: ReadonlySet<string> = new Set([
  'sort',
  'sortBy',
  'sortAsc',
  'sortDesc',
  'reverse',
  'uniq',
])

/** Ops this wave's fuser can lower, keyed by name for source-level lookup. */
export const SUPPORTED_OP_NAMES: ReadonlySet<string> = new Set([...STREAM_OPS, ...TERMINAL_OPS, ...BOUNDARY_OPS])

const nameToArity = new Map<string, 0 | 1 | 2>()
const bareOps = new Set<string>()
for (const entry of OPS_TABLE) {
  if (!SUPPORTED_OP_NAMES.has(entry.name)) continue
  nameToArity.set(entry.name, entry.callbackArity)
  // Ops with no bound slots at all (registry bindings: []) are exported as
  // the tagged step value itself (e.g. `sum._op = 41`), not a factory you
  // call to produce one. Used bare in a pipeline: `A.sum`, never `A.sum()`
  // -- invoking them calls the data-first form with no data and throws.
  if (entry.bindingCount === 0) bareOps.add(entry.name)
}

/** Number of user-supplied callback/value arguments the op invokes, per the registry. */
export function callbackArity(name: string): 0 | 1 | 2 | undefined {
  return nameToArity.get(name)
}

/** True for ops that are used bare as a pipe step (no call), like `A.sum`. */
export function isBareOp(name: string): boolean {
  return bareOps.has(name)
}

/** True if `name` is a real op in the fp registry (recognized even if unsupported this wave). */
export function isRegistryOpName(name: string): boolean {
  return OPS_TABLE.some((entry) => entry.name === name)
}
